### ISSUE TITLE
Median is Translated wrongly for MSSQL in summarize

### ISSUE THREAD

**Issue by thothal** [tidyverse/dbplyr#1008]
Calculating the overall median does not yield valid `SQL`

```r
library(dbplyr)
library(dplyr)
d <- lazy_frame(x = 1:10, con = simulate_mssql())
d %>% summarize(med = median(x, na.rm = TRUE))
# <SQL>
# SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY `x`) AS `med`
# FROM `df`
```
The proper `SQL` syntax would look like:

```sql
--- Set up
DROP TABLE IF EXISTS #temp;
WITH rcte (x) AS (
  SELECT 1 AS x
   UNION ALL
  SELECT x + 1
    FROM rcte
   WHERE x <= 100
) 
SELECT x
  INTO #temp
  FROM rcte;

--- SQL should look like this
SELECT DISTINCT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY x) OVER () AS med
  FROM #temp;
```

Thus instead of
```sql
SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY `x`) AS `med`
  FROM `df`;
```

we would expect
```sql
SELECT DISTINCT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY `x`) OVER() AS `med`
  FROM `df`;
```

**Comment by hadley** [comment]
Could you please link to the approoriate SQL server docs for this?

**Comment by thothal** [comment]
[PERCENTILE_CONT](https://learn.microsoft.com/en-us/sql/t-sql/functions/percentile-cont-transact-sql?view=sql-server-ver16)

The `OVER` clause is not optional.

**Comment by hadley** [comment]
Ooops, looks like we already fixed this for `quantile()`, but we forgot about `median()`:

https://github.com/tidyverse/dbplyr/blob/main/R/backend-mssql.R#L361
