### ISSUE TITLE
HANA DB: SHORTTEXT casting not supported anymore?

### ISSUE THREAD

**Issue by lschneiderbauer** [tidyverse/dbplyr#1027]
I updated the Hana driver recently, and I noticed that some previously working dbplyr queries are failing now.

In particular, a data type conversion using `as.character` seems to be failing with the SQL error message
```r
Error in `collect()`:
! Failed to collect lazy table.
Caused by error in `new_result()`:
! nanodbc/nanodbc.cpp:1412: 42000: [SAP AG][LIBODBCHDB DLL][HDBODBC] Syntax error or access violation;257 sql syntax error: incorrect syntax near "SHORTTEXT": line 1 col 27 (at pos 27) 
```

An explicit example which returns that error:
```r
some_lazy_table %>% select(some_number) %>% mutate(some_text = as.character(some_number))
```
which generates the SQL
```SQL
SELECT "some_number", CAST("some_number" AS SHORTTEXT) AS "some_text"
FROM "MYSCHEMA"."some_lazy_table"
```

When looking up the [specs for CAST](https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/20db6dd475191014aa7b978452f92bbd.html), SHORTTEXT is also not mentioned as allowed data type, so I wonder if it was ever supported in the first place.

**Comment by lschneiderbauer** [comment]
`TO_VARCHAR` as well as `CAST (col AS VARCHAR)` works in my case.
That is my suggestion.

**Comment by hadley** [comment]
Would you mind provide a link to the docs of those functions?

**Comment by lschneiderbauer** [comment]
Yes, the link is already in my initial comment:
[CAST](https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/20db6dd475191014aa7b978452f92bbd.html)
[TO_VARCHAR](https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/20f226a1751910149edd8969c469d54d.html?q=TO_VARCHAR)

Or are you looking for something else?
