### ISSUE TITLE
cur_column() and sym()

### ISSUE THREAD

**Issue by p-schaefer** [tidyverse/dbplyr#1036]
I have a situation where I need to divide columns in a database, `across()` multiple columns. When the divisor column is fixed, I can use `!!rlang::sym()` to specify the correct column, but I have one instance where the divisor column changes as a function of the current columns name (i.e., `gsub("_lump_sum","_lump_noNAcount",dplyr::cur_column()`. 

See example below:

```r
library(dplyr, warn.conflicts = FALSE)

con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
copy_to(con, name ="mtcars", df=mtcars %>% mutate(across(c(gear,carb),~.*2,.names = "{col}_2")))

# This works as intended
tbl(con,"mtcars") %>% 
  summarise(across(any_of(c("vs","am")),~sum(.)/sum(!!sym("wt"))))

# This doesn't work
tbl(con,"mtcars") %>% 
  summarise(across(any_of(c("gear","carb")),~sum(.)/sum(!!sym(paste0(cur_column(),"_2")))))

# Error in `cur_column()`:
# ! Must be used inside `across()`.
```
Is there a different way of doing this?
Thanks

**Comment by mgirlich** [comment]
This cannot work because you for the evaluation of `sym(paste0(cur_column(),"_2"))` by using the `!!` operator. Therefore, this also does not work with a dataframe.
What you could do instead is use `sql(...)` instead of `!!sym(...)`:

```r
tbl(con,"mtcars") %>% 
  summarise(across(any_of(c("gear","carb")), ~sum(.) / sum(sql(paste0(cur_column(),"_2"))))) %>% 
  show_query()
```

**Comment by p-schaefer** [comment]
> This cannot work because you for the evaluation of `sym(paste0(cur_column(),"_2"))` by using the `!!` operator. Therefore, this also does not work with a dataframe. What you could do instead is use `sql(...)` instead of `!!sym(...)`:
> 
> ```r
> tbl(con,"mtcars") %>% 
>   summarise(across(any_of(c("gear","carb")), ~sum(.) / sum(sql(paste0(cur_column(),"_2"))))) %>% 
>   show_query()
> ```

That doesn't seem to work for me.

The SQL I get from that is:
```
<SQL>
SELECT
  SUM(`gear`) / SUM(cur_column() || '_2') AS `gear`,
  SUM(`carb`) / SUM(cur_column() || '_2') AS `carb`
FROM `mtcars`
```
and since `cur_column()` isn't a database function, I get an error: `Error: no such function: cur_column`

**Comment by mgirlich** [comment]
Forgot to mention that you need the dev version for this. You can install it via `devtools::install_github("tidyverse/dbplyr")`

**Comment by p-schaefer** [comment]
> Forgot to mention that you need the dev version for this. You can install it via `devtools::install_github("tidyverse/dbplyr")`

Any suggestions if I need to use `gsub`, instead of `paste`?

**Comment by mgirlich** [comment]
This seems to be a bug in how `sql()` is evaluated locally. I opened another issue for this.
