### ISSUE TITLE
passing SQL optimizer hints

### ISSUE THREAD

**Issue by lschneiderbauer** [tidyverse/dbplyr#1041]
Hi there,

is there a way to specify SQL optimizer hints to be sent with the SQL without manually modifying the generated SQL code corresponding to some lazy query?

I would like to avoid using `show_query()` and adding my hints manually.
Is there a way? I would be okay with ugly hacks. :)

Thanks!

**Comment by mgirlich** [comment]
Currently, I don't see a way of doing this. Where in the SQL code are these optimiser hints? Can you provide some examples?

**Comment by lschneiderbauer** [comment]
They are right in the end, e.g. for a Hana DB
```SQL
SELECT * FROM TABLE LIMIT 10
WITH HINT (NO_USE_HEX_PLAN, NO_ESX_JOIN)
```
(in this example of course it doesn't do anything)
I doubt this is SQL standard though.

Injecting some custom string at the end would do the trick.

**Comment by mgirlich** [comment]
I quickly had a look at SQL Server and there are [three kind of hints](https://learn.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql?view=sql-server-ver16):

* Join Hints
* Query Hints
* Table Hint

So, I get the feeling this is very special for Hana DB which makes me reluctant to support this.

Do you have any idea about the following questions:

* Are there other kind of optimiser hints for Hana DB?
* Which other databases support optimiser hints?
* How generic are these kind of hints?

By the way you don't need to use `show_query()` and add the hints manually. You should rather use `remote_query()` and then you can easily add a hint via `paste()`.

**Comment by chwpearse** [comment]
One example is Oracle SQL using hints. These hints are in comments before a query so they are different again from Hana DB and mySQL.

https://docs.oracle.com/cd/B13789_01/server.101/b10752/hintsref.htm

Is there a good way to inject plain text before/after a query in a dbplyr pipeline before the collect statement?

**Comment by mgirlich** [comment]
If I understand the documentation correct, then before or after a query is not sufficient for Oracle. Instead it has to be after e.g. `SELECT`

> A block in a statement can have only one comment containing hints following the SELECT, UPDATE, MERGE, or DELETE keyword.

To me this feels like it is getting quite complex:

* different kind of hints
* different syntax for hints
* hints have to go to specific places
* how does this interfere with dbplyr optimising the SQL code itself (multiple statements in one query)?
* might be difficult for the user to control where the hint ends up

Overall, if you need hints you should probably use SQL code directly (and/or optimise your data model and your filters/joins/selects). You could still use dbplyr to quickly generate the SQL (though I would really recommend to use the current dev version which produces much nicer SQL code!).

**Comment by lschneiderbauer** [comment]
I agree, it seems to a be mess overall, and probably not worth including.

My current solution is defining a `collect_with_hints` function, retrieving the sql code with `remote_query()` as you suggested, concatenating the hints and issuing `DBI::getGetQuery`. That's enough for my purposes.

@mgirlich have there been further improvements regarding the SQL code optimization since 2.2.1.9000 (the version I have installed)?

**Comment by mgirlich** [comment]
I can't say for sure since `.9000` is used for every dev version. The biggest improvement I think are the multiple joins in one query. They are not merged yet but you can install them via `devtools::install_github("tidyverse/dbplyr#984")`.
With this joins do not always produce a nested query but are rather combined into a single query. If there are multiple joins involved this can have huge performance benefits depending on the database, the joins, etc.

**Comment by lschneiderbauer** [comment]
I would love to test it. Unfortunately, it seems to depend on a dev-dplyr version whose installation seems to need Rtools to be installed; and I cannot install Rtools (my permissions on this company-machine are extremely limited).

**Comment by MichaelChirico** [comment]
I'm really not sure this is obscure enough to ignore entirely. Most "modern" SQL flavors I've worked with have some sort of hints, especially Spark, Presto, SQL Server, Spanner

https://spark.apache.org/docs/3.5.4/sql-ref-syntax-qry-select-hints.html
https://prestodb.io/docs/current/optimizer/cost-based-optimizations.html
https://learn.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-join?view=sql-server-ver16
https://cloud.google.com/spanner/docs/reference/standard-sql/query-syntax#hints

Unfortunately, the syntax is quite idiosyncratic, so it's not likely something that {dbplyr} would implement natively, but it would be useful to go through adding support in an extension to make sure that central {dbplyr} is well-equipped for downstream methods to write the appropriate customization.
