### ISSUE TITLE
`dbplyr_uncount` not working with Redshift backend

### ISSUE THREAD

**Issue by barnesparker** [tidyverse/dbplyr#1042]
Hi there. `dbplyr_uncount` doesn't seem to be working with a Redshift backend. I wasn't able to create a true reprex since the query requires the creation of a temp table. This is the best I could do with a connection to my company database.

``` r
library(dbplyr)
library(dplyr, warn.conflicts = F)
# private db package
library(NursaData)
# helper func from above package
con <- connect()
test <- copy_to(con, tibble(a = c(1, 2, 3)), name = "test", overwrite = T)
test |> dbplyr_uncount(2)
#> Error: Failed to prepare query: ERROR:  syntax error at or near ","
#> LINE 10:     FROM (      VALUES (1), (2)) AS drvd("..dbplyr_row_id")
#>                                    ^
```

<sup>Created on 2022-11-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mgirlich** [comment]
I think this issue is already fixed in the dev version. Can you try out and confirm?

You can install the dev version via `devtools::install_github("tidyverse/dbplyr")`.

**Comment by barnesparker** [comment]
Yep, you're right. Thanks!
