### ISSUE TITLE
Redshift varchar character length not respected by dplyr::rows_*()

### ISSUE THREAD

**Issue by samterfa** [tidyverse/dbplyr#1050]
Thank you for this amazing package! I hope this is the right place for this issue. I know that dplyr::rows_*() are experimental.

When writing a text value to a Redshift table whose column is varchar(anything larger than 256), using dplyr::rows_append() or dplyr::rows_update() seems to cast the text to varchar(256) before writing to the database. Longer texts will then fail to write even though the table should be able to accommodate them.

To reproduce the issue:
- Create a Redshift table with columns id and txt (I haven't run into this with Postgres connections but it might happen there too).
- Make the datatype of the txt column varchar(max, or anything larger than 256)
- Connect to the table using a privileged user. I use RPostgres::Redshift() (but this isn't the issue).
- This will work successfully.
```r
dplyr::rows_append(x = dplyr::tbl(src = redshift_conn, DBI::Id(schema = schema, table = table)), y = tibble(id = 1, txt = paste(rep('a', 256), collapse = '')), copy = TRUE, in_place = TRUE)
```
- This will fail with `Error: Failed to fetch row: ERROR:  value too long for type character varying(256).`
```r
dplyr::rows_append(x = dplyr::tbl(src = redshift_conn, DBI::Id(schema = schema, table = table)), y = tibble(id = 2, txt = paste(rep('a', 257), collapse = '')), copy = TRUE, in_place = TRUE)
```
- But using RPostgres::dbAppendTable() works with the same data that failed with dplyr::rows_append().
```r
RPostgres::dbAppendTable(conn = redshift_conn, name = DBI::Id(schema = schema, table = table), value = tibble(id = 2, txt = paste(rep('a', 257), collapse = '')), row.names = NULL)
```

Somewhere along the line the text value is cast from varchar(65535) to varchar(256) for rows_append() and rows_update(), and I haven't figured out where.

**Comment by mgirlich** [comment]
Does

```r
db_copy_to(
  con = con,
  table = ident("dbplyr_test_table"),
  values = tibble(id = 1, val = paste(rep('a', 257), collapse = ''))
)
```

work?
And which version of dbplyr are you using?

**Comment by samterfa** [comment]
```
db_copy_to(
    con = wh_conn,
    table = ident("dbplyr_test_table"),
    values = tibble(id = 1, val = paste(rep('a', 256), collapse = ''))
)
```
 works fine, but 
```
db_copy_to(
    con = wh_conn,
    table = ident("dbplyr_test_table"),
    values = tibble(id = 1, val = paste(rep('a', 257), collapse = '')),
    overwrite = TRUE
)
```
returns the same error. 

I'm using dbplyr 2.2.1.

Thanks.

**Comment by mgirlich** [comment]
Which package are you using to connect to Redshift (i.e. which is the first argument passed to `DBI::dbConnect()`)?
And does it work when you directly use `DBI::dbWriteTable()`?

```r
df <- tibble(id = 1, val = paste(rep('a', 257), collapse = ''))
DBI::dbWriteTable(
  conn = con,
  name = "dbplyr_test_table",
  value = df,
  overwrite = TRUE
)
db <- DBI::dbReadTable(con, "dbplyr_test_table") %>% tibble::as_tibble()
identical(df, db)
```

**Comment by samterfa** [comment]
I'm using RPostgres::Redshift() to create the connection. RPostgres::Postgres() gives a different error using the same connection parameters (including port). RPostgres version is 1.4.4.
```
df <- tibble(id = 1, val = paste(rep('a', 257), collapse = ''))
DBI::dbWriteTable(
    conn = wh_conn,
    name = "dbplyr_test_table",
    value = df,
    overwrite = TRUE
)
```
gives the same "too long..." error.

Thank you!
