### ISSUE TITLE
`where(is.*)` doesn't work properly with Oracle

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dbplyr#1058]
The following doesn't keep numeric columns though there are some.

```
con %>%  tbl(dbplyr::in_schema("my_schema", "my_table")) %>%  select(where(is.numeric))
#> Error in `sql_clause_select()`:
#> ! Query contains no columns
```

It is the same thing with `is.character` and anything I could try with `where()`, except for `where(~TRUE)` which keeps all columns as it should.

`summarize(,across(where(...))` fails the same way.

With SQLite everything seems to work.

`summarise_if()` can be used as a workaround instead of `summarize(,across(where(...))` , unfortunately it prints a message "Applying predicate on the first 100 rows" which cannot be silenced AFAICT.

**Comment by mgirlich** [comment]
This has been "fixed" in the dev version:

``` r
devtools::load_all("~/GitHub/dbplyr/")

memdb_frame(!!!mtcars) %>% 
  select(where(is.numeric))
#> Error in `select()`:
#> ! This tidyselect interface doesn't support predicates.
```

<sup>Created on 2022-12-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

In general, dbplyr does not know the column types, so that predicates cannot be used.

**Comment by moodymudskipper** [comment]
Thank, `select_if()` does work though, but I guess we can't rely on it too much for the future.
