### ISSUE TITLE
can't fetch zero rows from an ORACLE table

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dbplyr#1061]
This will freeze my console until I press 'escape'

```
my data |>
  head(0)
  collect()
```

with `head(, 1)` it works fine and instantly.

I don't know if it's technically a dbplyr bug because this freezes it too : 

```
DBI::dbGetQuery(con, 'SELECT *
FROM ("MY_SCHEMA"."MY_TABLE") 
FETCH FIRST 0 ROWS ONLY')
```

But it seems we could get around it by fetching 1 row and then subsetting 0 rows ?

**Comment by hadley** [comment]
I think it would be better to fix this upstream, in whatever database driver you're using.
