### ISSUE TITLE
Suspected typo on "Get Started" article

### ISSUE THREAD

**Issue by brian-law-rstudio** [tidyverse/dbplyr#1067]
Hello. On the "Get Started" page, I suspect a typo. 

Where it currently says:
flights_db %>%
  group_by %>%
  summarise(delay = mean(dep_time))

I suspect it should be instead "dep_delay":
flights_db %>%
  group_by %>%
  summarise(delay = mean(dep_delay))
  
 Thank you for the great package and I hope this helps. 

-Brian

**Comment by hadley** [comment]
Thanks for the fix!
