### ISSUE TITLE
Groupby and mutate (with SQL verb) fails to generate correct SQL translation

### ISSUE THREAD

**Issue by viswaduttp** [tidyverse/dbplyr#1076]
if I use group_by and mutate and use a SQL function such as "approx_percentile", the translated SQL is incorrect.  Faced this issue in Presto and is reproduced below. 

```r
mf <- memdb_frame(x = 1, y = 2)

mf |> 
  group_by(x) |> 
  mutate(k = sql("approx_percentile(y, 0.5)"),
         l = mean(y)) |> 
  show_query()
```
The output is 

```
<SQL>
SELECT
  *,
  approx_percentile(y, 0.5) AS `k`,
  AVG(`y`) OVER (PARTITION BY `x`) AS `l`
FROM `dbplyr_002` 
```

This is quite different from what I expected. the function approx_percentile should also be windowed similar to 'AVG'. 
This issue doesn't occur if I do group_by and summarize.

**Comment by mgirlich** [comment]
There is nothing wrong with the translation here. You provide custom SQL, so dbplyr does not touch this clause.
But even if you don't provide custom SQL dbplyr cannot simply append the `OVER` clause. The issue is that it does not know that `approx_percentile()` is a window function.

I think the easiest you can do if you want to keep it relatively generic is something like

```r
my_approx_percentile <- function(data) {
  win_over(
    expr = sql("approx_percentile(y, 0.5)"),
    con = remote_con(data),
    partition = group_vars(data)
  )
}

mf |> 
  group_by(x) |> 
  (\(.x) {
    mutate(
      .x,
      k = !!my_approx_percentile(.x),
      l = mean(y)
    )
  })() |> 
  show_query()
```

**Comment by viswaduttp** [comment]
Thanks for the explanation. 
A grouped mutate would be a windowed function is what I was thinking. As I would see, there are 2 strong reasons for me to expect this behaviour.
1. There might be window functions that are in a specific form of SQL and are unable to be accessed through dbplyr. So if they are placed in a `mutate` after `group_by` I expect them to behave as a window function. 
2. If the dbplyr doesn't translate these custom window functions as such, a complete SQL statement has to be inserted as below  (or a work around you suggested can be followed)
``` 
 mutate(k = sql("approx_percentile(\"y\", 0.5) OVER (PARTITION BY \"x\")"))
```
which I think is inefficient and defeats the purpose of writing in dplyr syntax.

let me know your thoughts

Thank you
