### ISSUE TITLE
slot "subclasses" from an object of a basic class ("NULL") with no slots" on Mac occasionally just happens

### ISSUE THREAD

**Issue by aleighbrown** [tidyverse/dbplyr#1077]
This error keeps happening to me occasioanlly and now seems to persist. I cannot load 'tidyverse' due to an error with `dbplyr`

I've seen this error before #779  and had previously resolved by `devtools::install_github("RobinHankin/Brobdingnag)"` 

However, for whatever reason it's not working this time 

I have reinstalled from GitHub the Brobdingnag, dplyr, and tidyverse packages. Restarted my R, restarted my computer

 

```r
> library(tidyr)

Attaching package: ‘tidyr’

The following objects are masked from ‘package:Matrix’:

    expand, pack, unpack

> library(magrittr)

Attaching package: ‘magrittr’

The following object is masked from ‘package:tidyr’:

    extract

> library(dbplyr)
Error in completeSubclasses(classDef2, class1, obj, where) : 
  trying to get slot "subclasses" from an object of a basic class ("NULL") with no slots
Error: package or namespace load failed for ‘dbplyr’:
 .onLoad failed in loadNamespace() for 'dbplyr', details:
  call: setClass(cl, contains = c(prevClass, "VIRTUAL"), where = where)
  error: error in contained classes ("character") for class “ident”; class definition removed from ‘dbplyr’
```

Version info
```
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          2.1                         
year           2022                        
month          06                          
day            23                          
svn rev        82513                       
language       R                           
version.string R version 4.2.1 (2022-06-23)
nickname       Funny-Looking Kid     
```

**Comment by mgirlich** [comment]
Sorry, this is not a dbplyr issue and there is nothing we can do about it. It might be due to another package you have installed. You could have a look at [this issue from Brobdingnag](https://github.com/RobinHankin/Brobdingnag/pull/21) to find other packages that might cause this.
Or you could try to figure out which package is responsible for this, maybe by adapting this reprex from Hadley

```r
requireNamespace("Brobdingnag")
#> Loading required namespace: Brobdingnag
requireNamespace("Matrix")
#> Loading required namespace: Matrix
methods::setOldClass(c("ident", "character"))
#> Error in completeSubclasses(classDef2, class1, obj, where) : 
#>   trying to get slot "subclasses" from an object of a basic class ("NULL") with no slots
#> Error in setClass(cl, contains = c(prevClass, "VIRTUAL"), where = where): error in contained classes ("character") for class "ident"; class definition removed from '.GlobalEnv'
```

and replacing Brobdingnag by other packages you have installed. Though, I can't promise you can figure it out like this.

@hadley In the other issue you mentioned a fix to R

> I pinged Michael Lawrence about this and he also pushed a fix to R-devel: [wch/r-source@3d97199](https://github.com/wch/r-source/commit/3d9719966830a29576c5f0b62465c0175aac2942)

Do you know when/whether this is going to happen? I didn't find anything in the R changelog.

**Comment by mgirlich** [comment]
Closing this because it is not a dbplyr issue. Sorry we couldn't help you.

**Comment by lanjlgle** [comment]
I also encountered this error, but only when I open a rstudio project which had been created  before, nor a newly created project or a new R session. 

Then, I guess some objects related to dbplyr may be loaded from '.RData'. If I add "library(dbplyr)", the error never occur any more. Hope helps.
