### ISSUE TITLE
slow `tbl(con, ...)` access to view, caused by db_query_fields.DBIConnection implementation

### ISSUE THREAD

**Issue by yuhenghuang** [tidyverse/dbplyr#1082]
## Situation

The `tbl(con, ...)` function to access tables on DB is very slow and costly when the target table is actually a `VIEW`. 

## Investigation 

I checked the implementation and DB logs and found that

```sql
SELECT * FROM `view_name` WHERE (0 = 1)
```

was executed to query the fields of the table. This statement is general and cheap for real tables, but for views, this is a disaster for some DBs, including the *Snowflake* I am currently using.

In the previous version of `dbplyr`, a solution is to overload the `dplyr::db_query_fields(con, sql, ...)` S3 method with your own function in a more suitable way. For example the `odbc::dbListFields` can be used in the customized implementation (e.g. `db_query_fields.OdbcConnection`) because it doesn't have problems with views when getting field names.

Since major version 2, a new function `dbplyr_query_fields` has been used to query the fields of table. This function is not an S3 method so it is not possible to overload it directly. But as far as I saw in the source code, it's only a wrapper for the original `db_query_fields.DBIConnection()` to serve some purposes, like downward compatibility. In the implementation of this new function, `dbplyr_query_fields`, `dbplyr_fallback` is called to indirectly handle the call of `db_query_fields.DBIConnection` and here is the problem. [This line](https://github.com/tidyverse/dbplyr/blob/v2.2.1/R/db.R#L81),

> fun <- sym(paste0(.generic, ".DBIConnection"))

dictates that regardless of the type of the connection `con`, only the `db_query_fields.DBIConnection` shall be called.

Overloading `dplyr::db_query_fields` (in my case it's `db_query_fields.OdbcConnection`) won't work at present.

## Summary

I think this issue is more likely a feature request than a bug report.

1. Is there any way for the users to optimize the `db_query_fields` method without changing anything in `dbplyr` or other loaded libraries in this version?

2. If the answer to question 1 is no, then does the team have any plan to optimize `db_query_fields` in the following releases? Such as writing the optimized version of overlading S3 method for each backends?

3. If the answer to question 2 is no, then will the team consider giving back the freedom of overloading `db_query_fields` to the users?

Thanks in advance!

Have a nice day.

P.S. This is only a toy example...
```r
library(dbplyr)

# prepare DB and table/view
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
dplyr::copy_to(con, mtcars, "remote_view")

# `tbl` can be very costly if it's remote view instead of real table
# considering the result earned at the cost is only field names...
# it's even more costly than it already was
remote_view <- dplyr::tbl(con, "remote_view")
```

**Comment by mgirlich** [comment]
For now you can use the `vars` argument (this is an argument from `tbl_sql()` but `tbl()` passes it on via `...`).

**Comment by yuhenghuang** [comment]
Thanks for the answer! It solves my problem.
I didn't know the `%||%` operator in [this line](https://github.com/tidyverse/dbplyr/blob/v2.2.1/R/tbl-sql.R#L19) before.
> vars <- vars %||% dbplyr_query_fields(src$con, from)

**Comment by yuhenghuang** [comment]
In case someone having the same problem comes to this issue, here is an example of the solution.
```r
# connection
con <- DBI::dbConnection(odbc::odbc(), "Snowflake")

# table field names in string format
# works well for real table, view and temp table 
vars <-   odbc::dbListFields(con, "table", catalog_name = con@info$dbname, schema_name = "schema")

# fast because no need to request fields by `SELECT * FROM schema.table WHERE (0 = 1);`
df <- tbl(con, in_schema("schema", "table"), vars = vars)
```
