### ISSUE TITLE
fill() does not work with Databricks ODBC driver

### ISSUE THREAD

**Issue by fabkury** [tidyverse/dbplyr#1083]
This is similar to https://github.com/tidyverse/dbplyr/issues/651 and https://github.com/tidyverse/dbplyr/issues/1026, but for Databricks the server expects:

`LAST_VALUE(expr, true)`

instead of

`LAST_VALUE(expr) IGNORE NULLS`

The `true` there means _"yes, ignore nulls"_: https://docs.databricks.com/sql/language-manual/functions/last_value.html

I was able to make it work by running this prior to `fill()`:

```
`last_value_sql.Spark SQL` <- function(con, x) {
  dbplyr:::build_sql("LAST_VALUE(", ident(as.character(x)), ", true)", con = con)
}
```

Thanks to all involved for the awesome resource that is `dbplyr`.

**Comment by mgirlich** [comment]
The spark implementation lives in sparklyr. Please open an issue there.
