### ISSUE TITLE
Multiple warnings : "ORDER BY is ignored in subqueries without LIMIT"

### ISSUE THREAD

**Issue by bobbymc0** [tidyverse/dbplyr#1092]
## ORDER BY is ignored in subqueries without LIMIT

**Issue** 
Script output is filled with the same warning message (over and over again, +30 times) :

_ORDER BY is ignored in subqueries without LIMIT
Do you need to move arrange() later in the pipeline or use window_order() instead?_

I have the same issue everywhere (local, databricks, Hadoop, etc.)
I don't know exactly what is causing the warning but it appears generally when I use dplyr::group_by() with dplyr::arrange().

---
**Reproducible example** 
```r
library("dplyr"); library("sparklyr") 
spark_version <- "3.1.3"
sc <- spark_connect(master = "local", version = spark_version)

# --- coping mtcars data into spark for the example
sdf_mtcars = sdf_copy_to(sc = sc, x = mtcars, name = "sdf_mtcars")

# --- example generating the warning message (twice)
# note : I had to use mutate() twice to make the warning appear
# the warning does not appear in this simple example with if only one of the two columns cum_mpg or max_mpg is created
example_mtcars = sdf_mtcars %>%
  group_by(cyl) %>%
  arrange(mpg, .by_group = TRUE) %>%
  mutate(cum_mpg = cumsum(mpg)) %>%
  mutate(max_mpg = cummax(mpg)) %>%
  ungroup() %>% 
  sdf_collect()
```
**Warning messages** : 
1: ORDER BY is ignored in subqueries without LIMIT
ℹ Do you need to move arrange() later in the pipeline or use window_order() instead? 
2: ORDER BY is ignored in subqueries without LIMIT
ℹ Do you need to move arrange() later in the pipeline or use window_order() instead? 

---
**utils::sessionInfo()** 
- R version 4.2.1 (2022-06-23)
- other attached packages:
[1] dbplyr_2.2.1   sparklyr_1.7.8 dplyr_1.0.10  

(but the warning is the same with other older versions of those packages, R and spark)

Thank you.

**Comment by mgirlich** [comment]
I think the warning gives a pretty good hint what you should try to do. You learn the most if you try to understand what the warning is telling you and try to solve the problem yourself 😉
If you still have no success, please post what you tried out and then we can still help you 😄

**Comment by bobbymc0** [comment]
I am not sure the warnings are supposed to be here. 
For example, if the 2 columns cum_mpg et max_mpg are created inside the same mutate(), then the warnings do not appear :

```
example_mtcars = sdf_mtcars %>%
  group_by(cyl) %>%
  arrange(mpg, .by_group = TRUE) %>%
  mutate(cum_mpg = cumsum(mpg),
  max_mpg = cummax(mpg)) %>%
  ungroup() %>% 
  sdf_collect()
```

**Comment by hadley** [comment]
Isn't `window_order()` exaclty what you need here?

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

mtcars |>
  tbl_lazy() |> 
  window_order(mpg) |> 
  mutate(
    cum_mpg = cumsum(mpg),
    max_mpg = cummax(mpg),
    .by = cyl
  )
#> <SQL>
#> SELECT
#>   *,
#>   SUM(`mpg`) OVER (PARTITION BY `cyl` ORDER BY `mpg` ROWS UNBOUNDED PRECEDING) AS `cum_mpg`,
#>   MAX(`mpg`) OVER (PARTITION BY `cyl` ORDER BY `mpg` ROWS UNBOUNDED PRECEDING) AS `max_mpg`
#> FROM `df`
```

<sup>Created on 2023-01-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by fh-mthomson** [comment]
I encountered this same puzzle and the error message was very informative -- `window_order()` was a perfect substitute. Accordingly I adapted my logic along the lines of:
```
if (inherits(., "tbl_sql")) {
  dbplyr::window_order(., x)
} else {
  dplyr::arrange(., c)
}
``` 

Would it be reasonable to embed similar behavior in the lazy tbl method for `arrange()`? 

cc: @fh-dObeng

**Comment by hadley** [comment]
@fh-mthomson I don't it makes sense to change the behaviour of `arrange()` since using `window_order()` won't actually yield the same result (i.e. the rows won't be ordered). That's why we give a warning so that the user can figure out what to do.

**Comment by iangow** [comment]
> Isn't `window_order()` exaclty what you need here?
> 
> ```r
> library(dbplyr)
> library(dplyr, warn.conflicts = FALSE)
> 
> mtcars |>
>   tbl_lazy() |> 
>   window_order(mpg) |> 
>   mutate(
>     cum_mpg = cumsum(mpg),
>     max_mpg = cummax(mpg),
>     .by = cyl
>   )
> #> <SQL>
> #> SELECT
> #>   *,
> #>   SUM(`mpg`) OVER (PARTITION BY `cyl` ORDER BY `mpg` ROWS UNBOUNDED PRECEDING) AS `cum_mpg`,
> #>   MAX(`mpg`) OVER (PARTITION BY `cyl` ORDER BY `mpg` ROWS UNBOUNDED PRECEDING) AS `max_mpg`
> #> FROM `df`
> ```
> 
> Created on 2023-01-17 with [reprex v2.0.2](https://reprex.tidyverse.org)

@Hadley 

Interestingly, [R4DS (2e)](https://r4ds.hadley.nz/databases.html#sec-sql-expressions) says:

> Here it’s important to [arrange()](https://dplyr.tidyverse.org/reference/arrange.html) the data, because SQL tables have no intrinsic order. In fact, if you don’t use [arrange()](https://dplyr.tidyverse.org/reference/arrange.html) you might get the rows back in a different order every time! Notice for window functions, the ordering information is repeated: the ORDER BY clause of the main query doesn’t automatically apply to window functions.

I was confused by this guidance, as I took the warnings and always use `window_order()` for these situations.

(But note I still get weird behaviour at times, see #1248.)

**Comment by jeffwitmer11** [comment]
Regardless if `window_order()` works for the use case in this thread:

1. The warning is unclear.  The `ORDER BY` in the subquery is not ignored, per se, it just that the resultant data frame is not ordered. But the ordering is still happening in the groups. 
2. If `dplyr::arrange()` behaves differently on a Spark data frames, should this be an error instead of a warning? It feels half-baked that `dplyr::arrange()` can be used with Spark data frames in the same way it can be used with in-memory data frames but only for some use cases.

**Comment by hadley** [comment]
Closing this thread because I believe dbplyr is already doing the best that it can here.
