### ISSUE TITLE
Translate nzchar()

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/dbplyr#1094]
I think `nzchar()` has an ANSI representation as `x <> ""`.

We could also be more precise and take `keepNA` into account:

 - `nzchar(x, keepNA = TRUE)` ➡️  `x <> ""`
 - `nzchar(x, keepNA = FALSE)` ➡️  `(x IS NULL OR x <> "")`

**Comment by mgirlich** [comment]
Thanks for including the SQL translation. I mentioned you in the NEWS entry to honour that 😄
