### ISSUE TITLE
Joins with copy_to = TRUE fail when source has no default or current schema

### ISSUE THREAD

**Issue by fh-afrachioni** [tidyverse/dbplyr#1099]
When I connect to a Snowflake database without specifying a schema, and the database lacks a default schema, joins which `copy_to` the connection fail.

**Example**
```
snowflake_tbl %>%
  left_join(local_tbl, copy = TRUE)
```
throws
```
Error in `db_copy_to()` at dbplyr/R/verb-copy-to.R:75:4:
! Can't copy to table "dbplyr_003"
Caused by error in `dplyr::db_write_table()` at dbplyr/R/db-io.R:56:8:
! Can't write table "dbplyr_003".
Caused by error in `new_result()`:
! nanodbc/nanodbc.cpp:1594: 00000: Cannot perform CREATE TEMPTABLE. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.
```

**Thoughts**
The call to `copy_to` enabling `copy = TRUE` passes a `unique_table_name` and the connection object:
```
# verb-copy-to.R:94
auto_copy.tbl_sql <- function(x, y, copy = FALSE, ...) {
  copy_to(x$src, as.data.frame(y), unique_table_name(), ...)
}
```
I imagine it would be safe to use the same schema where `x` is stored as the destination for `y`.  Could we extract the schema name from `y` here and update the third argument as `in_schema(schema_name, unique_table_name())`?  This raises a related question about the best way to extract a schema name from a lazy tbl; I've been taking an inelegant approach by inspecting `some_tbl$[ops | lazy_query]$x[$x[$x ...]]]` but there's likely something I'm missing.

**Further**
For odbc connections, dbplyr currently calls `dplyr::db_write_table` (effectively `DBI::dbWriteTable` / `odbc:::odbc_write_table`) with a plain string as the `name` argument (`dbplyr_003`, etc).  On backends with many schemas and tables, this leads to very bad performance (~15 minutes of hang for me), as iteration over all schemas and tables is needed to find a match (via `odbcConnectionColumns`).

When an `Id` is supplied as the `name` argument to `odbc::odbc_write_table` instead, its catalog, schema, and table names are [passed to `odbc::odbcConnectionColumns`, and ultimately `SQLColumns` on the driver](https://github.com/r-dbi/odbc/blob/111cedfe2aacb1ca4f87016814fb7d295f7dfb3f/R/Connection.R#L145), enabling much faster execution.

I think it's important, then, that an `Id` encapsulating the schema and table names is passed to `db_write_table` in `db_copy_to.DBIConnection`.

---
dbplyr version: current `main` (`861b08fc4b538822299fb8cb414a98a6b066ad0d`)
R version: 4.2.2

**Comment by mgirlich** [comment]
Extracting the schema from a lazy table currently isn't always possible. I'm currently working on improving the handling of schemas in general but this requires a bit more effort.
I don't think it is worth the effort for the special case of Snowflake and a connection without a specified schema and not default schema in the database.
For the other issue I created a separate issue as this could affect more users.
