### ISSUE TITLE
Question regarding inspection of query objects

### ISSUE THREAD

**Issue by lschneiderbauer** [tidyverse/dbplyr#1111]
Hi,
this is not really a bug, but a question (I apologize if this is not the right place, but I don't know where to put that otherwise).

I have given a dbplyr `query` object, for instance made by
```r
query <- 
   ref_table %>%
   # ... whatever we want to do here
   filter(col1 == "some_filter") %>%
   select(col2)
```

Is there a way to inspect this object `query` in retrospect and find out which basic tables and columns it is referring to?
I tried to experiment with `query$lazy_table` and traversing the tree (for instance using `$x`, `$joins` and `$selects$expr`) and picking up the information near the "leaves" of the tree.
But I fear I am missing something out (for example I am not successful retrieving some columns used in `filter` when not explicitly selected.
Also, I guess this approach is not "stable" in the sense that it accesses internal dbplyr data and you might change that structure in the future.

My use case: We are maintaining a collection of queries, and for documentation purposes it would be easier to just retrieve this information directly (to generate the documentation) instead of maintaining this information twice.
Ideally, I would have a function, say `get_source_deps(query)` which returns the basic table / column dependencies in the source system.

**Comment by mgirlich** [comment]
No, this isn't possible currently. It sounds like an interesting use case.
For things like `filter()` you would have to do something like we do in `dbplyr:::expr_uses_var()`.
@krlmlr Does this sound interesting for you? E.g. in the dm package?

**Comment by krlmlr** [comment]
Thanks, I'll think about it.

**Comment by hadley** [comment]
This is an interesting idea, but I'd say it's out of scope for dbplyr currently.
