### ISSUE TITLE
`compute` doesn't handle errors with DBI::Id tables

### ISSUE THREAD

**Issue by But2ene** [tidyverse/dbplyr#1113]
Since version 2.3.0, handling errors in `compute` method doesn't work with DBI::Id tables in the "name" parameter. I work with Teradata, but it looks like it applies to all databases.

The reprex
```r
library(dplyr)
db <- DBI::dbConnect(<connection info>)
target_name <- DBI::Id(schema = "my_shema", table = "my_table")

DBI::dbCreateTable(db, name = "test_compute", fields = c(my_id = "INTEGER"), temporary = TRUE)
DBI::dbCreateTable(db, name = target_name, fields = c(my_id = "INTEGER"), temporary = TRUE)

# should fail because `target_name` already exists
tbl(db, "test_compute") %>%
  compute(
    name = target_name,
    indexes = list("my_id"),
    temporary = FALSE
)
```

The following error appears
```
Error in as.character.default(target_name) : 
  no method for coercing this S4 class to a vector
Called from: as.character.default(target_name)
```

With debugging, it comes from [db_save_query](https://github.com/tidyverse/dbplyr/blob/b16399f4fb7d862f84ca7f12fb6d4502390a3e12/R/db-sql.R#L908). It seems it started with the use of `cli_abort`. DBI::Id tables cannot be converted to character directly. Maybe it applies somewhere else in the code ?

**Comment by mgirlich** [comment]
Thanks for filing the issue. Indeed there were a couple of other places with the same issue.
