### ISSUE TITLE
Databricks / JDBC connection : Parsing error

### ISSUE THREAD

**Issue by homer3018** [tidyverse/dbplyr#1114]
I have a JDBC connection to a Databricks environment using their JDBC driver and a token along with the packages RJDBC and DBI. I then want to use that connection with DBPLYR.

I can successfully do
```
>dbGetQuery(con, "SELECT * FROM cycle_time_analysis.test LIMIT 5")
```
However, this does not work :
```
>tbl(con, "cycle_time_analysis.test")

Error in dbSendQuery(conn, statement, ...) : 
  Unable to retrieve JDBC result set
  JDBC ERROR: [Databricks][DatabricksJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: org.apache.hive.service.cli.HiveSQLException: Error running query: [PARSE_SYNTAX_ERROR] org.apache.spark.sql.catalyst.parser.ParseException: 
[PARSE_SYNTAX_ERROR] Syntax error at or near '"cycle_time_analysis.test"': extra input '"cycle_time_analysis.test"'(line 2, pos 5)

== SQL ==
SELECT *
FROM "cycle_time_analysis.test" AS "q21"
-----^^^
WHERE (0 = 1)

	at org.apache.spark.sql.hive.thriftserver.HiveThriftServerErrors$.runningQueryError(HiveThriftServerErrors.scala:48)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.$anonfun$execute$1(SparkExecuteStatementOperation.scala:498)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.unity.EmptyHandle$.runWith(UCSHandle.scala:124)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$s
```

Thinking that it was a translation issue, i've tried a number of things around these statements 
```
sql_translation.JDBCConnection <- dbplyr:::`sql_translation.Microsoft SQL Server`
sql_select.JDBCConnection <- dbplyr:::`sql_query_select.Microsoft SQL Server`
```

This is `SQL` but I've tried `Hive` and others without luck.

Is this supposed to work ? I would think so if only I can tell it which translator to use.
Thanks ahead of time for your help.

Edit : Using `in_schema("cycle_time_analysis", "test")` does not change anything and I'm still getting the parsing error.

**Comment by mgirlich** [comment]
It seems you want to query the table `test` in the schema `cycle_time_analysis`. To query tables in a schema you need to use the `in_schema()` function, e.g. `in_schema("cycle_time_analysis", "test")`.
Does this solve your issue?

**Comment by homer3018** [comment]
Apologies. I should have mentioned that I tried that as well, but the output remains identical.
I'll edit my post accordingly.

**Comment by mgirlich** [comment]
Can you post the output of `as.sql(in_schema("cycle_time_analysis", "test"), con)`?

**Comment by homer3018** [comment]
`as.sql(in_schema("cycle_time_analysis", "test"), con)` gives 
```
<IDENT> "cycle_time_analysis"."test"
```

**Comment by mgirlich** [comment]
Thanks. So it seems that the escape characters aren't correct. Maybe you forgot to add the `identifier.quote`. From their help I found this:

```r
JDBC("com.mysql.jdbc.Driver",
           "/etc/jdbc/mysql-connector-java-3.1.14-bin.jar",
           identifier.quote="`")
```

**Comment by homer3018** [comment]
Unfortunately adding the `identifier.quote` argument does not change anything.
`tbl(con, "cycle_time_analysis.test")` is still giving me the exact same error, and `as.sql(in_schema("cycle_time_analysis", "test"), con)` also gives me the same output.

Can I ask why you closed it ?
