### ISSUE TITLE
Cannot join 3+ tables with the same column name

### ISSUE THREAD

**Issue by lentinj** [tidyverse/dbplyr#1130]
Hello!

Joining 2 tables results in sensible SQL, but any more results in the second table being used repeatedly:-

```r
> library(magrittr)
> library(dplyr, warn.conflicts = FALSE)
> library(dbplyr, warn.conflicts = FALSE)
>
> packageVersion('dplyr')
[1] ‘1.1.0’
> packageVersion('dbplyr')
[1] ‘2.3.0’
>
> lf <- lazy_frame(x = 1, a = 1)
> lf2 <- lazy_frame(x = 1, b = 2)
> lf3 <- lazy_frame(x = 1, b = 3)
> lf4 <- lazy_frame(x = 1, b = 4)
> lf5 <- lazy_frame(x = 1, b = 5)
>
> left_join(lf, lf2, by = "x") %>%
+   left_join(lf3, by = "x") %>%
+   left_join(lf4, by = "x") %>%
+   left_join(lf5, by = "x")
<SQL>
SELECT
  `df...1`.*,
  `df...2`.`b` AS `b.x`,
  `df...3`.`b` AS `b.y`,
  `df...3`.`b` AS `b.x.x`,
  `df...3`.`b` AS `b.y.y`
FROM `df` AS `df...1`
LEFT JOIN `df` AS `df...2`
  ON (`df...1`.`x` = `df...2`.`x`)
LEFT JOIN `df` AS `df...3`
  ON (`df...1`.`x` = `df...3`.`x`)
LEFT JOIN `df` AS `df...4`
  ON (`df...1`.`x` = `df...4`.`x`)
LEFT JOIN `df` AS `df...5`
  ON (`df...1`.`x` = `df...5`.`x`)
```

Note the LEFT JOIN clauses are reasonable, but the SELECTs have got "stuck" on ``df...3``.

It seems highly likely that this is related to #865, the previous stack-of-subqueries SQL formulation as generated by dbplyr 2.2.1 could produce working queries for this sort of request.

FWIW in our actual use case we are rename()ing the joins first, to give the additional columns unique names, but that only affects the column aliases in the generated SQL, it still gets stuck on the second sub-select.

**Comment by mgirlich** [comment]
Thanks for filing the issue. This is fixed in the dev version (install via `devtools::install_github("tidyverse/dbplyr")`).
