### ISSUE TITLE
(Bug) Window Frame and Filter create unexpected SQL query (wrong order)

### ISSUE THREAD

**Issue by gui-salome** [tidyverse/dbplyr#1135]
**Context:** 
I am using `dbplyr::window_order` and `dbplyr::window_frame` to create windowed sums of a variable. For some rows I might not have enough data points for a full windowed sum, i.e., I am at the end of my data, but need data for the next few days. In this case the windowed sum would be NA or a partial sum, depending on what row you are (see example in reprex). Then, to remove these rows without a full window, I use `dplyr::filter`. 

**Problem:**
 Even though the windowed sum calculation comes before the use of `dplyr::filter`, the values are actually calculated as if the `dplyr::filter` was applied before the windowed calculations, yielding wrong summations. See the reprex below for a small example, and the expected vs actual SQL query generated.

**Example:**
```r
# Create the following table 
data <- tibble::tibble(
                 identification = c(1,1,1),
                 date = c(1,2,3),
                 value = c(1,1,1)
               )
# Write the data to a remote server before continuing
```
![Screenshot 2023-02-07 at 3 56 35 PM](https://user-images.githubusercontent.com/68299186/217363873-954b4910-3bbe-4767-b2a8-fea9313e0a67.png)

```r
# Calculate windowed sums
sums <- data %>%
    dplyr::group_by(identification) %>%
    dbplyr::window_order(identification, date) %>%
    dbplyr::window_frame(
              from = 1,
              to = 2
            ) %>%
    dplyr::mutate(
             summed = sum(value, na.rm = TRUE)
           ) %>%
    dplyr::ungroup()
```
![Screenshot 2023-02-07 at 3 58 20 PM](https://user-images.githubusercontent.com/68299186/217364207-44bd78ad-80bb-440f-9640-b1d55d71e10a.png)

The problem happens here:
```r
# Remove the rows without a full window
dplyr::filter(sums, date <= 1)
```
Output:
![Screenshot 2023-02-07 at 4 00 41 PM](https://user-images.githubusercontent.com/68299186/217364623-1e9d4603-6f04-429d-9c90-ded12b93eada.png)
Expected:
![Screenshot 2023-02-07 at 4 00 41 PM copy](https://user-images.githubusercontent.com/68299186/217364846-291478fe-91bb-463c-bd42-8a1b55c11d5e.png)

This is the query generated:
```r
SELECT
  *,
  SUM("value") OVER (PARTITION BY "identification" ORDER BY "identification", "date" ROWS BETWEEN 1 FOLLOWING AND 2 FOLLOWING) AS "summed"
FROM "vrvkvwtftvhrekibsploqvthpfjmzt"
WHERE ("date" <= 1.0)
```
Notice that the filter is added directly to the select statement, instead of being added to a second select statement after the windowed sum is calculated. This is the query I expected (since filtering comes after the creation of the windowed sums):
```r
SELECT
  *
FROM (
  SELECT
    *,
    SUM("value") OVER (PARTITION BY "identification" ORDER BY "identification", "date" ROWS BETWEEN 1 FOLLOWING AND 2 FOLLOWING) AS "summed"
  FROM "vrvkvwtftvhrekibsploqvthpfjmzt"
  WHERE ("date" <= 1.0)
  );
```

**Comment by mgirlich** [comment]
Thanks. Fixed in the dev version (which you can install via `devtools::install_github("tidyverse/dbplyr")`).
