### ISSUE TITLE
Support `reframe()`

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dbplyr#1148]
Not quite sure how to handle this.

* `mutate()` doesn't have the constraint on the number of rows, e.g. when using the SQL function `unnest()` it can increase/decrease the number of rows
* for the SQL translation it is necessary to know whether a verb is like `mutate()` or `summarise()` to decide whether to use a window function or not
* or should it simply throw an unsupported error?

**Comment by DavisVaughan** [comment]
One of the reasons for putting `reframe()` in a separate function from `summarise()` was that dbplyr could just say "we don't support `reframe()` because that isn't something most data bases can do"

That could be the default behavior, with some restrictions lifted if a data base does have those capabilities?

**Comment by mgirlich** [comment]
Actually, `SELECT` itself doesn't really care about how many rows are returned. I think there are 2 situations:

1. an aggregation function is used: every expression in `SELECT` must create 1 row per group
2. no aggregation function: do whatever you want. One example is [`UNNEST()`](https://www.w3resource.com/PostgreSQL/postgresql_unnest-function.php) or `GENERATE_SERIES()` which would be the right fit for `reframe()`. And these functions are now very common.

With the recent dplyr version SQL now feels very limited and not expressive... In particular, I love the new safety for joins with `unmatched` and `multiple`.

**Comment by mgirlich** [comment]
Decided to simply not support `reframe()` for now. At least this gives a more informative error. The alternative would be to define reframe the same as summarise.
Closed by 0b2840aa7e0e3f8052720112ee22bf435ebcfd4a
