### ISSUE TITLE
SQLite now supports FULL JOINS

### ISSUE THREAD

**Issue by hadley** [tidyverse/dbplyr#1150]
``` r
library(DBI)

con <- dbConnect(RSQLite::SQLite())
dbWriteTable(con, "df1", data.frame(x = c(1, 2)))
dbWriteTable(con, "df2", data.frame(x = c(2, 3)))

dbGetQuery(con, "SELECT COALESCE(df1.x, df2.x) FROM df1 FULL JOIN df2 ON df1.x = df2.x")
#>   COALESCE(df1.x, df2.x)
#> 1                      1
#> 2                      2
#> 3                      3
```

<sup>Created on 2023-02-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

And it's no longer mentioned in https://www.sqlite.org/omitted.html

**Comment by mgirlich** [comment]
And also `RIGHT JOIN`, for more than [half a year](https://www.sqlite.org/releaselog/3_39_0.html) already. I like them mentioning "long overdue":

> Add (long overdue) support for [RIGHT and FULL OUTER JOIN](https://www.sqlite.org/lang_select.html#rjoin).
