### ISSUE TITLE
Wrong `rows_upsert()` test

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dbplyr#1162]
With RSQLite >= 2.3.0, the ```"`rows_upsert()` works with `in_place = TRUE` and `returning`"``` test fails. I believe that the test is wrong.

With Postgres:

```sh
psql <<EOF
CREATE TEMPORARY TABLE a(x int PRIMARY KEY, y int);
INSERT INTO a (x, y) VALUES (1, 11), (2, 12), (3, 13);
CREATE TEMPORARY TABLE b(x int, y int);
INSERT INTO b (x, y) VALUES (2, 22), (3, 23), (4, 24);
INSERT INTO a (x, y) SELECT * FROM b WHERE true ON CONFLICT (x) DO UPDATE SET y = excluded.y RETURNING a.x, a.y;
EOF
```

```
CREATE TABLE
INSERT 0 3
CREATE TABLE
INSERT 0 3
 x | y
---+----
 2 | 22
 3 | 23
 4 | 24
(3 rows)

INSERT 0 3
```

dbplyr version:

``` r
library(dplyr, warn.conflicts = FALSE)
library(dbplyr)
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql
con <- RPostgres::postgresDefault()
x <- copy_to(con, tibble(x = 1:3, y = 11:13), name = "df_x", overwrite = TRUE, unique_indexes = "x")
y <- copy_to(con, tibble(x = 2:4, y = 22:24), name = "df_y", overwrite = TRUE)
df_upserted <- rows_upsert(
  x, y,
  by = "x",
  in_place = TRUE,
  returning = everything()
)
get_returned_rows(df_upserted)
#> # A tibble: 3 × 2
#>       x     y
#>   <int> <int>
#> 1     2    22
#> 2     3    23
#> 3     4    24
```

<sup>Created on 2023-02-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

With RSQLite 2.2.20:

``` r
library(dplyr, warn.conflicts = FALSE)
library(dbplyr)
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql
con <- src_memdb()
x <- copy_to(con, tibble(x = 1:3, y = 11:13), name = "df_x", overwrite = TRUE, unique_indexes = "x")
y <- copy_to(con, tibble(x = 2:4, y = 22:24), name = "df_y", overwrite = TRUE)
df_upserted <- rows_upsert(
  x, y,
  by = "x",
  in_place = TRUE,
  returning = everything()
)
get_returned_rows(df_upserted)
#> # A tibble: 1 × 2
#>       x     y
#>   <int> <int>
#> 1     4    24
```

<sup>Created on 2023-02-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Results consistent with Postgres when using RSQLite 2.3.0 (which upgrades to 3.40.1).

The triggering change in the SQLite sources is here: https://github.com/r-dbi/RSQLite/commit/52516c78d4335fcc2e1e03b2e98754d015982ab8#diff-3130402057210a5a9cb567610268ca9d5a732ca340f7d2815b197c5804020186L145442 . The changelog for 3.40.1 only contains "Various obscure fixes" (line 145442)...

**Comment by mgirlich** [comment]
I remember being surprised by the behaviour in SQLite only returning the inserted row. The new behaviour is definitely correct according to the documentation:

> A RETURNING clause for an [UPSERT](https://www.sqlite.org/lang_upsert.html) reports both inserted and updated rows.

**Comment by mgirlich** [comment]
Thanks for the detailed issue! We plan to have a minor release soon.
