### ISSUE TITLE
Feature Request: Add Pipe-able version of sql_query_save

### ISSUE THREAD

**Issue by carlganz** [tidyverse/dbplyr#1165]
Sometimes when building complex queries with `dbplyr` it is helpful to be able to save a table without collecting and pulling into memory like `copy_to`. `sql_query_save` can do this, but the interface is clearly not intended for handling `tbl` objects, so I once wrote a naive wrapper function along the lines of:

```r
# use this instead of copy_to so we don't pull data into memory
save_temp_table <- function(tbl, temp_name) {
  con <- tbl[[1]]$con
  dbExecute(con, glue(
    "IF OBJECT_ID('tempdb..{temp_name}') IS NOT NULL
DROP TABLE {temp_name};\n",sql_query_save(con, db_sql_render(con, tbl), name = as.sql(temp_name, con))), immediate = TRUE)

  tbl(con, temp_name)
}
```
Ideally I wouldn't have to glue sql strings together and it would be better to have interface along lines of:

```{r}
my_remote_tbl %>% 
mutate() %>% 
filter() %>% 
save_into('new_table_name',  ...all same parameters as copy_to) %>% 
can_continue_doing_stuff_on_new_table()
```

**Comment by mgirlich** [comment]
Probably you're looking for

> [compute()](https://dplyr.tidyverse.org/reference/compute.html) stores the results in a remote table

😄

**Comment by carlganz** [comment]
Oh wow that's embarrassing. It would be nice to have the option to save into a specific table and not just a temporary table without copying to memory, but maybe there's already a function for that I missed 😄

**Comment by mgirlich** [comment]
It is possible 😄 Just use `compute(temporary = FALSE)`. Unfortunately, you only find this argument when doing `?compute.tbl_sql`, not via `?compute`, so it is quite difficult to find 😞
