### ISSUE TITLE
Trouble creating a DuckDB table with `dbplyr::sql`

### ISSUE THREAD

**Issue by chriscardillo** [tidyverse/dbplyr#1173]
When attempting to use `dbplyr::sql` to create a `dplyr::tbl` using a `duckdb` connection, I receive the following error:

```
Error: Parser Error: syntax error at or near "SELECT"
LINE 2: FROM SELECT * FROM items AS q01
```

Please see reprex below.

```r
# Creating connection and data
con <- DBI::dbConnect(duckdb::duckdb(), dbdir = ":memory:")
DBI::dbExecute(con, "CREATE TABLE items(item VARCHAR, value DECIMAL(10,2), count INTEGER)")
DBI::dbExecute(con, "INSERT INTO items VALUES ('jeans', 20.0, 1), ('hammer', 42.2, 2)")

# Confirming data is in the db
DBI::dbGetQuery(con, "SELECT * FROM items")

# Works
dplyr::tbl(con, "items")

# Does not work
dplyr::tbl(con, dbplyr::sql(paste("SELECT * FROM items")))
```

The above, `dplyr::tbl(con, dbplyr::sql(paste("SELECT * FROM items")))`, currently works in other SQL dialects, including Snowflake, Postgres, and SQLite.

**Comment by chriscardillo** [comment]
Hope this is helpful, found that the following works:

```r
dplyr::tbl(con, dbplyr::sql(paste("(SELECT * FROM items)")))
```

(Please excuse the unnecessary `paste`)

**Comment by mgirlich** [comment]
This is an issue in the duckdb package., in their `tbl.duckdb_connection()` method. Can you please open an issue there?
