### ISSUE TITLE
Error in ._jobjRef_dollar(x[["jobj"]], name) :   no field, method or inner class called 'use_cli_format'

### ISSUE THREAD

**Issue by rbcavanaugh** [tidyverse/dbplyr#1186]
I am working with an amazon redshift db and getting this error now with dbplyr 2.3.1. Reverting to 2.2.1 fixes the error. It appears to occur when there are multiple joins in a query, for example:

Apologies up front - I don't know how I can create a reprex for this. Happy to do so if there are suggestions (are there any public redshift dbms I can test on?). 

```r
tbl(con, "table") |>
    inner_join(table2, by = "by_var") |>
    inner_join(table3, by = "other_by_var") |>
    collect()
```

many thanks -

**Comment by mgirlich** [comment]
Which package do you use to connect to Redshift? What is the class of `con`?
