### ISSUE TITLE
TIMESTAMP is incorrect CAST type for MySQL & MariaDB

### ISSUE THREAD

**Issue by avsdev-cw** [tidyverse/dbplyr#1189]
Similar to: https://github.com/tidyverse/dbplyr/pull/1011

DATETIME is the correct cast type: 
https://mariadb.com/kb/en/cast/
https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast

**Comment by avsdev-cw** [comment]
Also related, (see the links in the first post), DOUBLE/FLOAT is the correct CAST type for numeric, not NUMERIC.

**Comment by mgirlich** [comment]
Do you want to create a PR for this? 😄

**Comment by avsdev-cw** [comment]
Done :smile:
