### ISSUE TITLE
Wrong Results/Bug with last() function when using dbplyr in r

### ISSUE THREAD

**Issue by lorenzolightsgdwarf** [tidyverse/dbplyr#1214]
I'm using dplyr 1.0.9 and dbplyr 2.2.1 to query a PostgreSQL db.

I'm facing the same issue described in https://stackoverflow.com/questions/74486303/wrong-results-bug-with-last-function-when-using-dbplyr-in-r

Basically, the translation of something like 
```r
df %>% dplyr::arrange(timstamp)%>%dplyr:group_by(id)%>%dplyr::mutate(last_el = dplyr::last(element))
```

will result in a SQL query that does not have the 

```sql
RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
```

part inside LAST_VALUE(....), which leads to wrong results.

**Comment by mgirlich** [comment]
Could you please create a reprex for this? See https://dbplyr.tidyverse.org/articles/reprex.html for more information how to do this.
And could you check whether this still happens with dbplyr 2.3.1 or even better if you check with the dev version: `devtools::install_github("tidyverse/dbplyr")`. Thanks 😄

**Comment by lorenzolightsgdwarf** [comment]
Sorry, I should have checked in the latest master. It works perfectly since 2.3.0

```r
library(dplyr)
library(dbplyr)

mf <- memdb_frame(g = c(1, 1, 2, 2, 2), x = 1:5, y = 5:1)

mf%>%
  dplyr::group_by(g)%>%
  dplyr::arrange(x)%>%
  dplyr::mutate(last_val = dplyr::last(y))%>%show_query() 
``` 

```
# Source:     SQL [5 x 4]
# Database:   sqlite 3.40.1 [:memory:]
# Groups:     g
# Ordered by: x
      g     x     y last_val
  <dbl> <int> <int>    <int>
1     1     1     5        4
2     1     2     4        4
3     2     3     3        1
4     2     4     2        1
5     2     5     1        1

SELECT
  *,
  LAST_VALUE(`y`) OVER (PARTITION BY `g` ORDER BY `x` ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS `last_val`
FROM `dbplyr_001`
ORDER BY `x`
```
