### ISSUE TITLE
Inclusion of 'suffix' as argument to sql_join_suffix intentional?

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/dbplyr#1218]
https://github.com/tidyverse/dbplyr/blob/dbc81685d0da72c0f0949939b6dec95457a34a98/R/verb-joins.R#L346

The call here includes `suffix`, but the included methods to `sql_join_suffix()` just ignore any argument but `con=`:

https://github.com/tidyverse/dbplyr/blob/dbc81685d0da72c0f0949939b6dec95457a34a98/R/db.R#L45-L53

It _does_ seem a bit redundant to me, but maybe I'm missing something.

Discovered b/c of my own error -- I wrote a `sql_join_suffix` method with signature `(con)`, not `(con, ...)`.

**Comment by mgirlich** [comment]
I added `suffix` as an argument to `sql_join_suffix()`. I think it makes sense to have the `suffix` argument so that methods can check whether the suffix might work or not.
