### ISSUE TITLE
Not aliasing tables breaks sql_on()

### ISSUE THREAD

**Issue by khkk378** [tidyverse/dbplyr#1227]
I noticed that the new version no longer aliases left/right side of a join as LHS/RHS. I'm sure there are some advantages to that, but it breaks existing sql_on() code and also makes it more difficult to write such statements. If nothing else the documentation should reflect this new behavior. Thanks!

**Comment by mgirlich** [comment]
Can you provide a reprex where you use `sql_on` and the aliases aren't LHS/RHS? We tried to make sure that the LHS/RHS alias is kept if `sql_on` is used.

**Comment by mgirlich** [comment]
Closing this as there is no reprex. Happy to reopen if you provide a reprex.
