### ISSUE TITLE
db_copy_to.DBIConnection needs to pass forward arguments

### ISSUE THREAD

**Issue by halpo** [tidyverse/dbplyr#1237]
the method `db_copy_to.DBIConnection` does not appropriately pass forward extra arguments as it should.  This causes problems such as passing extra arguments such as `append`.  I do not have a reprex as that would require a working database connection, but here is the result that I received with a working database.

```r
copy_to(db, DX_mapping, name= "DX_mapping", temporary=FALSE, overwrite=FALSE, append=TRUE)
```
which results in the error

```
Error in `db_copy_to()`
! Can't copy to table "\"DX_mapping\""
Caused by error in `dplyr::db_write_table()`:
! Can't write table "\"DX_mapping\"".
Caused by error:
! Table "DX_mapping" exists in database, and both overwrite and append are FALSE.
Backtrace:
 1.  dplyr::copy_to(...)
 2.  dplyr:::copy_to.DBIConnection(...)
 4.  dbplyr:::copy_to.src_sql(...)
 6.  dbplyr:::db_copy_to.DBIConnection(...)
13. dbplyr:::db_write_table.DBIConnection(...)
```

This is the result of `db_copy_to.DBIConnection()` not passing `...` through to `dplyr::db_write_table()` in file [db-io.R:76-81](https://github.com/tidyverse/dbplyr/blob/fd36f7c9b9c2a3c919fae892fecb10443649779f/R/db-io.R#L76-L81).

**Comment by mgirlich** [comment]
Seems reasonable to me.
