### ISSUE TITLE
`tidyr::replace_na` not translating

### ISSUE THREAD

**Issue by carlganz** [tidyverse/dbplyr#1247]
According to NEWS.md `tidyr::replace_na` has been supported since version 2.1.0

```
library(dplyr) # 1.1.1
library(dbplyr) # 2.3.2
library(tidyr) # 1.3.0

### need to setup your own SQL Server connection
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
x <- tibble(
  id = "id",
  x = 1:3,
  y = c("A", NA, "B")
)
copy_to(con, x, overwrite = T)
x2 <- tbl(con, "x")

x %>%
  mutate(y = replace_na(y, "X"))

# error: no such function: replace_na
x2 %>%
  mutate(y = replace_na(y, "X"))
```

**Comment by ejneer** [comment]
To use `replace_na` you'll need to pipe the df to it directly and pass replacements as a list. I realize the `replace_na` docs specify the `data` arg as a data frame or a vector, but this may be one of those areas where things don't translate to sql 1:1 exactly. If you want to stick with the `mutate` call you can use `coalesce` instead (they generate the same query)

``` r
library(dplyr)
library(dbplyr)

df <- memdb_frame(
  id = "id",
  x = 1:3,
  y = c("A", NA, "B")
)

df |> tidyr::replace_na(list(y = "X"))
#> # Source:   SQL [3 x 3]
#> # Database: sqlite 3.39.2 [:memory:]
#>   id        x y    
#>   <chr> <int> <chr>
#> 1 id        1 A    
#> 2 id        2 X    
#> 3 id        3 B

df |> tidyr::replace_na(list(y = "X")) |> show_query()
#> <SQL>
#> SELECT `id`, `x`, COALESCE(`y`, 'X') AS `y`
#> FROM `dbplyr_001`

df |> mutate(y = coalesce(y, "X"))
#> # Source:   SQL [3 x 3]
#> # Database: sqlite 3.39.2 [:memory:]
#>   id        x y    
#>   <chr> <int> <chr>
#> 1 id        1 A    
#> 2 id        2 X    
#> 3 id        3 B

df |> mutate(y = coalesce(y, "X")) |> show_query()
#> <SQL>
#> SELECT `id`, `x`, COALESCE(`y`, 'X') AS `y`
#> FROM `dbplyr_001`
```

<sup>Created on 2023-04-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by carlganz** [comment]
Gosh how embarrassing. I guess rule of thumb is `tidyr` functions exist outside of `dplyr` functions. Sort of interesting `replace_na` has an `across` like syntax for handling multiple columns since `across` didn't exist yet when it was written.
