### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by cseidman** [tidyverse/dbplyr#126]
In the "Introduction to dbplyr" the author recommends the following when deciding to use a database: 

> As well as working with local in-memory data stored in data frames, dplyr also works with remote on-disk data stored in databases. This is particularly useful in two scenarios:
> 
> Your data is already in a database.
> 
> You have so much data that it does not all fit into memory simultaneously and you need to use some external storage engine.
> 
> (If your data fits in memory there is no advantage to putting it in a database: it will only be slower and more frustrating).

This is actually not completely accurate as it's literally written.

I suggest this should be qualified to give the following reasons as well:
1) Dataset is relatively small (up to a million rows or less)
2) It's only a "one-off" project where the overhead of creating the database takes longer than wait times
3) It's a single user project, so data consistency and multi-user concurrency aren't issues 

Or alternatively, make no mention of when a database should be used or not as this is a large subject that depends on too many variables to mention in an introduction

**Comment by hadley** [comment]
While not 100% technically accurate, I think the current wording is still useful.
