### ISSUE TITLE
Is there a way to render_sql with schema

### ISSUE THREAD

**Issue by scottporter** [tidyverse/dbplyr#1275]
I'm using Sybase, which I know there isn't a back end for.  I've gotten pretty far just connecting with JDBC.  But one of the issues I'm working through right now is that Sybase really seems to want you to call tables including the schema name.  `dbplyr::render_sql` strips those out, even if the original object I started with was created using the `dbplyr::in_schema` method.

Is there an option that can be specified somewhere to force `dbplyr` to hang onto the schema I specified at the beginning?  Or if that isn't possible, just to force it to render with a default schema I specify?

**Comment by mgirlich** [comment]
I don't really understand what you mean. Can you provide examples of the generated SQL and what you would like to see instead.

**Comment by scottporter** [comment]
As I went to pull a reprex, I realized that I've been going back and forth between `dbplyr` and `sparklyr` (trying to access this database both directly and via spark).  And I realize that dbplyr behaves properly.  It's the `sparklyr::spark_read_jdbc` that drops the schema.

I'll document here the good behavior I see from dbplyr before closing.  I'll need to confirm behavior in `sparklyr` and potentially open an issue there.

So, `dbplyr` is behaving well.

```
my_table_ref <- dplyr::tbl(con,dbplyr::in_schema("my_necessary_schema",my_table))
my_pipeline <- my_table_ref %>%
  dplyr::ungroup() %>%
  dplyr::summarize(max_numeric_month = max(numeric_month, na.rm = TRUE) )
 
dbplyr::sql_render(my_pipeline)
# <SQL> SELECT MAX("numeric_month") AS "max_numeric_month"
# FROM "my_necessary_schema"."my_table"  
```
Where with a similar approach connecting this database to spark drops the schema.  Sorry for the false alarm.
