### ISSUE TITLE
MariaDB doesn't support `RETURNING` in update queries

### ISSUE THREAD

**Issue by avsdev-cw** [tidyverse/dbplyr#1279]
"returning" parameter of rows_update, rows_upsert and rows_patch causes invalid SQL syntax to be generated.

As per the MariaDB documentation, "RETURNING" can only be used in INSERT, REPLACE and DELETE queries.

**Comment by mgirlich** [comment]
I added a more informative error when using `returning` in `rows_update/patch()` for MariaDB.
`rows_upsert()` isn't supported for MariaDB for now. If you need it, it would be great if you could add a PR.
