### ISSUE TITLE
missing importFrom(methods, is)

### ISSUE THREAD

**Issue by bastistician** [tidyverse/dbplyr#1295]
In a {methods}-free R session (from, e.g., `R_DEFAULT_PACKAGES=NULL`) ,
`example(copy_inline)` gives:

```
cpy_nl> df <- data.frame(x = 1:3, y = c("a", "b", "c"))

cpy_nl> con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")

cpy_nl> copy_inline(con, df)
Error in `purrr::map_lgl()`:
ℹ In index: 1.
ℹ With name: x.
Caused by error in `is()`:
! could not find function "is"
```

because `methods::is` is used with no import here:

https://github.com/tidyverse/dbplyr/blob/d1ffec5de1c6b80c9eb1f32be7acaef73a0a80d2/R/backend-sqlite.R#L146

**Comment by mgirlich** [comment]
Thanks for the detailed description. Fixed via 3a57ac65af7a9a4227f7a9edf13b888010bab32c.
