### ISSUE TITLE
missing \alias

### ISSUE THREAD

**Issue by bastistician** [tidyverse/dbplyr#1312]
https://github.com/tidyverse/dbplyr/blob/a5b80d88db92e46117a222572f0a352aa3d055d2/man/backend-mssql.Rd#L3-L4

The help pages entitled "Backend: Hive", "Backend: Impala", and "Backend: SQL server" lack an `\alias` entry. They are included in the PDF manual but not linked from the HTML index nor accessible via `help()` as there is no associated topic.

**Comment by mgirlich** [comment]
Thanks for opening the issue and the detailed description.
