### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by hadley** [tidyverse/dbplyr#1318]
@mgirlich can we plan to do a release in the near future to fix https://cran.r-project.org/web/checks/check_results_dbplyr.html? (the alias problem, not the odbc one). Or should I do a hot patch?

**Comment by hadley** [comment]
Or do I normally do the releases?

**Comment by mgirlich** [comment]
This depends on how soon you want to release. There are a couple of breaking changes which also caused issues in some packages. Some of them are already fixed, some of them are still in the PR state but they all haven't made it to CRAN yet.

**Comment by hadley** [comment]
CRAN wants a release by 2023-07-12. So maybe a hot patch is better?

**Comment by ablack3** [comment]
I vote for a release so that joins work on Oracle again. https://github.com/tidyverse/dbplyr/issues/1177

**Comment by mgirlich** [comment]
@ablack3 We can do a hot patch release and then aim for a release not so long afterwards.

**Comment by cjyetman** [comment]
I would love #1185 to be finally included in a release also.

**Comment by hadley** [comment]
Closing this issue since this isn't an open call for what people would like in a release.
