### ISSUE TITLE
Unable to connect to bigqueyr table in dev version

### ISSUE THREAD

**Issue by oobd** [tidyverse/dbplyr#1326]
Hi, not sure if the issue is caused by #1287 or something else but I am unable to connect to bigquery tables using the latest dev version of the package. 

```{r}
library(dplyr)
library(dbplyr)
library(DBI)

conn = DBI::dbConnect(
    bigrquery::bigquery(),
    project = 'bigquery-public-data',
    dataset = "covid19_public_forecasts",
    KeyFilePath = "covid19_public_forecasts",
    OAuthMechanism = 0
)
dbListTables(conn)

state_14d <- tbl(conn, 'state_14d')
```

Using a public bigquery dataset, I get the following error when running the tbl command. 
Error in strsplit(name, ".", fixed = TRUE) : non-character argument

Package versions are:
dbplyr: 2.3.2.9000
dplyr: 1.1.2
DBI: 1.1.3

**Comment by rbcavanaugh** [comment]
I've been seeing this error too using the AlloUs Research program's workbench. The error only seems to occur when no other SQL is added to the query at least in this case. I"ve tried with CRAN and dev versions of dplyr/dbplyr. Thanks!

For example, this would not work:
```
tbl(con, "mtcars")
```

This works:
```
tbl(con, "mtcars") |> select(cyl)
```

Here's the error from our actual db:

```
Error in strsplit(name, ".", fixed = TRUE): non-character argument
Traceback:

1. tbl(con, "observation")
2. tbl.DBIConnection(con, "observation")
3. tbl(dbplyr::src_dbi(src, auto_disconnect = FALSE), from = from, 
 .     ...)
4. tbl.src_dbi(dbplyr::src_dbi(src, auto_disconnect = FALSE), from = from, 
 .     ...)
5. tbl_sql(c(subclass, "dbi"), src = src, from = from, ...)
6. vars %||% dbplyr_query_fields(src$con, from)
7. dbplyr_query_fields(src$con, from)
8. dbplyr_fallback(con, "db_query_fields", ...)
9. eval_bare(expr((!!fun)(con, ...)))
10. dplyr::db_query_fields(con, ...)
11. db_query_fields.BigQueryConnection(con, ...)
12. as_bq_table(con, sql)
13. as_bq_table.BigQueryConnection(con, sql)
14. strsplit(name, ".", fixed = TRUE)
15. ```

**Comment by hadley** [comment]
Looks like it was reported in https://github.com/r-dbi/bigrquery/issues/509 and fixed in https://github.com/r-dbi/bigrquery/pull/512

**Comment by paulcbauer** [comment]
Apologies.. what is the status of this/final solution? 

I am using bigrquery_1.4.2 dbplyr_2.4.0    dplyr_1.1.3  and getting the error `Fehler in strsplit(name, ".", fixed = TRUE) : nicht-character Argument` when running `dplyr::tbl(bq_conn, '...') `. Not sure what previous package versions I should resort to.

**Comment by paulcbauer** [comment]
That would be great. Thank you.

**Comment by hadley** [comment]
@paulcbauer it's fixed

**Comment by paulcbauer** [comment]
It works. Thank you!

**Comment by dzion** [comment]
This is not yet fixed in the version(s) of the packages on CRAN, correct @hadley? I am seeing the same issue as @paulcbauer.

> Apologies.. what is the status of this/final solution?
> 
> I am using bigrquery_1.4.2 dbplyr_2.4.0 dplyr_1.1.3 and getting the error `Fehler in strsplit(name, ".", fixed = TRUE) : nicht-character Argument` when running `dplyr::tbl(bq_conn, '...') `. Not sure what previous package versions I should resort to.

**Comment by paulcbauer** [comment]
Not on CRAN yet I think but you can install the development versions which worked for me:

```
install.packages("pak")
pak::pak("r-dbi/bigrquery")
pak::pak("tidyverse/dbplyr")
```

**Comment by dzion** [comment]
Thanks. That works for me as well. However, I need it in a production app, where I don't want to use development versions of packages. Alas, I will (need to) wait.
