### ISSUE TITLE
Pyodc hive connection from windows is prefixing ..hive keyword to table names is there a way to  handle it

### ISSUE THREAD

**Issue by srikanthtist** [tidyverse/dbplyr#1338]
Pyodc hive connection from windows is prefixing ..hive keyword to table names is there a way to  handle it

I am running python script on windows and hive is installed on Linux... I am able to establish success connection but unable to access tables in hive.. eg if table name is products then connection prefixes Hive...products. using 64 bit odbc

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>. You can use the examples in [Reprexes for dbplyr](https://dbplyr.tidyverse.org/articles/reprex.html) as a starting point for your reprex.

Brief description of the problem

```r
# insert reprex here
```

**Comment by mgirlich** [comment]
I can't quite follow what your issue is. Can you please try to describe it in more detail and add a reprex.

**Comment by srikanthtist** [comment]
I have written python script in windows I am trying to connect hive
database using pyodc. I am able to connect to hive database successfully
but unable to read data from table as ..hive keyword is getting prefixed

I have used ODBC DataSource 64bit to create userdsn named DEV and the
driver is
Cloudera ODBC Driver for Apache Hive

Code
Import pyodbc
import pandas as pd
con =pyodbc.connect('DSN=DEV",autocommit=True)
query="select * from product"
cur=con.cursor()
cur.execute(query)
cur.close()

Error
Table or view not found Hive..product'

Note:- Hive keyword getting prefixed
