### ISSUE TITLE
Approximate number of rows ?

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dbplyr#1339]
Counting rows can be slow on databases, but this information is often stored (though not necessarily up to date) in meta tables. Could we have a way to fetch it through dbplyr ?

Displaying it in the header when printing would seem like a net win at least ? And there could be a new verb `db_approx_count()` mentioned in `?count`.

chatgpt got me this as a start: 

1. MySQL:
   In MySQL, you can use the `SHOW TABLE STATUS` command to get information about a table, including the number of rows. The query would look like this:

   ```sql
   SHOW TABLE STATUS LIKE 'your_table_name';
   ```

   In the result set, you can find the row count under the column `Rows`.

2. PostgreSQL:
   In PostgreSQL, you can use the `pg_stat_all_tables` system view to get statistics about all tables in the database. The query would look like this:

   ```sql
   SELECT schemaname, tablename, n_live_tup AS row_count
   FROM pg_stat_all_tables
   WHERE schemaname = 'your_schema_name' AND tablename = 'your_table_name';
   ```

   The `n_live_tup` column represents the number of live (non-deleted) rows in the table.

3. SQL Server:
   In SQL Server, you can use the `sys.dm_db_partition_stats` dynamic management view to get row count information. The query would look like this:

   ```sql
   SELECT OBJECT_NAME(object_id) AS table_name, row_count
   FROM sys.dm_db_partition_stats
   WHERE object_id = OBJECT_ID('your_schema_name.your_table_name') AND index_id IN (0, 1);
   ```

   The `row_count` column provides the number of rows in the specified table.

4. Oracle:
   In Oracle, you can use the `ALL_TABLES` or `USER_TABLES` data dictionary views to get information about tables, including the number of rows. The query would look like this:

   ```sql
   SELECT table_name, num_rows
   FROM all_tables
   WHERE owner = 'YOUR_SCHEMA_NAME' AND table_name = 'YOUR_TABLE_NAME';
   ```

   The `num_rows` column contains the number of rows in the specified table.

**Comment by mgirlich** [comment]
@hadley What do you think? We could also add this to the header when printing a simple table.

**Comment by hadley** [comment]
Since it only affects tables, and not queries, and I know there are issues with counts for at least Postgres, I don't think this is going to be worth the effort.
