### ISSUE TITLE
CRAN failures

### ISSUE THREAD

**Issue by hadley** [tidyverse/dbplyr#1362]
https://cran.r-project.org/web/checks/check_results_dbplyr.html

Need to fix by  2023-09-26

**Comment by mgirlich** [comment]
This one is a bit tricky. It seems that the timezone `US/Central` isn't supported anymore on Debian used by CRAN and `ISOdatetime(2000, 1, 2, 3, 4, 5, tz = "US/Central")` also doesn't seem to warn there. Also see the documentation from `ISOdatetime()`:

> If TZ is set but invalid, most platforms default to ‘⁠UTC⁠’, the time zone colloquially known as ‘⁠GMT⁠’ (see https://en.wikipedia.org/wiki/Coordinated_Universal_Time). (Some but not all platforms will give a warning for invalid values.) 

It seems that `America/New_York` still works (at least that's what lubridate uses}, so let's try switching to this.

**Comment by hadley** [comment]
Should I do a patch release next week/

**Comment by hadley** [comment]
@mgirlich I'll do a patch release tomorrow.
