### ISSUE TITLE
`n_distinct` with `group_by` produces incorrect SQL for MSSQL

### ISSUE THREAD

**Issue by carlganz** [tidyverse/dbplyr#1366]
```r
library(dbplyr)

con_test <- simulate_mssql()

translate_sql(n_distinct(y), con = con_test, vars_group = "x")
```
[Use of DISTINCT is not allowed with the OVER clause in MSSQL. ](https://stackoverflow.com/questions/53517860/count-distinct-over-partition-by-sql)

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(dbplyr)

translate_sql(n_distinct(y), con = simulate_mssql(), vars_group = "x")
#> <SQL> COUNT(DISTINCT `y`) OVER (PARTITION BY `x`)
```

<sup>Created on 2023-11-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Not clear what we can do here except throw a clearer error message.
