### ISSUE TITLE
Support Firebird-Backends in tbl()?

### ISSUE THREAD

**Issue by KRRLP-PL** [tidyverse/dbplyr#1367]
Hi all,

I'm not 100% sure if my issue should be addressed here or over at [r-dbi](https://github.com/r-dbi/DBI). 

It would be nice to support Firebird-Databases when using the function `tbl()`.

By default this function generates a SQL-Statement of a given query  with a `LIMIT 11` clause to reduce the printed output in the console. However, this is not valid Firebird-SQL syntax and must be handled via [SELECT] `FIRST 11` [*].

Is there any chance to include this some time?

Kind regards,
Philipp

Error for a given query is below

```
library(DBI)
library(odbc)
library(dbplyr)

con_dbi <- dbConnect(odbc(), "our_database")

MY_TABLE<- tbl(con_dbi, "MY_TABLE")

print(MY_TABLE)

dbDisconnect(con_dbi)

Error in `collect()`:
! Failed to collect lazy table.
Caused by error:
11 en unknown - line 3, column 70: [Devart][ODBC][Firebird]Dynamic SQL Error
<SQL> 'SELECT *
FROM "MY_TABLE"
LIMIT 11'
```

**Comment by hadley** [comment]
Unfortunately we don't have the resources to add new backends, but we have written up the docs on how to write your own at https://dbplyr.tidyverse.org/articles/new-backend.html.
