### ISSUE TITLE
Skip MariaDB tests on old Windows 

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dbplyr#1382]
MariaDB doesn't work properly on Windows + old R. Either increase the minimal tested R version or skip tests. See https://github.com/r-dbi/RMariaDB/issues/317 for more background.

**Comment by mgirlich** [comment]
@hadley What's your opinion on this?

**Comment by hadley** [comment]
I think it's probably easiest to just bump the version of windows in the toolchain (with a comment explaining why).
