### ISSUE TITLE
Translation of as.Date in Oracle is not correct in version 2.4

### ISSUE THREAD

**Issue by apalacio9502** [tidyverse/dbplyr#1389]
Hello,

In version 2.4 the translation of as.Date is not correct, I think the error is generated by the migration to `glue_sql2` https://github.com/tidyverse/dbplyr/blob/83045c593a69c0d981bad0051cf63be24e923c49/R/backend-oracle.R#L118

In the previous version the conversion of as.Date() was `DATE '2023-01-01'` and now it is `DATE 2023-01-01`, so the problem is that the quotes are missing from the value of the date. I think it would be fixed by adding the .val in the following way: `glue_sql2(sql_current_con(), "DATE {.val x}")`

Regards,

**Comment by mgirlich** [comment]
Thanks for the detailed issue description. Now fixed in the dev version.
