### ISSUE TITLE
`db_sql_render()` doesn't pass three dots

### ISSUE THREAD

**Issue by jarodmeng** [tidyverse/dbplyr#1394]
I have a package `RPresto` that extends the `db_sql_render()` generic for Presto connections ([code link](https://github.com/prestodb/RPresto/blob/master/R/dbplyr-db.R#L180)). The extended `db_sql_render()` function has an added argument, `use_presto_cte`. The call stack goes from `dbplyr::db_sql_render()` to `RPresto::db_sql_render.PrestoConnection()`, so the passing of the `use_presto_cte` arg relies on the three dot ellipsis in `dbplyr::db_sql_render()`. However, in dbplyr 2.4.0, `db_sql_render()` doesn't pass on the ellipsis (see [code link](https://github.com/tidyverse/dbplyr/blob/main/R/db.R#L76)).

Happy to provide a quick PR to add the ellipsis passing to the function.

**Comment by hadley** [comment]
A PR would be great, thanks! (You might also want to consider using `sql_options` in your code).
