### ISSUE TITLE
ODBC complex query fails to collect() while it did in an earlier version

### ISSUE THREAD

**Issue by Mkranj** [tidyverse/dbplyr#1395]
In our app, we generate some complex queries via metaprogramming. When using a JDBC connection, the query works no problem. However, with the same app in Docker containers we have to use an ODBC connection instead. The connection itself works, we pull some data from the database. When it comes to the complex query, we get a non-informative error message:  
" Warning: Error in collect: Failed to collect lazy table.
 Caused by error:
 ! nanodbc/nanodbc.cpp:1526: 00000: [Informix][Informix ODBC Driver]General error.
   1: shiny::runApp"

I'll provide an example of the query below with fake names. Sorry for it being hard to comprehend (its difficult for us too :))
```r
inner_join(
  inner_join(
    tbl(my_odbc_connection, 'table1'),
    tbl(my_odbc_connection, 'table2')  %>%
      rename_with( ~ paste0(.,'_t2')) , 
    by = c('key1' = 'key_t2'),
    suffix = c('_left_table2', '_right_table2')
    ),
  tbl(my_odbc_connection, 'table3') %>% 
    rename_with( ~ paste0(.,'_t3')) ,
  by = c('key3' = 'key_t3'),
  suffix = c('_left_table3', '_right_table3')
  )  %>% 
collect()
```

After lots of trial and error, here's what made even this work as intended: **using dbplyr 2.1.1**.
I've heard there's been some issues with 2.4.0, but we also used 2.3.4 and 2.3.3, with the same error.
So, it seems we found our fix, hopefully this could point to specific parts that cause this issue elsewhere :)

**Comment by hadley** [comment]
Could you please provide a traceback?

**Comment by Mkranj** [comment]
I used `options(error = function() traceback(3))` before running the app. Here is what immediately appears:
```
Warning: Error in : ! in callr subprocess.
Caused by error in `collect(.)`:
! Failed to collect lazy table.
  1: runApp
Warning: Error in : ! in callr subprocess.
Caused by error in `collect(.)`:
! Failed to collect lazy table.
  1: runApp
```

Here is the traceback output:
```
11: execCallbacks(timeoutSecs, all, loop$id)
10: run_now(timeoutMs/1000, all = FALSE)
9: service(timeout)
8: serviceApp()
7: ..stacktracefloor..(serviceApp())
6: withCallingHandlers(expr, error = doCaptureStack)
5: domain$wrapSync(expr)
4: promises::with_promise_domain(createStackTracePromiseDomain(), 
       expr)
3: captureStackTraces({
       while (!.globals$stopped) {
           ..stacktracefloor..(serviceApp())
       }
   })
2: ..stacktraceoff..(captureStackTraces({
       while (!.globals$stopped) {
           ..stacktracefloor..(serviceApp())
       }
   }))
1: runApp("my_application")
```

**Comment by hadley** [comment]
Could you please run `rlang::last_trace()` to get a nice traceback?

**Comment by Mkranj** [comment]
Sure thing, here it is:
```
 <error/rlang_error>
Error in `collect()`:
! Failed to collect lazy table.
Caused by error:
! nanodbc/nanodbc.cpp:1509: [Informix][Informix ODBC Driver][Iɷ
---
Backtrace:
    ▆
 1. ├─... %>% collect()
 2. ├─dplyr::collect(.)
 3. └─dbplyr:::collect.tbl_sql(.)
 4.   └─base::tryCatch(...)
 5.     └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 6.       └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 7.         └─value[[3L]](cond)
 8.           └─cli::cli_abort("Failed to collect lazy table.", parent = cnd)
 9.             └─rlang::abort(...)
 ```

**Comment by hadley** [comment]
I think you're going to have to do a bit more reduction on your end before I can figure out what's going wrong. I'd suggest that you start by getting a reprex outside of the shiny app, and then seeing if you can remove anything from the query and still get the problem. Then use `show_query()` to generate the SQL and see if there's anything obviously wrong with it.

There's also a small chance that installing the latest version of the odbc package (1.4.0) will get you a version that gives a more informative error message, so you might try that too.

**Comment by hadley** [comment]
I'm closing this for now since I don't have a reprex that I can work with, but I'm happy to re-open and take another look if something comes to light.
