### ISSUE TITLE
2.3.4 > 2.4.0 breaks ROracle dttm column filtering

### ISSUE THREAD

**Issue by wstvcg** [tidyverse/dbplyr#1407]
It seems that the upgrade breaks the ability to filter ROracle dttm columns

i.e.  filter(DATE >= as.Date(ref_date))

works in 2.3.4 and breaks in 2.4 with th following error:

Error in `collect()` at dbplyr/R/verb-pivot-wider.R:188:3:
! Failed to collect lazy table.
Caused by error in `.oci.SendQuery()`:
! ORA-00936: missing expression

**Comment by apalacio9502** [comment]
This problem has already been solved https://github.com/tidyverse/dbplyr/issues/1389
