### ISSUE TITLE
Add a function to check if `schema` exists in a database

### ISSUE THREAD

**Issue by maciekbanas** [tidyverse/dbplyr#1414]
It would be nice to have a function checking if the `schema` exists in a database. It would be a good feature to work on schedule with databases and caching results (e.g. pulling tables if a given `schema` exists).

For the time-being I don't see any other way to check it with classic error handling which is a bit cumbersome:

```r
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")

tmp <- tempfile()
DBI::dbExecute(con, paste0("ATTACH '", tmp, "' AS aux"))

dplyr::copy_to(con, mtcars, dbplyr::in_schema("aux", "df"), temporary = FALSE)

# this one exists
dplyr::tbl(con, dbplyr::in_schema("aux", "df"))

# this does not
tryCatch({
  dplyr::tbl(con, dbplyr::in_schema("aux2", "df"))
},
error = function(e) {
  print("no schema")
})
```

**Comment by hadley** [comment]
That feels out of scope for dbplyr, sorry.  Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
