### ISSUE TITLE
Oracle `IN` clause limits

### ISSUE THREAD

**Issue by vitallish** [tidyverse/dbplyr#143]
Oracle DBs have a limit on the length of lists (such as those used with `IN` clauses) of 1000 items. See  the discussion [here](http://dbaparadise.com/2016/07/limitations-of-the-in-clause-in-oracle-ora-01795/).

Is this something that `dbplyr` would be open to addressing? If so, would one of the two methods suggested in the article above be preferable?

For example this throws an error:
```
lkp <- as.character(1:1001)
oracle_tbl %>% 
  filter(ID %in% lkp)
```

```
Error in new_result(connection@ptr, statement) : 
  nanodbc/nanodbc.cpp:1344: HY000: ORA-01795: maximum number of expressions in a list is 1000
```

While this is ok:

```
lkp <- as.character(1:1000)
oracle_tbl %>% 
  filter(ID %in% lkp)
```

**Comment by hadley** [comment]
I don't see any way to implement this; in general you're better off switching to `semi_join()` instead of using a large inline vector anyway.
