### ISSUE TITLE
bigquery integration

### ISSUE THREAD

**Issue by godislobster** [tidyverse/dbplyr#1438]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>. You can use the examples in [Reprexes for dbplyr](https://dbplyr.tidyverse.org/articles/reprex.html) as a starting point for your reprex.

Brief description of the problem

Hi! So just a quick reminder to add bigquery support into dbplyr functionality. I had been searching for a version that works with the code from the Coursera course from the University of Colorado, Clinical Data Science, which they are asking people to use 2.1.1, but I ended up using the 2.3.4 version, which worked a lot smoother.

Thanks!

```r
# insert reprex here
```

**Comment by hadley** [comment]
bigquery already has dbplyr integration?
