### ISSUE TITLE
SQLite gains support for window functions in 3.25.0

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/dbplyr#144]
According to the developers, it mimics PostgresSQL.

https://www.sqlite.org/draft/windowfunctions.html
https://www.sqlite.org/draft/releaselog/3_25_0.html

Would also need to update the vignette section, "Creating your own database", as it mentions the current lack of window function support.
https://cran.r-project.org/web/packages/dbplyr/vignettes/dbplyr.html

**Comment by RMHogervorst** [comment]
depends on https://github.com/r-dbi/RSQLite/pull/273

**Comment by krlmlr** [comment]
_RSQLite_ PR now merged, release planned end of February.
