### ISSUE TITLE
The `unknown` column appears after I join the 2 tables

### ISSUE THREAD

**Issue by joshbal** [tidyverse/dbplyr#1448]
I am using `flights` and `weather` data frames from the `nycflights13` and I store them in my SQL database (`sample_con`). 
Where does this `row_names` came from?

```r
> flights_query <- tbl(sample_con, "flights") %>%
  left_join(tbl(sample_con, "weather"))
> flights_query %>% show_query()

```

```r
<SQL>
SELECT
  `flights`.*,
  `row_names`,
  `temp`,
  `dewp`,
  `humid`,
  `wind_dir`,
  `wind_speed`,
  `wind_gust`,
  `precip`,
  `pressure`,
  `visib`
FROM `flights`
LEFT JOIN `weather`
  ON (
    `flights`.`year` = `weather`.`year` AND
    `flights`.`month` = `weather`.`month` AND
    `flights`.`day` = `weather`.`day` AND
    `flights`.`origin` = `weather`.`origin` AND
    `flights`.`hour` = `weather`.`hour` AND
    `flights`.`time_hour` = `weather`.`time_hour`
  )
```

**Comment by mgirlich** [comment]
Could you please create a reprex for this? See https://dbplyr.tidyverse.org/articles/reprex.html for more information how to do this.
And could you check whether this still happens with dbplyr 2.4.0 or even better if you check with the dev version: `devtools::install_github("tidyverse/dbplyr")`. Thanks 😄

**Comment by joshbal** [comment]
Alright.

```r
library(dplyr)
library(dbplyr)

flights <- memdb_frame(nycflights13::flights)
weather <- memdb_frame(nycflights13::weather)

   
``` 

After I uninstall `dbplyr` and reinstall it via `devtools::install_github("tidyverse/dbplyr")`:

```r
flights_query <- flights %>%
    left_join(weather)
flights_query %>% show_query()
``` 

Output:

```r
<SQL>
SELECT
  `dbplyr_Lmbxh8Cu35`.*,
  `temp`,
  `dewp`,
  `humid`,
  `wind_dir`,
  `wind_speed`,
  `wind_gust`,
  `precip`,
  `pressure`,
  `visib`
FROM `dbplyr_Lmbxh8Cu35`
LEFT JOIN `dbplyr_ABTvOZhnAc`
  ON (
    `dbplyr_Lmbxh8Cu35`.`year` = `dbplyr_ABTvOZhnAc`.`year` AND
    `dbplyr_Lmbxh8Cu35`.`month` = `dbplyr_ABTvOZhnAc`.`month` AND
    `dbplyr_Lmbxh8Cu35`.`day` = `dbplyr_ABTvOZhnAc`.`day` AND
    `dbplyr_Lmbxh8Cu35`.`origin` = `dbplyr_ABTvOZhnAc`.`origin` AND
    `dbplyr_Lmbxh8Cu35`.`hour` = `dbplyr_ABTvOZhnAc`.`hour` AND
    `dbplyr_Lmbxh8Cu35`.`time_hour` = `dbplyr_ABTvOZhnAc`.`time_hour`
  )
```

**Comment by mgirlich** [comment]
As you can see there is no `row_names` column.
The second part is not a reprex as an important part is missing: how was the data written to the database. I am pretty sure you unintentionally created a `row_names` column when writing the data to the database. You could check that e.g. with `DBI::dbListFields(sample_con, "weather")`.

**Comment by joshbal** [comment]
Yeah, I see it now. After I copy the `weather` dataset from `nycflights13` to my SQL database connection, the `row_names` column was spontaneously created. So I thought it might be bug
