### ISSUE TITLE
Compute does not work with teradata

### ISSUE THREAD

**Issue by kmace** [tidyverse/dbplyr#147]
calling `compute` on a teradata connection does not work and throws the following error:

```
Error in new_result(connection@ptr, statement) : 
  nanodbc/nanodbc.cpp:1344: 42000: [Teradata][ODBC Teradata Driver][Teradata Database](-3707)Syntax error, expected something like a 'METHOD' keyword between the 'CREATE' keyword and the 'TEMPORARY' keyword. 
```

I think you need to use the keyword `VOLATILE ` instead of `TEMPORARY` for Teradata right?

**Comment by edgararuiz** [comment]
Hi, are you using the `odbc` package? We depend on it to account for Teradata's expected syntax: https://github.com/r-dbi/odbc/blob/b4c6c3f05236bc5c721a664451dd10026c988387/R/db.R#L30-L33
