### ISSUE TITLE
DBI::dbExecute (TD implementaion?) will replace linebreak \n with carriage return \r of the statement

### ISSUE THREAD

**Issue by happyshows** [tidyverse/dbplyr#152]
Hi,

When I'm using DBI::dbExecute(con, statement) to send create view /create table statement to Teradata, and then do a show view query to pull the statement. The text consistently got messed up by missing the \n. I have tested using other IDE to send identical .sql file to database and the \n was kept fine.

```
DBI        * 1.0.0      2018-05-02 cran (@1.0.0)                          
dbplyr       1.2.1      2018-02-19 cran (@1.2.1) 
 Teradata Version: 15.10.0711  15.10.07.11B
```

**Comment by hadley** [comment]
This doesn't seem to be related to dbplyr.
