### ISSUE TITLE
check_na_rm() should warn with untranslated function names

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/dbplyr#153]
`check_na_rm()` warns like this, but apparently we cannot use `AVG(x, na.rm = TRUE)`; I believe it should be `mean(x, na.rm = TRUE)`.

But, I don't know how to pass the original name to `check_na_rm()`...

``` r
library(dplyr, warn.conflicts = FALSE)
library(dbplyr, warn.conflicts = FALSE)

result <- memdb_frame(x = 1) %>% 
  summarise(x = mean(x)) %>%
  collect()
#> Warning: Missing values are always removed in SQL.
#> Use `AVG(x, na.rm = TRUE)` to silence this warning
```

Created on 2018-09-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by hadley** [comment]
This requires an additional argument to `check_na_rm()`
