### ISSUE TITLE
distinct ignores rhs when there is a lhs (renaming result columns)

### ISSUE THREAD

**Issue by sverchkov** [tidyverse/dbplyr#154]
``` r
library( dplyr, warn.conflicts = F )

df_tib <- tibble( a=c(1,1,2,2), b=c(1,2,1,2) )
df_sql <- dbplyr::memdb_frame( a=c(1,1,2,2), b=c(1,2,1,2) )

df_tib %>% distinct( x = a )
#> # A tibble: 2 x 1
#>       x
#>   <dbl>
#> 1     1
#> 2     2

res <- df_sql %>% distinct( x = a )
res %>% show_query()
#> <SQL>
#> SELECT `x`
#> FROM `bigofxlnjv`
#> GROUP BY `x`
res
#> Error in result_create(conn@ptr, statement): no such column: x
```

Created on 2018-09-06 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

I think the correct translation is `SELECT DISTINCT "a" AS "x"`.

**Comment by edgararuiz** [comment]
Hi @sverchkov , what is the difference between this issue and #161?

**Comment by sverchkov** [comment]
No difference.

**Comment by hadley** [comment]
Needs `dplyr:::distinct_vars()` to be exported first

**Comment by hadley** [comment]
Now called `distinct_prepare()`. Will need bump to dplyr 0.8.0.

**Comment by hadley** [comment]
Nope, not worth it — `distinct_prepare()` assumes too much about the data frame, and it'll be easiest to reimplement in dbplyr.

**Comment by hadley** [comment]
The fix is suspiciously simple, but seems to work 😄
