### ISSUE TITLE
dbplyr.tidyverse.org outdated

### ISSUE THREAD

**Issue by dpprdan** [tidyverse/dbplyr#163]
The information on [dbplyr.tidyverse.org](https://dbplyr.tidyverse.org/index.html) is not up-to-date (and inconsistent). 

E.g. according to the CRAN badge on the homepage, the current version is 0.7.6 (which is the current dplyr version) while it is 1.2.2 at the time of writing. The [Reference](https://dbplyr.tidyverse.org/reference/index.html) page says "version 0.0.0.9001" and on the [News](https://dbplyr.tidyverse.org/news/index.html) page it says that the latest version is "dbplyr 0.5.0.9000".

**Comment by dpprdan** [comment]
FWIW, v1.2.2 has not been tagged on GH, and according to the DESCRIPTION in the master branch the version is still 1.2.1.9001.

**Comment by batpigandme** [comment]
@dpprdan thanks, working on a site rebuild (and streamlining this process generally, since I can definitely see how it's confusing). 

Because 1.2.2 is already on CRAN, the bug report update will have to be part of the next development cycle once we bump versions to get things up to date.
