### ISSUE TITLE
str_detect always treats pattern as fixed string

### ISSUE THREAD

**Issue by dlindelof** [tidyverse/dbplyr#168]
When `str_detect` is used in a call to `filter` on a `tbl`, I expect `pattern` to be treated as a regular expression. Instead, it seems that it is treated as a fixed pattern:

```
> MASTER %>% filter(str_detect(FOO, "pen$")) %>% show_query
<SQL>
SELECT *
FROM "MASTER"
WHERE (INSTR("FOO", 'pen$') > 0)
```

The SQL `INSTR` function performs a case-insensitive search, and does not treat its second argument as a regex.

**Comment by colearendt** [comment]
What database are you using here?

**Comment by kmace** [comment]
I have this issue too. I am using teradata.

**Comment by PNorvaisas** [comment]
I have the same problem with MySQL database. Need to collect data to be able to use patterns in str_detect.

**Comment by yutannihilation** [comment]
`str_detect()` can be translated as `INSTR()`, `CHARINDEX()`, or `CHARINDEX()`, but neither of them is a regex function.

https://github.com/tidyverse/dbplyr/blob/79d2a0377561ad57f67a65b914ce3195d10de0be/R/db-postgres.r#L68-L70

https://github.com/tidyverse/dbplyr/blob/79d2a0377561ad57f67a65b914ce3195d10de0be/R/db-odbc-mssql.R#L93-L96

According to https://github.com/tidyverse/dbplyr/issues/151#issuecomment-418660979, this seems a design decision.

> There's unfortunately no way that dbplyr can translate every stringr feature into every database backend.

You can directly specify a function particular to the backend, though. For example (this is only for illustration purpose and the SQLs are invalid for SQLite):

``` r
library(DBI)
library(dplyr, warn.conflicts = FALSE)
library(dbplyr, warn.conflicts = FALSE)

con <- dbConnect(RSQLite::SQLite(), ":memory:")
copy_to(con, iris)

# MySQL has REGEXP
tbl(con, "iris") %>%
  filter(FOO %regexp% "pen$") %>%
  show_query
#> <SQL>
#> SELECT *
#> FROM `iris`
#> WHERE (`FOO` REGEXP 'pen$')

# Teradata has REGEXP_LIKE
tbl(con, "iris") %>%
  filter(regexp_like(FOO, "pen$")) %>%
  show_query
#> <SQL>
#> SELECT *
#> FROM `iris`
#> WHERE (REGEXP_LIKE(`FOO`, 'pen$'))
```

<sup>Created on 2018-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yutannihilation** [comment]
@kmace 
BTW, for https://github.com/tidyverse/stringr/issues/262, you might feel you were using regex, but it was, sadly, just a bug (c.f. https://github.com/tidyverse/dbplyr/pull/81)... The dev version of dbplyr will give you 0 rows with the very same code.

**Comment by kmace** [comment]
@yutannihilation
Oh wow. Thanks for that heads up.

**Comment by hadley** [comment]
@colearendt do you want to take this one on too?
