### ISSUE TITLE
Oracle translation fails on "identifier too long"

### ISSUE THREAD

**Issue by colearendt** [tidyverse/dbplyr#172]
Apparently Oracle has an identifier length limit of 30 characters, which causes problems for generated SQL names that are inherently long (i.e. those generated from a `summarize` statement).

Should we take this into account and truncate names / have an option for doing so? Or is this something that documentation / a better error message would help with?

``` r
library(odbc)
library(DBI)
library(config)
library(dplyr)

cfg <- config::get(file = "/wrk/db-test-config.yml")
con <- do.call(dbConnect, cfg$oracle)
mytbl <- copy_to(con, iris, "somename")

mytbl %>% summarize(test=sum(Petal.Length + Petal.Width, na.rm=TRUE))
#> # Source:   lazy query [?? x 1]
#> # Database: Oracle 12.01.0020[system@xe/]
#>    test
#>   <dbl>
#> 1  744.

mytbl %>% summarize(sum(Petal.Length + Petal.Width, na.rm=TRUE))
#> Error in new_result(connection@ptr, statement): nanodbc/nanodbc.cpp:1344: HY000: ORA-00972: identifier is too long
#> 
```

<sup>Created on 2018-10-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
I don't see any easy way to fix this — I don't think we want to truncate by default, and adding a custom error message is going to be a lot of work. I think the best we can do is provide help for debugging generate SQL statements (i.e. #196).
