### ISSUE TITLE
dbplyr::spread() on tbl_sql

### ISSUE THREAD

**Issue by jinaliu** [tidyverse/dbplyr#173]
This is a specific issue of the following dev version of dbplyr:

devtools::install_github("tidyverse/dbplyr", ref = devtools::github_pull(72)) developed by @edgararuiz 

It seems to me that the spread function doesn't work properly...

```
df_sample <- tribble(~group1, ~group2, ~group3, ~identifier, ~value, 
                      8, 24, 6, 'mt_0', 
                      12, 18, 24, 6, 'mt_1', 4)
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
df_db <- copy_to(con, df_sample, 'df_sample')
```

I obtained an incorrect result with the following command. There should've been only one row of data after spread.

`df_db %>% spread(identifier, value)`
![snap_incorrect](https://user-images.githubusercontent.com/44044954/46776565-0afe6a00-ccc1-11e8-98d8-cb1f76fec623.png)

The result is correct if the original data is downloaded to local memory.
`df_db %>% collect() %>% spread(identifier, value)`

![snap29_correct](https://user-images.githubusercontent.com/44044954/46776594-1f426700-ccc1-11e8-850e-93e4eeb91eb2.png)

**Comment by hadley** [comment]
`spread()` does not work on remote databse tables.

**Comment by jcfisher** [comment]
I know this is closed, but would it be possible to implement `spread` and `gather` using [`PIVOT` and `UNPIVOT`](https://docs.microsoft.com/en-us/sql/t-sql/queries/from-using-pivot-and-unpivot?view=sql-server-2017)?  A rough example follows:

```
library(tidyverse)
library(dbplyr)
con <- DBI::dbConnect(
  odbc::odbc(),
  driver = "{SQL Server}",
  database = "AdventureWorks2012",
  uid = "sqlfamily",
  pwd = "sqlf@m1ly",
  server = "mhknbn2kdz.database.windows.net",
  port = 1433
)

# In R:
work_orders _long<- con %>% 
  tbl(in_schema("Production", "WorkOrder")) %>% 
  select(WorkOrderID, StartDate, EndDate) %>%
  tbl_df %>% 
  gather(key = "mykey", value = "myvalue", -WorkOrderID)

# In SQL:
sel <- 'SELECT WorkOrderID, mykey, myvalue 
        FROM 
          (SELECT WorkOrderID, StartDate, EndDate FROM Production.WorkOrder) p 
        UNPIVOT 
          (myvalue FOR mykey IN (StartDate, EndDate)) AS unpvt'

tbl(con, sql(sel))
```
