### ISSUE TITLE
SQL database specification

### ISSUE THREAD

**Issue by TomWeishaar** [tidyverse/dbplyr#176]
In SQL, you can specify both a database and a table at the same time with syntax like `database`.`table`. 

With RMariaDB, if not others, you can create connections that will access any database on the server you're connected to by not including a dbname parameter or using dbname = "".

But I can't find any examples of using dbplyr that specify both the database and the table. All the examples set the database when creating the connection rather than in the `tbl()` call. I've played around with some guesses at what the syntax would be but without any luck.

Please tell me there's a way to do this with an example of how to specify both the database and table to dbplyr. If there's no syntax for this, then this would be a feature request.

Thanks.

Tom

**Comment by edgararuiz** [comment]
Hi! Maybe this article can help: http://db.rstudio.com/best-practices/schema.  The idea is to try out `in_schema()`

**Comment by TomWeishaar** [comment]
Yes, Edgar - exactly what I was looking for. Thank you very much.

Tom
