### ISSUE TITLE
Cannot cast to date in PostgreSQL

### ISSUE THREAD

**Issue by lincis** [tidyverse/dbplyr#177]
Consider the following table:
```sql
CREATE table my_table(
  id int,
  created timestamp default now()
  )
  ;

INSERT INTO my_table (id) values(1);
INSERT INTO my_table (id) values(2);
INSERT INTO my_table (id) values(3);
INSERT INTO my_table (id) values(4);
```
And R code
```r
my_db = dplyr::tbl(con, "my_table")
my_data_stmt = my_db %>%
  mutate(created = as.Date(created)
```

The resulting query part for type casting is like `AS.DATE(created)` while I would expect `created::DATE`.
On the same note postgres `CURRENT_DATE` is not treated correctly.

I am using version from github master.

**Comment by karldw** [comment]
One workaround is to `CAST` the column:

```r
date_psql_type <- rlang::sym("date")

my_db = dplyr::tbl(con, "my_table")
my_data_stmt = my_db %>%
  mutate(created = CAST(created %as% date_psql_type))
```

**Comment by hadley** [comment]
@colearendt this is for you too 😄

**Comment by hadley** [comment]
Already fixed:

``` r
library(dbplyr)
translate_sql(as.Date(x), con = simulate_postgres())
#> <SQL> CAST(`x` AS DATE)
```

<sup>Created on 2019-03-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
