### ISSUE TITLE
SQL translation turns aggregation into window function

### ISSUE THREAD

**Issue by javierluraschi** [tidyverse/dbplyr#178]
`dbplyr` is adding an unnecessary `OVER ()` hint with a repro similar to:

```r
library(sparklyr)
sc <- spark_connect(master = "local")
sdf_len(sc, 10) %>%
    dplyr::mutate(average = mean(id)) %>%
    dplyr::show_query()
```
```sql
<SQL>
SELECT `id`, avg(`id`) OVER () AS `average`
FROM `sparklyr_tmp_afe063482375`
```

Which causes performance degradation in Spark cluster, see: https://github.com/rstudio/sparklyr/issues/1738

However, this behavior has been around since 2017, probably even earlier, so not a regression at all.

**Comment by hadley** [comment]
This is deliberate behaviour — asking clarifying questions on original issue.
