### ISSUE TITLE
Cleaning up tables created by join(..., copy=TRUE)

### ISSUE THREAD

**Issue by cboettig** [tidyverse/dbplyr#188]
When using `dplyr` with an external database, performing joins with `copy=TRUE` results in a table being created in my database with a randomly assigned name.  I realize that do to lazy evaluation, this table cannot just be deleted once the call completes, or even after we first call `collect()`.  Still, it would be nice to have some ability / helper function to clean up these auto-created tables, otherwise running an analysis with `copy=TRUE` can create a very large number of table copies.  

Reproducible example:

```r
library(nycflights13)
library(MonetDBLite)
library(dplyr)

db <- DBI::dbConnect(MonetDBLite::MonetDBLite(), "test")

DBI::dbWriteTable(db, "flights", flights)
DBI::dbListTables(db)
x <- semi_join(tbl(db, "flights"), airlines, copy = TRUE)

## Look, now we have a randomly generated table name, ick:
DBI::dbListTables(db)

```

### Context

So why am I calling this potentially expensive operation so many times to begin with? In my use case, the table already in the database, table `x`, is quite large (i.e. too big for available RAM), and I wish to perform a filtering join.  Table `y` is not tiny but easily fits in memory.  Using MonetDBLite, a filtering join, even with copying in table `y`, runs about **200x faster** than a call to `filter`.  This filtering join is part of a function in package (for taxonomic name look-ups) that could be run many times, and I don't want to pollute the user's workspace with lots of copies of temporary tables.   I'm not sure what the best way to clean up said tables would be (e.g. the random names created do not look easy to distinguish from potentially real tables using simple regex patterns).  

Or maybe I'm going about this all wrong and I should really be avoiding `copy` whenever possible, but in this context performance seems to favor it.  Any suggestions?  I think a clean-up function or at least a way to set the name of the copied table before it is created would be great.  Apologies if I've overlooked a way in which that can already be done.

**Comment by hadley** [comment]
I think this would be an easy fix for someone - it just requires modifying `random_table_name()` to add a `dbplyr_` prefix (although you'll need to double check that `_` is the right separator)

**Comment by mattle24** [comment]
Hi, I'd love to work on this as a first-time contributor.

**Comment by mattle24** [comment]
@hadley great, that should make this easier. I'm having some trouble finding the standard prefix though. I tried the same code as @cboettig using SQLite instead of MonetDBLite (reprex below), but I did not see a prefix. I traced the chain of functions set off by this `semi_join()` to `auto_copy.tbl_sql()`, which calls `random_table_name()` to create the temporary table names. The names generated by `random_table_name()` are eventually used by `db_copy_to.DBIConnection()` to write tables. I didn't see a preexisting way to create prefixes in this process. Where did you see the standard prefix?

``` r
set.seed(0108)
library(nycflights13)
#> Warning: package 'nycflights13' was built under R version 3.5.2
library(RSQLite)
#> Warning: package 'RSQLite' was built under R version 3.5.1
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
db <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")

DBI::dbWriteTable(db, "flights", flights, overwrite = TRUE)
DBI::dbListTables(db)
#> [1] "flights"
x <- semi_join(tbl(db, "flights"), airlines, copy = TRUE, prefix = "pre_")
#> Joining, by = "carrier"

# Now we have the original tbl, the semi_join tbl, and two SQLite stats tbls
DBI::dbListTables(db)
#> [1] "flights"      "lkjrmangnm"   "sqlite_stat1" "sqlite_stat4"
DBI::dbDisconnect(db)
```

<sup>Created on 2019-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment]
Argh, now I don't know where I saw that. Sorry for the confusion!

**Comment by mattle24** [comment]
No worries!
