### ISSUE TITLE
sqlite runtime error when testing dplyr 0.8.0 RC on rhub

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dbplyr#189]
Testing dplyr release candidate on rhub with ASAN/UBSAN gives this error: 

```
vendor/sqlite3/sqlite3.c:61270:14: runtime error: member access within misaligned address 0x7ff692d82f4e for type 'struct BtCursor', which requires 8 byte alignment
0x7ff692d82f4e: note: pointer points here
 62 65 27 00 01 00  01 00 00 00 00 00 0d 00  27 6c 6f 6e 67 20 69 6e  74 27 00 00 00 00 0a 00  27 75
             ^
```

The Debian Linux, R-devel, GCC ASAN/UBSAN rhub says ERROR
https://builder.r-hub.io/status/dplyr_0.7.99.9000.tar.gz-d3b96eac4a25411b88544c378b08f935

originally in https://github.com/tidyverse/dplyr/issues/3931#issuecomment-448607933
I'm not sure what to do with this, but one of you might

**Comment by hadley** [comment]
I don't think we can do anything about this since it's upstream code (and CRAN seems to understand that)
