### ISSUE TITLE
MySQL / MariaDB window function support

### ISSUE THREAD

**Issue by andypohl** [tidyverse/dbplyr#191]
I'm running into the same problem [this person ran into and reported on the RMariaDB repository](https://github.com/r-dbi/RMariaDB/issues/89).

Before you ask me to go to the RStudio community site and whine there, [I'll just mention I did that](https://community.rstudio.com/t/why-no-dbplyr-support-for-mysql-mariadb-windowing-functions/20338), and I've been politely encouraged by an authority there to post an issue here.

That post has my non-reprex example illustrating my confirmation of the conclusion by @krlmlr that it's dbplyr that's missing the necessary piece of the puzzle.  It's certainly a similar issue to #144 but in this case, I think the DBI part is working.  But anyhow since that issue hasn't been closed, I thought maybe there's perhaps interest in adding window function querying functionality to MariaDB/MySQL too.

**Comment by hadley** [comment]
Can you please provide a pointer to the documentation for window functions in MariaDB?

**Comment by andypohl** [comment]
Hi, thanks for responding.  I think [here](
https://mariadb.com/kb/en/library/window-functions/).

**Comment by hadley** [comment]
<https://mariadb.com/kb/en/library/window-functions/>
