### ISSUE TITLE
Update documentation re. database window-function support

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/dbplyr#209]
In #191 and #144 we have requests for window-function support for MariaDB and SQLite window functions. Part of #191's original [complaint on community](https://community.rstudio.com/t/why-no-dbplyr-support-for-mysql-mariadb-windowing-functions/20338) was:
> MySQL/MariaDB's support for window functions is [inaccurately mentioned in the documentation](https://db.rstudio.com/dplyr/#mysqlmariadb)

So, perhaps we should update the documentation in the meantime.

**Comment by badjouras** [comment]
I'm completely new to this repository, so I'm not sure if commenting here is the right way to go about this, but I would just like to mention that the issue persists. I'm new to window functions and the only way I found out that MariaDB actually supports window functions and that dbplyr already supports that feature was by doing a Google search for _dplyr mariadb window functions_, coming across the [original complaint on community](https://community.rstudio.com/t/why-no-dbplyr-support-for-mysql-mariadb-windowing-functions/20338), then [#191](https://github.com/tidyverse/dbplyr/issues/191) and finding out it was resolved. Given that it's been resolved for over a year, I highly suggest updating the documentation.
