### ISSUE TITLE
Fix na_if Translation for Oracle

### ISSUE THREAD

**Issue by carvalhomb** [tidyverse/dbplyr#211]
Translate na_if to NULLIF rather than NULL_IF when using an Oracle connection.

Reference: https://docs.oracle.com/en/database/oracle/oracle-database/18/sqlrf/NULLIF.html

(Related to #32)

**Comment by hadley** [comment]
I think it actually should be `NULLIF` everywhere:

* Oracle:  https://docs.oracle.com/en/database/oracle/oracle-database/18/sqlrf/NULLIF.html
* MySQL:  https://dev.mysql.com/doc/refman/8.0/en/control-flow-functions.html#function_nullif
* SQLite: https://www.sqlite.org/lang_corefunc.html#nullif
* Postgres: https://www.postgresql.org/docs/8.4/functions-conditional.html
