### ISSUE TITLE
Backend: Sybase

### ISSUE THREAD

**Issue by imanuelcostigan** [tidyverse/dbplyr#215]
Is there any appetite to develop a Sybase backend? How easy / hard would it be to provision a Sybase test environment?

**Comment by hadley** [comment]
I'd be happy to review a PR.  

I'm in the process of a bunch of refactoring (code and test) that should make a test environment much less important by relying on regression tests of SQL output. rstudio::conf will take up the rest of the week, and but I should be able to finish it off the week of Jan 21.

**Comment by imanuelcostigan** [comment]
I’ll come back to this ticket at that point.

**Comment by hadley** [comment]
I've completed the major reshuffling if you want to come back to it.

**Comment by hadley** [comment]
I'll be working on dbplyr for the next 2-3 weeks, so should be able to give rapid feedback on PRs.

**Comment by hadley** [comment]
Closing this because we've made no progress in well over a year.
