### ISSUE TITLE
mssql and nvarchar(max) selection order

### ISSUE THREAD

**Issue by r2evans** [tidyverse/dbplyr#219]
Big picture: from Windows, the ODBC for SQL Server is sensitive to the selected order of "long data" (poorly quantified) columns. (The [best documentation](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/getting-long-data?view=sql-server-2017) I've found suggests that it *might* be greater than 255 bytes.)

Reproducible, using docker on windows with [microsoft/mssql-server-linux](https://hub.docker.com/r/microsoft/mssql-server-linux/) (and postgres for comparison).

<details><summary>(create/populate a test table)</summary>

```r
library(DBI)
library(dplyr)
library(dbplyr)

conss <- DBI::dbConnect(odbc::odbc(), driver="ODBC Driver 17 for SQL Server", ...)
conpg <- DBI::dbConnect(odbc::odbc(), driver="PostgreSQL ANSI(x64)", ...)

DBI::dbExecute(conpg, "drop table if exists quux")
DBI::dbExecute(conss, "drop table if exists quux")

DBI::dbExecute(conpg, "
  CREATE TABLE quux (
    id              UUID DEFAULT uuid_generate_v1mc() PRIMARY KEY NOT NULL ,
    someint         INT4 NOT NULL ,
    notes           TEXT NULL ,
    createddatetime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP )")
DBI::dbExecute(conss, "
  CREATE TABLE quux (
    id              UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY NOT NULL ,
    someint         INT NOT NULL ,
    notes           NVARCHAR(MAX) NULL ,
    createddatetime DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET() )")

DBI::dbWriteTable(conss, "quux", data.frame(someint=1L), append=TRUE)
DBI::dbWriteTable(conpg, "quux", data.frame(someint=1L), append=TRUE)
```

</details>

The underlying problem is not unique to `dbplyr` or even `odbc`, the problem is ODBC.

```r
### (with connections: conss, conpg)
DBI::dbGetQuery(conpg, "select * from quux")
#                                     id someint notes     createddatetime
# 1 7767DDF6-19A7-11E9-ABD7-138C23179576       1  <NA> 2019-01-16 15:57:46
DBI::dbGetQuery(conss, "select * from quux")
# Error in result_fetch(res@ptr, n, ...) : 
#   nanodbc/nanodbc.cpp:2894: 07009: [Microsoft][ODBC Driver 17 for SQL Server]Invalid Descriptor Index 
# Warning in dbClearResult(rs) : Result already cleared
```

The workaround (after reopening the connection, since `conss` is now trashed):

```r
# postgres works unabated
tbl(conpg, "quux")

# avoid the "longish" fields
tbl(conss, "quux") %>% select(-notes)
# reorder the "longish" fields
tbl(conss, "quux") %>% select(-notes, everything(), notes)
```

This feels a little hacky, but I think it starts to break down when you don't know a priori what constitutes "longish", though after several attempts, one can break down and ask for the original schema to determine what is what; and it starts getting cumbersome when the number of misplaced "longish" fields increases.

With single tables, one easy-enough workaround might be to define a view that reorders the columns. Unfortunately, with joins the order of columns is no longer as-desired.

I know that this is ultimately a problem with the ODBC driver, not the `odbc` package or anything in R, as it affects other languages too.

**My question is this**: is there a better way to deal with this than the `select(-..., everything(), ...)` pattern? It doesn't need to be solved with `dbplyr` functions, but as it is particular to DBMS access, it might do well (in function or at least documentation) within `dbplyr`.

<details><summary>Session info</summary>

```r
Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 system   x86_64, mingw32             
 ui       RTerm                       
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2019-01-16                  

Packages ----------------------------------------------------------------------
 package        * version     date       source                           
 acepack          1.4.1       2016-10-29 CRAN (R 3.5.1)                   
 assertthat       0.2.0       2017-04-11 CRAN (R 3.5.1)                   
 backports        1.1.2       2017-12-13 CRAN (R 3.5.0)                   
 base           * 3.5.1       2018-07-02 local                            
 base64enc        0.1-3       2015-07-28 CRAN (R 3.5.0)                   
 bit              1.1-14      2018-05-29 CRAN (R 3.5.0)                   
 bit64            0.9-7       2017-05-08 CRAN (R 3.5.0)                   
 blob             1.1.1       2018-03-25 CRAN (R 3.5.1)                   
 checkmate        1.8.5       2017-10-24 CRAN (R 3.5.1)                   
 cli              1.0.1       2018-09-25 CRAN (R 3.5.1)                   
 cluster          2.0.7-1     2018-04-13 CRAN (R 3.5.1)                   
 colorspace       1.3-2       2016-12-14 CRAN (R 3.5.1)                   
 commonmark       1.5         2018-04-28 CRAN (R 3.5.1)                   
 compiler         3.5.1       2018-07-02 local                            
 config           0.3         2018-03-27 CRAN (R 3.5.1)                   
 crayon           1.3.4       2017-09-16 CRAN (R 3.5.1)                   
 data.table     * 1.11.8      2018-09-30 CRAN (R 3.5.1)                   
 datasets       * 3.5.1       2018-07-02 local                            
 DBI            * 1.0.0       2018-05-02 CRAN (R 3.5.1)                   
 dbplyr         * 1.3.0       2019-01-09 CRAN (R 3.5.2)                   
 devtools         1.13.6      2018-06-27 CRAN (R 3.5.1)                   
 digest           0.6.15      2018-01-28 CRAN (R 3.5.1)                   
 dplyr          * 0.7.99.9000 2018-11-12 Github (tidyverse/dplyr@e177d27) 
 evaluate         0.11        2018-07-17 CRAN (R 3.5.1)                   
 fansi            0.4.0       2018-11-12 Github (brodieG/fansi@ab11e9c)   
 foreign          0.8-70      2017-11-28 CRAN (R 3.5.1)                   
 formatR          1.5         2017-04-25 CRAN (R 3.5.1)                   
 Formula          1.2-3       2018-05-03 CRAN (R 3.5.0)                   
 futile.logger    1.4.3       2016-07-10 CRAN (R 3.5.1)                   
 futile.options   1.0.1       2018-04-20 CRAN (R 3.5.0)                   
 ggplot2        * 3.0.0       2018-07-03 CRAN (R 3.5.1)                   
 glue             1.3.0       2018-07-17 CRAN (R 3.5.1)                   
 graphics       * 3.5.1       2018-07-02 local                            
 grDevices      * 3.5.1       2018-07-02 local                            
 grid             3.5.1       2018-07-02 local                            
 gridExtra        2.3         2017-09-09 CRAN (R 3.5.1)                   
 gtable           0.2.0       2016-02-26 CRAN (R 3.5.1)                   
 Hmisc            4.1-1       2018-01-03 CRAN (R 3.5.1)                   
 hms              0.4.2       2018-03-10 CRAN (R 3.5.1)                   
 htmlTable        1.12        2018-05-26 CRAN (R 3.5.1)                   
 htmltools        0.3.6       2017-04-28 CRAN (R 3.5.1)                   
 htmlwidgets      1.2         2018-04-19 CRAN (R 3.5.1)                   
 jsonlite         1.5         2017-06-01 CRAN (R 3.5.1)                   
 knitr            1.20        2018-02-20 CRAN (R 3.5.1)                   
 lambda.r         1.2.3       2018-05-17 CRAN (R 3.5.1)                   
 lattice          0.20-35     2017-03-25 CRAN (R 3.5.1)                   
 latticeExtra     0.6-28      2016-02-09 CRAN (R 3.5.1)                   
 lazyeval         0.2.1       2017-10-29 CRAN (R 3.5.1)                   
 magrittr         1.5         2014-11-22 CRAN (R 3.5.1)                   
 Matrix           1.2-14      2018-04-13 CRAN (R 3.5.1)                   
 memoise          1.1.0       2017-04-21 CRAN (R 3.5.1)                   
 methods        * 3.5.1       2018-07-02 local                            
 munsell          0.5.0       2018-06-12 CRAN (R 3.5.1)                   
 nnet             7.3-12      2016-02-02 CRAN (R 3.5.1)                   
 odbc             1.1.6       2018-11-13 Github (r-dbi/odbc@2d9875d)      
 pillar           1.3.1.9000  2018-12-21 Github (r-lib/pillar@9cc3030)    
 pkgconfig        2.0.2       2018-08-16 CRAN (R 3.5.1)                   
 plyr             1.8.4       2016-06-08 CRAN (R 3.5.1)                   
 purrr          * 0.2.5       2018-05-29 CRAN (R 3.5.1)                   
 R6               2.3.0       2018-10-04 CRAN (R 3.5.1)                   
 RColorBrewer     1.1-2       2014-12-07 CRAN (R 3.5.0)                   
 Rcpp             1.0.0       2018-11-07 CRAN (R 3.5.1)                   
 readr            1.1.1       2017-05-16 CRAN (R 3.5.1)                   
 rgeos            0.3-28      2018-06-08 CRAN (R 3.5.1)                   
 rlang            0.3.0.1     2018-10-25 CRAN (R 3.5.1)                   
 rmarkdown        1.10        2018-06-11 CRAN (R 3.5.1)                   
 roxygen2         6.1.0       2018-07-27 CRAN (R 3.5.1)                   
 rpart            4.1-13      2018-02-23 CRAN (R 3.5.1)                   
 rprojroot        1.3-2       2018-01-03 CRAN (R 3.5.1)                   
 rredis           1.7.0       2015-07-05 CRAN (R 3.5.1)                   
 rstudioapi       0.7         2017-09-07 CRAN (R 3.5.1)                   
 scales           1.0.0       2018-08-09 CRAN (R 3.5.1)                   
 sp               1.3-1       2018-06-05 CRAN (R 3.5.1)                   
 splines          3.5.1       2018-07-02 local                            
 stats          * 3.5.1       2018-07-02 local                            
 stringi          1.2.4       2018-07-20 CRAN (R 3.5.1)                   
 stringr          1.3.1       2018-05-10 CRAN (R 3.5.1)                   
 survival         2.42-3      2018-04-16 CRAN (R 3.5.1)                   
 testthat         2.0.0       2017-12-13 CRAN (R 3.5.1)                   
 tibble         * 1.4.99.9006 2018-12-21 Github (tidyverse/tibble@85823b7)
 tidyr          * 0.8.1       2018-05-18 CRAN (R 3.5.1)                   
 tidyselect       0.2.5       2018-10-11 CRAN (R 3.5.1)                   
 tools            3.5.1       2018-07-02 local                            
 utf8             1.1.4       2018-05-24 CRAN (R 3.5.1)                   
 utils          * 3.5.1       2018-07-02 local                            
 withr            2.1.2       2018-03-15 CRAN (R 3.5.1)                   
 xml2             1.2.0       2018-01-24 CRAN (R 3.5.1)                   
 yaml             2.2.0       2018-07-25 CRAN (R 3.5.1)                   
 zoo              1.8-3       2018-07-16 CRAN (R 3.5.1)                   
```

</details>

**Comment by r2evans** [comment]
Clarification: I listed `nvarchar(max)`, but it is the same for `varbinary` and related.

A slight reduction of the `select(-..., everything(), ...)` model would be to use an example from the RStudio::Conf BigData workshop, `06-advanced-operations.Rmd` example:

```r
select_end <- function(.data, ...){
  vars <- enquos(...)
  neg_vars <- map(vars, ~ expr(- !! .x))
  select(
    .data,
    !!! neg_vars,
    everything(),
    !!! vars
  )
}
tbl(conss, "quux") %>% select_end(notes) # works
```

(I'd still like to know if there's a way to automate knowing which fields are which.)

**Comment by hadley** [comment]
I think this really needs to be fixed upstream of dbplyr

**Comment by r2evans** [comment]
I understand your logic, Hadley, and in theory I agree. But it has been known for 10 years or so and the authors of the ODBC driver (I'm told originally Simba, though *their* current download is a 20-day trial) have shown no apparent intent to remedy it. It is a well known thing and documented as if this were an additive feature. There is very little if any leverage over Microsoft on this.

Please reconsider.

**Comment by hadley** [comment]
Basically, what you are asking me to do is invest my time to fix a MS driver problem. SQL server is a billion dollar business and I really think the onus is on them to fix it, rather than me. That said, I had thought we (RStudio) had discussions with simba about this, and a fix was in flight. @jimhester will know more.

**Comment by r2evans** [comment]
I understand your perspective, but that's not what I had in mind. The "ideal" is obviously to fix the ODBC driver, which is outside R's realm. Fix `nanodbc`, but those authors have said they will not pursue a fix (since it is in the underlying driver). No, I don't think and do not mean to suggest that it is your job to "fix" this. In fact, I don't see this as a "bug", any more than I see problems with forward/back-slash, space-in-pathname, or other unixy-vs-windows things. They are as much a property of the platform, and therefore something that must be acknowledged and worked around.

This affects a small number of us: the domain of affected users is very specifically windows users who use ODBC to pull data from SQL Server. The only other way to access SQL Server for "us" is via Imanuel's deprecated and shut-down [`RSQLServer`](https://github.com/imanuelcostigan/RSQLServer) (using `rJava` and JDBC), and since that project is archived, the chances of keeping it viable are rather slim.

This issue is not about fixing the problem, it's about generalizing a "good" workaround. This might be just `select_end` as defined above, providing a more compact solution to the literal `select(-notes, everything(), notes)` (for all long-data fields) with `select_end(notes)`.

Possible enhancements, and I bring them up as much for discussion as anything else:

- (Easy but hackish) Support a list of "known long" field names that should be moved to the end, and if present will be moved to the end (possibly unnecessary, depending on the specificity of the names);
- (More difficult) Determine from the compiled query the `table.field` being retrieved, and with a user-provided list of known long fields, move the resulting columns to the end; this still requires knowledge of the fields, which seems reasonable;
- (Very difficult) Automatically detect via column types which fields are "long", allowing the user to know nothing about the problematic fields and operate with impunity with merely a trailing `select_end()`.

There have been short conversations with Jim about this, and his comments were similar to yours, including mention of RStudio's commercial ODBC drivers (for linux). Unfortunately, as long as I (and others) must use windows, *there is literally no option*.

**Comment by r2evans** [comment]
... but I'm encouraged to hear that there have been discussions with Simba about it. Even more so if it is not a non-free driver.
