### ISSUE TITLE
Bug: Having tbl() inside list() variable fails since R3.5.x for SQL Server

### ISSUE THREAD

**Issue by N1h1l1sT** [tidyverse/dbplyr#223]
Okay, so for R version before 3.5 this worked fine, but now if there are dbplyr tbl() inside a list variable the show method fails.
Please note that the actual SQL Code produced by `ListVariable$tblName` works when copy/pasting it to SSMS.
Please also note that trying to print this kind of list variable in rgui.exe will cause it to crash, on RStudio you get an error:
```
Error: <SQL> 'SELECT  TOP 11 *
FROM "DIM_Employee"'
  nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'DIM_Employee'.
```
And if you try to print it on Visual Studio 2017's it will actually print correctly (which is so confusing!)

Reproducing the problem: Just create a list variable with any tbl() with a SQL Server connection and try to print them

Example
```r
library(magrittr)
library(dplyr)
library(dbplyr)
library(DBI)

con <- DBI::dbConnect(odbc::odbc(),
                      Driver = "{SQL Server};", Database = "YourDatabaseName", Server = "YourServerNameOrIP",
                      UID = NULL,
                      PWD = NULL,
                      Trusted_Connection = TRUE,
                      port = 1433
                      )

a <- NULL
a[["First"]] <- tbl(con, "DIM_Employee")
a[["Second"]] <- tbl(con, "DIM_Site")
a
```

> $First

> Error: <SQL> 'SELECT  TOP 11 *
> FROM "DIM_Employee"'
>   nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'DIM_Employee'.

**Comment by edgararuiz** [comment]
It seems that there is an extra escaping that occurs when doing it this way.  But it is not visible until using a backtrace:

`Error: <SQL> 'SELECT TOP 1000 * FROM "ÿþairportsÿþ"' nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'ÿþairportsÿþ'.`

I'll research further

**Comment by edgararuiz** [comment]
It looks like it has to do with how RStudio handles encoding in Windows machines, I'm able to recreate in an interactive session:

```r
> library(DBI)
> library(dbplyr)
> library(dplyr)
> con <- dbConnect(odbc::odbc(), Driver = "SQL Server", Server = "localhost\\SQLEXPRESS",
+                  Database = "datawarehouse", Trusted_Connection = "True")
> a <- list(
+   first = tbl(con, "airports"),
+   second = tbl(con, "airlines")
+ )
> a
$first
Error: <SQL> 'SELECT TOP 11 *
FROM "airports"'
  nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'airports'. 
```
But not when I run it as a `reprex` or when I run it in "bare" R: 

``` r
library(DBI)
library(dbplyr)
library(dplyr)

con <- dbConnect(odbc::odbc(), Driver = "SQL Server", Server = "localhost\\SQLEXPRESS",
                 Database = "datawarehouse", Trusted_Connection = "True")
a <- list(
  first = tbl(con, "airports"),
  second = tbl(con, "airlines")
)
a
#> $first
#> # Source:   table<airports> [?? x 8]
#> # Database: Microsoft SQL Server
#> #   14.00.1000[dbo@LAPTOP-368HS2ML\SQLEXPRESS/datawarehouse]
#>    faa   name                    lat    lon   alt    tz dst   tzone        
#>    <chr> <chr>                 <dbl>  <dbl> <int> <dbl> <chr> <chr>        
#>  1 04G   Lansdowne Airport      41.1  -80.6  1044    -5 A     America/New_~
#>  2 06A   Moton Field Municipa~  32.5  -85.7   264    -6 A     America/Chic~
#>  3 06C   Schaumburg Regional    42.0  -88.1   801    -6 A     America/Chic~
#>  4 06N   Randall Airport        41.4  -74.4   523    -5 A     America/New_~
#>  5 09J   Jekyll Island Airport  31.1  -81.4    11    -5 A     America/New_~
#>  6 0A9   Elizabethton Municip~  36.4  -82.2  1593    -5 A     America/New_~
#>  7 0G6   Williams County Airp~  41.5  -84.5   730    -5 A     America/New_~
#>  8 0G7   Finger Lakes Regiona~  42.9  -76.8   492    -5 A     America/New_~
#>  9 0P2   Shoestring Aviation ~  39.8  -76.6  1000    -5 U     America/New_~
#> 10 0S9   Jefferson County Intl  48.1 -123.    108    -8 A     America/Los_~
#> # ... with more rows
#> 
#> $second
#> # Source:   table<airlines> [?? x 3]
#> # Database: Microsoft SQL Server
#> #   14.00.1000[dbo@LAPTOP-368HS2ML\SQLEXPRESS/datawarehouse]
#>    row_names name                 carrier
#>    <chr>     <chr>                <chr>  
#>  1 3         1Time Airline        1T     
#>  2 10        40-Mile Air          Q5     
#>  3 13        Ansett Australia     AN     
#>  4 14        Abacus International 1B     
#>  5 15        Abelag Aviation      W9     
#>  6 21        Aigle Azur           ZI     
#>  7 22        Aloha Airlines       AQ     
#>  8 24        American Airlines    AA     
#>  9 28        Asiana Airlines      OZ     
#> 10 29        Askari Aviation      4K     
#> # ... with more rows
dbDisconnect(con)
```

<sup>Created on 2019-02-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

And easy work-around is to use `purrr` to iterate through each list item:

```
> purrr::walk(a, ~print(head(.x)))
# Source:   lazy query [?? x 8]
# Database: Microsoft SQL Server 14.00.1000[dbo@LAPTOP-368HS2ML\SQLEXPRESS/datawarehouse]
  faa   name                             lat   lon   alt    tz dst   tzone           
  <chr> <chr>                          <dbl> <dbl> <int> <dbl> <chr> <chr>           
1 04G   Lansdowne Airport               41.1 -80.6  1044    -5 A     America/New_York
2 06A   Moton Field Municipal Airport   32.5 -85.7   264    -6 A     America/Chicago 
3 06C   Schaumburg Regional             42.0 -88.1   801    -6 A     America/Chicago 
4 06N   Randall Airport                 41.4 -74.4   523    -5 A     America/New_York
5 09J   Jekyll Island Airport           31.1 -81.4    11    -5 A     America/New_York
6 0A9   Elizabethton Municipal Airport  36.4 -82.2  1593    -5 A     America/New_York
# Source:   lazy query [?? x 3]
# Database: Microsoft SQL Server 14.00.1000[dbo@LAPTOP-368HS2ML\SQLEXPRESS/datawarehouse]
  row_names name                 carrier
  <chr>     <chr>                <chr>  
1 3         1Time Airline        1T     
2 10        40-Mile Air          Q5     
3 13        Ansett Australia     AN     
4 14        Abacus International 1B     
5 15        Abelag Aviation      W9     
6 21        Aigle Azur           ZI
```

I'm honestly not sure of the best way forward for this.  My first reaction is to wonder why simply pulling `a` to be printed is something that should be supported in the first place.  Hopefully the work around can get you unstuck for now.

**Comment by N1h1l1sT** [comment]
I'm not certain if your question means that you think a list of tbl() should have never been able to be printed in the first place, but if so:
Well, I think that as a list of data_frame() can be printed, it only makes sense that a list of tbl() should also be able to be printed.

I appreciate the workaround, it works like a charm and it's perfect for the time being.

For the future, I'm really crossing my fingers to having this actually fixed without the need for a workaround though.

**Comment by hadley** [comment]
@edgararuiz can you point me to a RSP instance that lets me look at this interactively?

**Comment by edgararuiz** [comment]
Yes, but in RSP, because it is a Linux server, the issue will not occur.  I will send you the info to the server via Slack.

**Comment by hadley** [comment]
Given that the problem occurs when printing `list(x)` and not `x`, this is unlikely to be a dbplyr problem, and so it's unlikely that a fix will be either easy or fast. Given the mojibake that you're seeing in your output, I _suspect_ this is a bug in base R (probably related to the complexities in https://github.com/wch/r-source/blob/e1cd297a23cbe79989d2ff1b47f0dc4ed1ddff1b/src/main/print.c#L741). 

Unfortunately, given the small number of people affected and the complexity of the bug, it's probably not going to be worthwhile to get to the bottom of the problem and fix it..
