### ISSUE TITLE
copy_to truncates strings with accented words

### ISSUE THREAD

**Issue by verajosemanuel** [tidyverse/dbplyr#230]
Inserting strings (spanish province names) on database containing accented words like:
```

PROVINCE
------------
Málaga
Córdoba
Cádiz

ends with this 

PROVINCE
------------
M
C
C

 insertconnection <- DBI::dbConnect(RMySQL::MySQL(),
                              host = "myhost",
                              user = "myuser",
                              password = "mypass",
                              db = "mydb"
  )

dbExecute(insertconnection, as.character('set character set "utf8"'))

copy_to(insertconnection, dataframe, temporary = FALSE, overwrite = TRUE)
```

**Comment by hadley** [comment]
Can you please confirm that this works if you instead use DBI::dbWriteTable?

**Comment by verajosemanuel** [comment]
> insertconnnection <- DBI::dbWriteTable(RMySQL::MySQL(),
+                             host = "myhost",
+                             user = "myuser",
+                             password = "mypass",
+                             db = "mydb"
+ )
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbWriteTable’ for signature ‘"MySQLDriver", "missing", "missing"’

**Comment by hadley** [comment]
Please read the documentation for `dbWriteTable()`; that's not how you use it.

**Comment by verajosemanuel** [comment]
Sorry, my bad.  But I can confirm the same issue using dbWriteTable. Province names are truncated if they have accented characters.
```

DBI::dbWriteTable(conn = insertconnection,
                  name = SQL('provinces'),
                  value = dataframe,
                  append = FALSE)
```

**Comment by hadley** [comment]
In that case, I'd first trying switching from RMySQL to RMariaDB, and if that still doesn't work, filing bugs for those packages.
