### ISSUE TITLE
Can't abort (interrupt) query

### ISSUE THREAD

**Issue by shgoke** [tidyverse/dbplyr#231]
I wanted to abort (interrupt) a query that takes just too long to implement, but the usual procedure doesn't seem to work (the only thing I can do is to kill the R process).

I'm using R 3.5.2 on OS X Mojave, dbplyr 1.3.0 and SQLite. I usually use R from Emacs + ESS but I observe the same issue on R console.

After running a query that goes on and on on R console, I typed `Ctrl+C`, but this doesn't change the situation. Am I missing something?

**Comment by hadley** [comment]
This is outside the control of dbplyr. You need to file an issue with the underlying database package (e.g. RMySQL, RPostgreSQL etc)
