### ISSUE TITLE
Backend: SAP HANA

### ISSUE THREAD

**Issue by javierluraschi** [tidyverse/dbplyr#233]
While SAP HANA has been reported to work with `dbplyr`, there is functionality that is unsupported and will need special translations in `dbplyr`, for instance:

- `dbplyr::compute()` and `dbplyr::copy_to()` require temp tables to be prefixed with `#`.
-  No support for `logical` types since `BIT` require a different mapping.

In order to test and resolve those issues, a SAP HANA cloud instance can be started in Amazon thorough [SAP HANA on AWS](https://aws.amazon.com/sap/solutions/saphana/) and [Azure SAP HANA](https://azure.microsoft.com/en-us/blog/azure-data-factory-offer-sap-hana-and-business-warehouse-data-integration/).

The ODBC drivers can be downloaded as follows:
- Register as a SAP Developer under [developers.sap.com](https://developers.sap.com)
- Download the ODBC from [SAP HANA Client Software Packages](https://www.sap.com/developer/trials-downloads/additional-downloads/sap-hana-client-software-packages-12950.html).

CC: @edgararuiz

**Comment by hadley** [comment]
Do we have a specific need/request for SAP HANA support?

**Comment by xstodeepak** [comment]
It would be awesome for the entire corporate community for which SAP HANA is the backbone of entire reporting. Around 90-95% of the organizations use SAP HANA for all of their reporting needs. 

Having dbplyr support for SAP HANA would immensely benefit the developer/data scientist community, since, HANA database has complex table structures and lack of BI Infrastructure with SAP. Getting BI projects done by IT teams is really a pain and having dbplyr support for SAP Hana will ease this pain to a very large extent.

Hence, requesting SAP HANA database support by dbplyr.

**Comment by deathbydata** [comment]
+1 request for HANA dbplyr translation.

We’re pretty organisationally locked into HANA as an RDBMS and dbplyr has been a big unlock for our teams.

Being able to make full use of dbplyr functionality and particularly upload/temp table creation would be huge for us.

**Comment by hadley** [comment]
* identifier/string quoting should hopefully be taken care of by the odbc driver
* data types (for escaping and `as.*` translations): https://help.sap.com/viewer/7c78579ce9b14a669c1f3295b0d8ca16/Cloud/en-US/20a1569875191014b507cf392724b7eb.html
* uses `||` for string concatenation
* SELECT docs: https://help.sap.com/viewer/7c78579ce9b14a669c1f3295b0d8ca16/Cloud/en-US/20fcf24075191014a89e9dc7b8408b26.html
* Uses TOP, not LIMIT
* Temporary tables use `LOCAL TEMPORARY COLUMN TABLE` (https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.03/en-US/20d58a5f75191014b2fe92141b7df228.html) — also need `#` name.
* String functions: https://help.sap.com/viewer/7c78579ce9b14a669c1f3295b0d8ca16/Cloud/en-US/20a24d4b75191014afc5ac3b997d3ce2.html
* Same problem as MS SQL with distinct predicate and boolean types: https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.03/en-US/f044a9c7fb7b49159384f92f147345fb.html

**Comment by hadley** [comment]
The basics are now in dev dplyr + https://github.com/r-dbi/odbc/pull/396. This seems to mostly work for me locally. The mac hana ODBC driver seems to be extremely crash prone but I'm pretty sure that's unrelated to odbc/dbplyr. However, it makes for an extremely frustrating development experience, so I've put in as much time into this as I'm willing to. Hopefully there's enough there that other folks in the community can add on as needed.
