### ISSUE TITLE
Vignette references RPostgreSQL instead of RPostgres

### ISSUE THREAD

**Issue by alex-gable** [tidyverse/dbplyr#245]
The vignette should be updated to reflect the creation and usage of r-dbi/RPostgres, which is kept much more up-to-date and in the same "universe" as RSQLite, for example.

I'm happy to make these changes!

**Comment by hadley** [comment]
A PR would be wonderful! (I think it might also need an update from RMySQL to RMariaDB for similar reasons)

**Comment by krlmlr** [comment]
But the code still uses RPostgreSQL and doesn't use RPostgres?
