### ISSUE TITLE
Incorrect syntax for MS SQL via FreeTDS?

### ISSUE THREAD

**Issue by JakeRuss** [tidyverse/dbplyr#246]
I'm having trouble setting up a basic tbl connection using the FreeTDS driver to access MS SQL. 

I have compiled my TDS to version 7.3, 

```
tsql -C

rstudio@ip-10-0-0-12:~/freetds-1.00.111$ tsql -C
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00.111
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: no
```
I added FreeTDS to my `odbcinst.ini` file and I then connect to the database with the following, 
```
connection <- dbConnect(odbc::odbc(),
                        Driver    = "FreeTDS",
                        Server    = credentials$host, 
                        Database  = credentials$database,
                        UID       = credentials$username,
                        PWD       = credentials$password)
```
Which successfully connects to the database. 

But when I try to `tbl()` any of my tables in the database I'm met with, 
```
tbl_object      <- connection %>% dplyr::tbl("tablename")

Error: <SQL> 'SELECT *
FROM "tablename" AS "zzz4"
WHERE (0 = 1)'
  nanodbc/nanodbc.cpp:1587: 42000: [FreeTDS][SQL Server]Incorrect syntax near 'tablename'.
```
I originally thought this might be a schema issue, so I tried the pattern, `tbl(connection, in_schema("dbo", "tablename"))` and I still get the same error message. I'm not sure why it appends the `WHERE (0 = 1)` to the query.

However, if I run `dbGetQuery(connection, "SELECT TOP 10 * FROM tablename")`, that query returns the data with no trouble.

I saw [this SO question](https://stackoverflow.com/questions/49004872/cant-get-data-with-dbplyr-from-shiny-server) and their problem appears to be similar to mine but I tried @edgararuiz's solution to no avail and I wonder if that advice is now out of date? When I run `class(connection)` my object's class is Microsoft SQL Server already. 
```
> class(connection)
[1] "Microsoft SQL Server"
attr(,"package")
[1] ".GlobalEnv"
```
So it is confusing as to why `sql_translate_env.Microsoft SQL Server` and `sql_select.Microsoft SQL Server` would not be working as intended.

**Comment by edgararuiz** [comment]
Yes, the `WHERE (0=1)` is a technique to pull the field names from the query (table) so that they can be available for the autocomplete.  Can you try running the query in the error message through `DBI::dbGetQuery()` and see if if fails there as well.  I get the sense that FreeTDS may not like the `"` as an expression escaping, so if the first test with `dbGetQuery()` fails for you, can you try replacing the `"` with `'`?  Thanks

**Comment by JakeRuss** [comment]
Thank you for the quick response @edgararuiz, but I think you misunderstood. `tbl()` is what fails me, not `DBI::dbGetQuery()`.

**Comment by JakeRuss** [comment]
Ugh, I misread your comment, @edgararuiz. 

```
DBI::dbGetQuery(connection, "SELECT * FROM 'tablename' AS 'zzz4' WHERE (0 = 1)")
DBI::dbGetQuery(connection, 'SELECT * FROM "tablename" AS "zzz4" WHERE (0 = 1)')
```
Both of these fail with the same message,
`nanodbc/nanodbc.cpp:1587: 42000: [FreeTDS][SQL Server]Incorrect syntax near 'Node'`

**Comment by JakeRuss** [comment]
I tried `DBI::dbGetQuery(connection, "SELECT * FROM tablename AS zzz4 WHERE (0 = 1)")` and this succeeds. 

It returned a data.frame with correct 20 columns and `<0 rows> (or 0-length row.names)`.

**Comment by edgararuiz** [comment]
Ok, can we try with the backtick? `

I think we'd rather have a valid escaping character than to remove it completely

**Comment by JakeRuss** [comment]
Sure. 
`DBI::dbGetQuery(connection, "SELECT * FROM `Node` AS `zzz4` WHERE (0 = 1)")` generates, 
`Error: <SQL> 'SELECT * FROM `tablename` AS `zzz4` WHERE (0 = 1)'
  nanodbc/nanodbc.cpp:1587: 42000: [FreeTDS][SQL Server]Incorrect syntax near '`'.`

**Comment by JakeRuss** [comment]
It appears to be brackets `[` `]`. 

`DBI::dbGetQuery(connection, "SELECT * FROM [tablename] AS [zzz4] WHERE (0 = 1)")` works.

**Comment by edgararuiz** [comment]
Interesting, I'm not sure if the escaping functions we use have a notion of start/end position.  I'll check.

**Comment by hadley** [comment]
Can you both please try running `SELECT sessionproperty('QUOTED_IDENTIFIER')` in your current SQL server databases? I think this might explain why @JakeRuss has a problem but @edgararuiz does not.

**Comment by hadley** [comment]
Ah, this might be the difference:

> The SQL Server Native Client ODBC driver and SQL Server Native Client OLE DB Provider for SQL Server automatically set QUOTED_IDENTIFIER to ON when connecting. This can be configured in ODBC data sources, in ODBC connection attributes, or OLE DB connection properties. The default for SET QUOTED_IDENTIFIER is OFF for connections from DB-Library applications.

— https://docs.microsoft.com/en-us/sql/t-sql/statements/set-quoted-identifier-transact-sql?view=sql-server-2017

**Comment by JakeRuss** [comment]
I tried the `SELECT` statement above twice. I ran it from an RStudio connection object and it returned a single row data frame with, `0`. I then tried it from SQL Server MS and it returned a `1`.

**Comment by JakeRuss** [comment]
Also at your link @hadley there is this line

> Using brackets, [ and ], to delimit identifiers is not affected by the QUOTED_IDENTIFIER setting.

which may explain why my query with `[` `]` succeeds.

**Comment by JakeRuss** [comment]
Your `QUOTED IDENTIFIER` inquiry led me to this `odbc` issue: https://github.com/r-dbi/odbc/issues/209

Once I ran `DBI::dbExecute(con, "SET QUOTED_IDENTIFIER ON")` the problem with `tbl()` is fixed.

**Comment by hadley** [comment]
@JakeRuss can you confirm that the query with names quoted by `[]` also works when run directly in SQL server? If so, it seems like it will be safe to change quoting globally (if that's possible with the current design of dbplyr, if not, you'll just have to run `SET QUOTED_IDENTIFIER ON` by hand)

**Comment by hadley** [comment]
Ah, I missed your pointer to that odbc issue — in that case I think this issue should be closed, although you might while to file an issue with the freeTDS driver to do it automatically (in order to match the official odbc drivers)

**Comment by freddy77** [comment]
FreeTDS ODBC driver turns on by default the `QUOTED_IDENTIFIER` setting connecting to MS server.
Exception are DB-library (which is not ODBC) and a TDS protocol < 7.0.
Can you use TDSDUMP to confirm which setting issue you are having?

**Comment by JakeRuss** [comment]
Yes, but I'll continue this discussion over at https://github.com/FreeTDS/freetds/issues/271 instead of cross posting both places.

**Comment by JakeRuss** [comment]
To close the loop here for anyone who might stumble upon this issue: I mis-specified the location of my FreeTDS driver. I was referencing an old TDS driver in my `odbcinst.ini` file, which defaulted my R session to use TDS 4.2. Once I referenced the updated driver, the 7.3 TDS protocol set QUOTED_IDENTIFIER correctly and the original issue went away.

I can confirm that `tbl_object <- connection %>% dplyr::tbl("tablename")` works with MS SQL Server as intended.
