### ISSUE TITLE
Proper way to define custom sql functions

### ISSUE THREAD

**Issue by FrancoisGuillem** [tidyverse/dbplyr#247]
In order to improve code readibility and robustness, I want to define some custom SQL scalar functions. For now what I am doing is create a new SQL variant. To do that I have to change the class of the connexion object:

```r
setClass("my_connexion", contains = "PostgreSQLConnection")

postgres_env <- dplyr::sql_translate_env(dbplyr::simulate_postgres())

sql_translate_env.my_connexion <- function(x) {
  sql_variant(
    scalar = sql_translator(
      .parent = postgres_env$scalar,
      weibull_surv = function(t, model) {
        par <- model$par
        translate_sql(exp(-(!!t) ^ (!!par$k) / (!!par$l)) * ifelse(!!t == 0,!!par$adj0, 1),
                      con = x)
      }
    ),
    aggregate = sql_translator(.parent = postgres_env$aggregate),
    window = sql_translator(.parent = postgres_env$window)
  )
}

con <- DBI::dbConnect(RPostgreSQL::PostgreSQL(), ...)
class(con) <- "my_connexion"
tbl(con, "my_table") %>% mutate(pred = weibull_surv (seniority, model))
```
Is there a better way to achieve the same result?

**Comment by edgararuiz** [comment]
I think you should be able to define the `sql_translate()` for `PostgreSQLConnection` in your Global Environment, and that should take priority over the function inside `dbplyr`.  Then, you can call the `sql_translate()` function of `dbplyr` from within your function.  Hope that make sense.

**Comment by FrancoisGuillem** [comment]
I already tried this. I'm not sure why but it did not work so that is why have created a new class.

I see two other problems in my code:
* I use some hacky code to get the current sql variant for Postgresql and modify it.
* My SQl expression contains only simple operations and should work with any SQL database. But here I have defined my function only for Postgresql.  If I want to define it for different databases, I need to replicate the above code.

**Comment by hadley** [comment]
There's no current way to add custom translations in this way. The best you can do is to write a function that generates the expressions for you:

```R
weibull_surv <- function(t, model) {
  x <- enquo(t)
  par <- model$par
  expr(exp(-(!!t) ^ (!!par$k) / (!!par$l)) * ifelse(!!t == 0, !!par$adj0, 1))
}
```

Then manually unquote the result:

```R
tbl(con, "my_table") %>% mutate(pred = !!weibull_surv(seniority, model))
```

**Comment by andyquinterom** [comment]
I believe a better aproach is would be to create a R-sql dictionary object and pass that onto the connection or the tbl, idk. Some way for users and developers to define a new set of translations and pass it on to the functions.

Just thinking about it like 

```R
my_dictionary <- sql_translator(
  weibull_surv = function(t, model) {
    par <- model$par
    translate_sql(exp(-(!!t) ^ (!!par$k) / (!!par$l)) * ifelse(!!t == 0,!!par$adj0, 1), con = x)
  }
)

tbl(conn, "example_table", sql_dictionary = my_dictionary
```
