### ISSUE TITLE
Error when using select on SQLite

### ISSUE THREAD

**Issue by tomauer** [tidyverse/dbplyr#249]
I'm getting the following error when I try to use `select()` on a SQLite database.

> Error in (function (classes, fdef, mtable)  : 
>   unable to find an inherited method for function ‘select’ for signature ‘"tbl_SQLiteConnection"’

```
checklists <- tbl(con, sql("SELECT * FROM checklists")) %>%
  select(SAMPLING_EVENT_ID)
```

Here's my DB header. I can't attached the database here as it's 18GB.

> Source:   SQL [?? x 230]
> Database: sqlite 3.22.0 [/Users/mta45/Box Sync/Projects/2018_status_and_trends/ERD2019_DATA_SPECIES_4466_TO_4466.db]

All my reading of the examples and documentation indicate that `select()` should work in this manner.

**Comment by romatik** [comment]
Maybe I'm missing something, but your syntax doesn't look right to me. Can you try with something like this:
```
checklists <- tbl(con, "checklists") %>%
  select(SAMPLING_EVENT_ID)
```

**Comment by tomauer** [comment]
I get the same error.

**Comment by romatik** [comment]
Then it's likely there is something specific to your setup. I can use SQLite without any issues:
``` r
library(magrittr)
con <- DBI::dbConnect(drv = RSQLite::SQLite())

dplyr::copy_to(con, iris)

iris <- dplyr::tbl(con, "iris") %>%
  dplyr::select(Species)

iris
#> # Source:   lazy query [?? x 1]
#> # Database: sqlite 3.22.0 []
#>    Species
#>    <chr>  
#>  1 setosa 
#>  2 setosa 
#>  3 setosa 
#>  4 setosa 
#>  5 setosa 
#>  6 setosa 
#>  7 setosa 
#>  8 setosa 
#>  9 setosa 
#> 10 setosa 
#> # … with more rows
```

<sup>Created on 2019-03-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by tomauer** [comment]
I'm able to get it to work with this code. Thanks.
