### ISSUE TITLE
Consider tidyr implementations for SQL

### ISSUE THREAD

**Issue by hadley** [tidyverse/dbplyr#252]
e.g.

* `complete()` #240
* `spread()` & `gather()` #189

**Comment by hadley** [comment]
Moved to dbplyr, since that contains all the low-level primitives needed for SQL generation

**Comment by edgararuiz** [comment]
Should I finish this PR? https://github.com/tidyverse/dbplyr/pull/72

**Comment by hadley** [comment]
See https://github.com/halpo/pivot for existing work.

**Comment by edgararuiz** [comment]
Should we target `pivot_longer()` and `pivot_wider()` instead of `spread()` and `gather()`?

**Comment by hadley** [comment]
Yes. Although for an initial implementation we’d ignore most of the advanced features.

**Comment by aldomann** [comment]
Any updates on this?

**Comment by aldomann** [comment]
@edgararuiz thanks, managed to do what i wanted to do in another way, but I'll definitely check it out later and try to replicate my results and compare.

**Comment by edgararuiz** [comment]
That'll be great, thank you

**Comment by ben1787** [comment]
I see that pivot_longer does not work on an uncollected dbplyr tibble. Should I just be using gather?

Thanks!
Ben

**Comment by abalter** [comment]
What is the status of implementing `unnest`?

**Comment by hadley** [comment]
Done, thanks to @mgirlich!
