### ISSUE TITLE
`copy_to()` broke for MS SQL connections

### ISSUE THREAD

**Issue by mkirzon** [tidyverse/dbplyr#281]
The development version of dbplyr (1.3.0.9) stopped successfully writing to a MS SQL connection using the `copy_to` command. The same exact code works fine in the CRAN version. 

Let me know if issue reports for development reports should be generated elsewhere.

In the reprex below, unfortunately I don't think we can reproduce with the `simulate_mssql()` method. 

``` r
devtools::dev_mode(on = TRUE)
library(tidyverse)

con_prodeng = DBI::dbConnect(odbc::odbc(), Driver = "SQL Server", Server = "ServerName", Database = "DBName")

df = tribble(
  ~name, ~age,
  "Mark", 26,
  "Jamie", 10)

copy_to(dest = con_prodeng, df = df, name = "test1")
#> Created a temporary table named: ##test1
#> Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'dbWriteTable' for signature '"Microsoft SQL Server", "SQL", "character"'
```

**Comment by hadley** [comment]
Should be fixed in #280
