### ISSUE TITLE
DDL tests for simulated DBI

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dbplyr#284]
Methods like `db_compute()` and `db_copy_to()` currently require a real database to be tested against. Suggesting the following approach:

1. Define a `db_execute()` generic, implement it only for the `"TestConnection"` class (which would print the SQL) and for `"DBIConnection"` (which forwards to `DBI::dbExecute()`)
2. Replace all calls to `DBI::dbExecute()` with calls to `db_execute()`
3. Run tests with `simulate_dbi(...)`, capture output

Reference: https://github.com/tidyverse/dbplyr/pull/280/files#r275091349

**Comment by hadley** [comment]
If we going to rearchitect stuff, I think it would be better to extract out a separate method that just generates the SQL.

**Comment by hadley** [comment]
Looks like these are the main generics that generate then execute SQL:

* `db_explain`
* `db_analyze`
* `db_save_query`
* `db_create_index` — but only used by MySQL and now I don't see why* 
* `db_drop_table`

I'm going to add matching `sql_*()` generics, and change the default `db_*()` to call use `sql_*` + `dbExecute()`.

**Comment by hadley** [comment]
`db_save_query()` is a little trickier because it has to return the name, and MS SQL needs to mangle it. So probably needs another new generic. (Which I think SAP HANA will also use)
