### ISSUE TITLE
Test complex SQL queries with known files

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dbplyr#285]
e.g. https://github.com/tidyverse/dbplyr/blob/dcb2228d896702119e41227fdad2176f381e63a3/tests/testthat/test-backend-mssql.R#L151-L162

Reference: https://github.com/tidyverse/dbplyr/pull/277#discussion_r274928314

**Comment by hadley** [comment]
Now in #419; we'll use the new snapshot testing features in testthat 3e.
