### ISSUE TITLE
Consider better naming for temporary tables in MSSQL

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dbplyr#286]
With the current implementation of storing temporary tables as global temporary tables in MSSQL (with the `##` prefix), we are prone to name clashes when more than one connection accesses the same server.

Can we use a UUID or something as part of the temporary table names we create?

To use local temporary tables, we need https://github.com/r-dbi/odbc/pull/272.

**Comment by krlmlr** [comment]
@hadley: Any chance a change like this can make this in the upcoming release?

**Comment by hadley** [comment]
No, I don't think so.

**Comment by krlmlr** [comment]
Local temporary tables should finally work any time soon.
