### ISSUE TITLE
`translate_sql()` fails with `is.na()` for Microsoft SQL Server

### ISSUE THREAD

**Issue by halpo** [tidyverse/dbplyr#290]
With the 1.4.0 version release of `dbplyr` broke `translate_sql()` with `is.na` for Microsoft SQL Server.  This can be seen using the `simulate_mssql()` connection.

``` r
library(dbplyr)
translate_sql(is.na(x), con = simulate_mssql())
#> Error: $ operator is invalid for atomic vectors
```

<sup>Created on 2019-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
Only broken in `translate_sql()`: 

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

lf <- lazy_frame(x = 1, con = simulate_mssql())
lf %>% mutate(y = is.na(x))
#> <SQL>
#> SELECT `x`, CONVERT(BIT, IIF(`x` IS NULL, 1, 0)) AS `y`
#> FROM `df`
lf %>% filter(is.na(x))
#> <SQL>
#> SELECT *
#> FROM `df`
#> WHERE (((`x`) IS NULL))
```

<sup>Created on 2019-06-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
