### ISSUE TITLE
Columns duplicated when part of a join using sql_on()  

### ISSUE THREAD

**Issue by vadimus202** [tidyverse/dbplyr#292]
Thank you for adding `sql_on` argument to remote joins. I noticed that the result returns the columns from both side of the expression. I understand that this is probably the desired behavior when a SQL expression is used, i.e. an inequality or `BETWEEN`. However, a frequent use case at my work is to join on a mix of expressions that include both equalities and other expressions. 

```r
library(dplyr)
library(dbplyr)

df1 <- lazy_frame(x = 1:5, y = 5:1)
df2 <- lazy_frame(x = 1:10, y = 10:1)
```

This duplicates the `x` column:
```r
inner_join(df1, df2, sql_on = "LHS.x = RHS.x and LHS.y > RHS.y")
#> <SQL>
#> SELECT `LHS`.`x` AS `x.x`, `LHS`.`y` AS `y.x`, `RHS`.`x` AS `x.y`, `RHS`.`y` AS `y.y`
#> FROM `df` AS `LHS`
#> INNER JOIN `df` AS `RHS`
#> ON (LHS.x = RHS.x and LHS.y > RHS.y)
```
Is it possible for SELECT translation to automatically return only the LHS column when the expression is an equality? 

I guess another (maybe easier?) option would be to allow a mix of both arguments: `by` for strict equalities and `sql_on` for other expressions, as shown below?

```r
inner_join(df1, df2, by = "x", sql_on = "LHS.y > RHS.y")
```
Thanks

**Comment by hadley** [comment]
I think the pay off for this work is going to be relatively low given that'll be quite a lot of work and is going to only affect a few people; so I think that means for now you'll just need to fix up after the fact with `select()`. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
