### ISSUE TITLE
str_detect() for MSSQL gone in dbplyr 1.4.0

### ISSUE THREAD

**Issue by mkirzon** [tidyverse/dbplyr#295]
Looks like the latest release of dbplyr lost support for the stringr function `str_detect()` against an MS SQL Server connection. 

### Reprex with dbplyr 1.3.0
``` r
library(tidyverse)
library(dbplyr)

df = tibble(letters = LETTERS)
df_remote = tbl_lazy(df, src = dbplyr::simulate_mssql())

df_remote %>%
  mutate(test = str_detect(letters, "B")) %>%
  show_query()
#> <SQL> SELECT `letters`, CHARINDEX('B', `letters`) > 0 AS `test`
#> FROM `df`
```

### Reprex with dbplyr 1.4.0
``` r
library(tidyverse)
library(dbplyr)

df = tibble(letters = LETTERS)
df_remote = tbl_lazy(df, con = dbplyr::simulate_mssql())

df_remote %>%
  mutate(test = str_detect(letters, "B")) %>%
  show_query()
#> <SQL>
#> Error: str_detect() is not available in this SQL variant
```

**Comment by hadley** [comment]
Yes, because it never actually worked correctly.

**Comment by mkirzon** [comment]
> Yes, because it never actually worked correctly.

Is the best solution for regex for mssql connections then to use the %like% operator directly?

**Comment by hadley** [comment]
That's not really a regular expression either, but yes.

**Comment by leungi** [comment]
@hadley: is regex for MSSQL part of the `dbplyr` roadmap?

**Comment by hadley** [comment]
You'd have to ask Microsoft. SQL server doesn't support regular expressions as far as I can tell.

**Comment by leungi** [comment]
Noted; thanks for prompt response @hadley.

On a side note, I see the same issue with Oracle as well. Is this for the same reason as MSSQL?

**Comment by sheepworrier** [comment]
> > Yes, because it never actually worked correctly.
> 
> Is the best solution for regex for mssql connections then to use the %like% operator directly?

Any chance of an example please?

**Comment by mkirzon** [comment]
For those looking for the "workaround" on MS SQL, here's an example: 
```
df_remote %>%
  filter(letters %like% "B")
```

**Comment by mkirzon** [comment]
Posted one on the original thread
<https://github.com/tidyverse/dbplyr/issues/295#issuecomment-523089704>

**Comment by steer629** [comment]
> For those looking for the "workaround" on MS SQL, here's an example:
> 
> ```
> df_remote %>%
>   filter(letters %like% "B")
> ```

I'd like use same mehtod both in dplyr and dbplyr,  so if we use **filter(letter %like% "B") this for me not working** or filter(letter %like% "%B%"), the code can't be reused in dplyr.

grepl not support by dbplyr

so if we have str_detect solution work properly, that would be great.

**Comment by leungi** [comment]
In my experience with Oracle and MSSQL, `df_remote %>%  filter(letters %like% "%B%")` works.

What does `df_remote %>% filter(letters %like% "%B%") %>% show_query()` says? 

Try running the generated SQL statement natively in Oracle/SQL. 

If all else fail, then your SQL skills will be put to good use via `sql()` wrapper 🙂 - [reference](https://dbplyr.tidyverse.org/articles/sql.html).
