### ISSUE TITLE
Regression when using filter from tbl (ESCAPE method not found)

### ISSUE THREAD

**Issue by ngageorange** [tidyverse/dbplyr#299]
Hello,
There seems to be a regression/problem with using dbplyr with postgresql.

`ids_df <- tibble(
  ids = c(1, 2, 3, 4)
)`
`my_table <- tbl(con, "db_table") %>% 
  filter(id %in% ids_df$ids) %>% show_query()`

results in:
`Error in UseMethod("escape") : 
  no applicable method for 'escape' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"`

However, this runs:
`var <- escape(ids_df$ids, con=con)`
`my_table <- tbl(con, "db_table") %>% 
  filter(id %in% var) %>% show_query()`

This also works:
`my_table <- tbl(con, "db_table") %>% 
  filter(id %in% c(1, 2, 3, 4)) %>% show_query()`

Any suggestions as to why this now required?

-ngageorange

**Comment by jakeybob** [comment]
I think this is mentioned in the breaking changes at the top of the [changelog](https://dbplyr.tidyverse.org/news/index.html#dbplyr-1-4-0) -- subsetting functions are no longer evaluated locally. (may also be related to #296)

Using `escape` as in your example or  `!!` as below should hopefully work.

```r
ids_df <- tibble( ids = c(1, 2, 3, 4) )
my_table <- tbl(con, "db_table") %>% filter(ids %in% !!ids_df$ids) %>% show_query()
```
```sql
SELECT *
FROM `ids_df`
WHERE (`ids` IN (1.0, 2.0, 3.0, 4.0))
```

**Comment by hadley** [comment]
Thanks @jakeybob!
