### ISSUE TITLE
Un-ideal NSE behavior when using `%in%` with `$` referenced columns in a secondary data frame

### ISSUE THREAD

**Issue by hrbrmstr** [tidyverse/dbplyr#300]
Via https://twitter.com/dataandme/status/1124032580221906944?s=20

I'll work up a real reprex if you are willing to spend money in Amazon Athena to reproduce and have access to their default logs DB.

I have this line of code from an earlier set of analysis code:

```r
filter(db, location__country_code3 %in% !!apac_countries$iso3c)
```

where `apac_countries` is:

```r
Observations: 44
Variables: 3
$ country_name <chr> "American Samoa", "Australia", "Bhutan", "Brunei Darussalam", "China", "Taiwan", "Hong…
$ iso2c        <chr> "AS", "AU", "BT", "BN", "CN", "TW", "HK", "CX", "CC", "CK", "FJ", "PF", "GU", "ID", "J…
$ iso3c        <chr> "ASM", "AUS", "BTN", "BRN", "CHN", "TWN", "HKG", "CXR", "CCK", "COK", "FJI", "PYF", "G…
```
 and `db` is created by code like:

```r
con <- DBI::dbConnect(odbc::odbc(), …)
db <- tbl(con, "seekrit_db_name")
```

The error I get is:

```r
## Error in UseMethod("escape") : 
##  no applicable method for 'escape' applied to an object of class "c('spec_tbl_df', 'tbl_df', 'tbl', 'data.frame')"
```

However it works if the `$`-referenced dataframe column is prefixed with `!!` (e.g. `!!apac_countries$iso3c`).

I am going to strongly posit that it should not require the `!!` to work since one would _kinda_ expect R code to work like R code should (and, it used to work).

**Comment by hadley** [comment]
This change was needed to support the many newer databases which allow nested fields, where `x$y$z` makes sense to translate to SQL. Unfortunately no package on CRAN used code like this, so I figured it was a fairly safe change to make.  But it seems like it's used frequently in practice, and the allusion in the release blog post wasn't enough.

**Comment by jessekps** [comment]
Hi,
sorry, just made a [new issue](https://github.com/tidyverse/dbplyr/issues/301) about this, I should have looked closer at the other posts. But I can say that the CRAN package dexter uses code like this (it might not be apparent from a code search because the predicate is forwarded from the user). I would appreciate it very much if this could be reversed.

thanks,
Jesse

**Comment by hrbrmstr** [comment]
@hadley I 100% see the need to support the funky (but, now, common) DB field-addressing syntax (and I need to try it with Drill and Athena map columns at some point) but I guess I'd rather see the need for folks who want to have that be transparent use something like a `quo()` wrapper (gross oversimplification just to limit the length of the comment reply) for those calls vs auto-assume what is valid R code was meant to be something pushed to the DB.

In the long run it's super easy to detect the error (now that I know the "why" it's happening) and modify any R scripts or Rmds we have at $WORK to use the new syntax when it's encountered and I've tweaked the infrequent areas we've used this syntax within $WORK R pkgs to work in the new fashion (with plenty of comments around said tweaks to enable quick reversal in the event this behavior is reversed :-).

Aligned w/r/t @cderv's comments, a more informative error would likely make the transition to the behavior easier for folks if it's going to remain.

**Comment by hadley** [comment]
I'll see what I can do about a better error message, and I'll add something more to the news, and the blog post. 

The other reason I removed this code is that it's utterly inconsistent with the rest of the translation — there's no other place where dbplyr guesses that an expression has to be R code.

**Comment by hadley** [comment]
What do you think of the error message in this imaginary reprex:

```R
library(dbplyr)
library(dbplyr, warn.conflicts = FALSE)

lf <- lazy_frame(x = 1, y = 2)

filter(lf, x %in% mtcars$cyl)
#> Error: Can not embed a data frame in a SQL query.
#> Hint: The behaviour of $ and [[ changed in dplyr 1.4.0.
#> (See https://github.com/tidyverse/dbplyr/issues/300 for more details)
#> The easiest fix is to unquote the subsetting with !!.
#> For example, if you previously had `df$x`, replace it with `!!df$x`
```

**Comment by hadley** [comment]
``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

lf <- lazy_frame(x = 1, y = 2)
filter(lf, x %in% mtcars$cyl)
#> <SQL>
#> Cannot embed a data frame in a SQL query.
#> 
#> If you are seeing this error in code that used to work, the most
#> likely cause is a change dbplyr 1.4.0. Previously `df$x` or
#> `df[[y]]` implied that `df` was a local variable, but now you must
#> make that explict with `!!` or `local()`, e.g., `!!df$x` or
#> `local(df[["y"]))
```

<sup>Created on 2019-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
