### ISSUE TITLE
na.omit.tbl_lazy ?

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dbplyr#304]
could we have a `tbl_lazy` for `na.omit` ? it's an *S3 generic*

I'm not sure how to translate it conveniently without it, as the following doesn't work.

```
tbl(con, "my_table") %>%
  filter_all(~!is.na(.))
```

so I end up repeating `... %>% filter(!is.na(var1), !is.na(var2), ...)` which seems suboptimal.

Moreover, `na.omit` doesn't fail on `tbl_lazy` objects, it just returns the input  unchanged ( as `tbl(con, "foo")` is a list without `NA`) , which might be unexpected by the user.

I guess it would imply building methods for and `na.fail` `na.exclude` as well. `na.pass` is not an `S3` generic but doesn't need a method as it's basically the `identity` function.

**Comment by hadley** [comment]
I think those generics are best reserved for their original use: in conjunction with the `na.action` argument of `lm()` and friends.

**Comment by moodymudskipper** [comment]
@hadley thanks, would you have a suggestion to emulate their behavior on remote data other than repeating `is.na` as many times as there are variables ?

Maybe you would consider have `na.omit.tbl_lazy` return an error ? the fact that it silently returns its output might cause a few head scratches.

**Comment by hadley** [comment]
`filter_if()` or `filter_at()`?

**Comment by moodymudskipper** [comment]
@hadley these don't work.

With *SQLite* all rows are filtered, with *PostgreSQL* it fails.

see reprex below with SQLite : 

``` r
library(RSQLite)
library(tidyverse)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang
#> Registered S3 method overwritten by 'rvest':
#>   method            from
#>   read_xml.response xml2
tbl1 <- tribble(
  ~A, ~B,
  1, 2,
  3, NA)
con <- dbConnect(SQLite(), ":memory:")

dbWriteTable(con, "tbl1", tbl1)
tbl(con, "tbl1")
#> # Source:   table<tbl1> [?? x 2]
#> # Database: sqlite 3.22.0 [:memory:]
#>       A     B
#>   <dbl> <dbl>
#> 1     1     2
#> 2     3    NA
# good
tbl1 %>% filter_all(~!is.na(.))
#> # A tibble: 1 x 2
#>       A     B
#>   <dbl> <dbl>
#> 1     1     2

# bad
tbl(con, "tbl1") %>%  filter_all(~!is.na(.)) %>% collect()
#> # A tibble: 0 x 2
#> # ... with 2 variables: A <dbl>, B <dbl>
tbl(con, "tbl1") %>%  filter_at(vars(A,B), ~!is.na(.)) %>% collect()
#> # A tibble: 0 x 2
#> # ... with 2 variables: A <dbl>, B <dbl>
```

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

And see below my output using a PostgreSQL db (reproducible if you change the connection) : 

``` r
library(RPostgres)
library(tidyverse)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang
#> Registered S3 method overwritten by 'rvest':
#>   method            from
#>   read_xml.response xml2
tbl2 <- tribble(
  ~A, ~B,
  1, 2,
  3, NA)

### CHANGE FOR REPRODUCIBILITY
library(adb)
con <- adb_con("sam1")
#########################

dbWriteTable(con, "tbl2", tbl2)
tbl(con, "tbl2") %>%  filter_all(~!is.na(.)) %>% collect()
#> Error in result_create(conn@ptr, statement): Failed to prepare query: ERROR:  argument of NOT must be type boolean, not type real
#> LINE 3: WHERE (NOT("A") AND NOT("B"))
#>                    ^
tbl(con, "tbl2") %>%  filter_at(vars(A,B), ~!is.na(.)) %>% collect()
#> Error in result_create(conn@ptr, statement): Failed to prepare query: ERROR:  argument of NOT must be type boolean, not type real
#> LINE 3: WHERE (NOT("A") AND NOT("B"))
#>                    ^
```

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by moodymudskipper** [comment]
I came up with the following workaround to get `filter_at`'s expected behavior :  

```
tbl(con, "tbl1") %>%  
  filter(!!!map(vars(A,B), ~ expr(!is.na(!!.)))) %>% 
  collect()
```

To simulate `filter_all` we can use : 

```
tbl(con, "tbl1") %>%  
  filter(!!!map(syms(colnames(.)), ~ expr(!is.na(!!.)))) %>% 
  collect()
```
