### ISSUE TITLE
n() ist translated into COUNT() without '*'

### ISSUE THREAD

**Issue by huelf** [tidyverse/dbplyr#314]
Hi,

I am connecting to an EXASOL database with a JDBC connection. (Drivers here: https://www.exasol.com/portal/display/DOWNLOAD/Version+6.0.5) 
Normal queries are no problem, but when I want to summarize and count the SQL ist not properly translated.

flight_db_group <- flights_db %>% 
  group_by(COLUMN1) %>% 
  summarize(CNT = n())

translates into

SELECT "COLUMN1", COUNT() AS "CNT"
FROM MY_SCHEMA.MY_TABLE
GROUP BY "COLUMN1"

which resolves to an (EXASOL) error:
Function COUNT should not be called with 0 arguments. Possible number of arguments: 1

I don't know if this is dbplyr's fault or maybe JDBC's but I thought I place it here.

Best Regards
Hans

```r
library(RJDBC)
library(dplyr)
library(dbplyr)

drv <- JDBC("com.exasol.jdbc.EXADriver",
            "H:/My Documents/exajdbc-6.0.5.jar",
            identifier.quote="\"")

con <- dbConnect(drv, "jdbc:exa:exasol-url.de", "myLogin", "myPassword")

flights_db <- tbl(con, in_schema('MY_SCHEMA', 'MY_TABLE'))

flight_db_group <- flights_db %>% 
  group_by(COLUMN1) %>% 
  summarize(CNT = n())

flight_db_group %>% show_query()

# SELECT "COLUMN1", COUNT() AS "CNT"
# FROM MY_SCHEMA.MY_TABLE
# GROUP BY "COLUMN1"

flight_db_group

# Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
#   Unable to retrieve JDBC result set for SELECT "COLUMN1", COUNT() AS "CNT"
#   FROM MY_SCHEMA.MY_TABLE
#   GROUP BY "COLUMN1"
#   LIMIT 11 (Function COUNT should not be called with 0 arguments. Possible 
#             number of arguments: 1 (Session: <session id>))

dbDisconnect(con)

sessionInfo()
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dbplyr_1.4.0  dplyr_0.8.1   RJDBC_0.2-7.1 rJava_0.9-11  DBI_1.0.0    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       fansi_0.4.0      zeallot_0.1.0    utf8_1.1.4       crayon_1.3.4    
 [6] assertthat_0.2.1 R6_2.4.0         backports_1.1.4  magrittr_1.5     pillar_1.4.1    
[11] cli_1.1.0        rlang_0.3.4      rstudioapi_0.10  vctrs_0.1.0      tools_3.5.1     
[16] glue_1.3.1       purrr_0.3.2      compiler_3.5.1   pkgconfig_2.0.2  tidyselect_0.2.5
[21] tibble_2.1.2

**Comment by hadley** [comment]
EXASOL is not currently officially supported by dbplyr, so unfortunately you can't expect all default translations to work.

**Comment by huelf** [comment]
Thanks for answering.
I mentioned this issue because I think that translating n() to COUNT() is wrong in any SQL dialect. 
Best Regards

**Comment by kondofersky** [comment]
I have exactly the same problems as @huelf . (Also with EXASOL connection by the way). Is there a way of changing the translation of n() to count(*) instead to count() ?

**Comment by hadley** [comment]
If the default translation fo `n()` is wrong, can you please open a new issue, and provide some evidence (e.g. find a link to something that describes the SQL spec)

**Comment by mkirzon** [comment]
We use RJDBC / JDBC Drivers with Denodo in our company and immediately ran into this same issue

**Comment by kondofersky** [comment]
It is not a jdbc problem. It also happens with odbc. But as you can see in the other post (https://github.com/tidyverse/dbplyr/issues/343), it is a planned bugfix (?) in the 2.0.0. version.
