### ISSUE TITLE
Hive native queries errors with select()/mutate()

### ISSUE THREAD

**Issue by martin-a-wade** [tidyverse/dbplyr#315]
Problem described here:
https://community.rstudio.com/t/dbplyr-issues-errors-with-hive-native-queries/32443

Hive native queries result in errors using dbplyr and select()/mutate(), but not with DBI.

The following is not directly reproducible, but hopefully it demonstrates the issues and errors in differt simple scenarios:
```r
suppressPackageStartupMessages(library(dplyr))  # 0.8.0.1
#> Warning: package 'dplyr' was built under R version 3.4.4
suppressPackageStartupMessages(library(dbplyr)) # 1.4.0

# odbc connection using native queries
con_native <- DBI::dbConnect(odbc::odbc(), "authentication")

# unsuccessful with DBI, but managed to upload copy of mtcars to Hive via:
# RODBC::sqlSave(con, mtcars, "container_name.tmp_mtcars", rownames = "car")

# container_name hidden
mtcars_native <- tbl(con_native, in_schema("container_name", "tmp_mtcars"))

# output is as expected with table name prefix for native queries
# `mpg` is recognised as column name even without table name prefix
mtcars_native %>% 
  filter(mpg > 30)
#> # Source:   lazy query [?? x 12]
#> # Database: Hive 1.1.0-cdh5.14.4[@Hive/HIVE]
#>   tmp_mtcars.car tmp_mtcars.mpg tmp_mtcars.cyl tmp_mtcars.disp
#>   <chr>                   <dbl>          <dbl>           <dbl>
#> 1 Fiat 128                 32.4              4            78.7
#> 2 Honda Civic              30.4              4            75.7
#> 3 Toyota Corolla           33.9              4            71.1
#> 4 Lotus Europa             30.4              4            95.1
#> # ... with 8 more variables: tmp_mtcars.hp <dbl>, tmp_mtcars.drat <dbl>,
#> #   tmp_mtcars.wt <dbl>, tmp_mtcars.qsec <dbl>, tmp_mtcars.vs <dbl>,
#> #   tmp_mtcars.am <dbl>, tmp_mtcars.gear <dbl>, tmp_mtcars.carb <dbl>

# same result (not run)
# head(DBI::dbGetQuery(con_native, "SELECT * FROM container_name.tmp_mtcars WHERE (`mpg` > 30.0)"))

# column names not recognised
mtcars_native %>% 
  select(car, mpg)
#> Error in .f(.x[[i]], ...): object 'car' not found

# output successful, but without table name prefix
head(DBI::dbGetQuery(con_native, "SELECT `car`, `mpg` FROM container_name.tmp_mtcars"))
#>             car  mpg
#> 1     Mazda RX4 21.0
#> 2 Mazda RX4 Wag 21.0
#> 3     Merc 280C 17.8
#> 4    Merc 450SE 16.4
#> 5    Merc 450SL 17.3
#> 6   Merc 450SLC 15.2

# same scenario with mutate (not run)
# mtcars_native %>% 
#   mutate(kpl = mpg * 0.425)

# output successful even with mutate, but without table name prefix
mtcars_native %>% 
  group_by(cyl) %>% 
  summarise(mpg_mean = mean(mpg, na.rm = TRUE)) %>% 
  mutate(kpl_mean = mpg_mean * 0.425)
#> # Source:   lazy query [?? x 3]
#> # Database: Hive 1.1.0-cdh5.14.4[@Hive/HIVE]
#>     cyl mpg_mean kpl_mean
#>   <dbl>    <dbl>    <dbl>
#> 1     4     26.7    11.3 
#> 2     6     19.7     8.39
#> 3     8     15.1     6.42

# same result (not run)
# head(DBI::dbGetQuery(con_native, "SELECT `cyl`, `mpg_mean`, `mpg_mean` * 0.425 AS `kpl_mean` FROM 
#                      (SELECT `cyl`, AVG(`mpg`) AS `mpg_mean` FROM container_name.tmp_mtcars GROUP BY `cyl`) `dbplyr_001`"))

DBI::dbDisconnect(con_native)
```

**Comment by hadley** [comment]
Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your code is currently a bit too complicated: there's quite a bit of extraneous stuff in there that doesn't seem directly related to the problem. Can you please try and simplify your example some more? The more minimal you can make the reprex, the faster I can identify the problem and fix it.

**Comment by martin-a-wade** [comment]
Thanks for the pointers.  It's my first post.

I have broken out the code into three related scenarios to demonstrate the inconsistencies between the dbplyr and DBI output.

I have used a copy of mtcars uploaded to a Hive database (named tmp_mtcars here) as an example.  The odbc connection uses Hive native queries.

Setup for each scenario:
``` r
suppressPackageStartupMessages(library(dplyr))  # 0.8.0.1
suppressPackageStartupMessages(library(dbplyr)) # 1.4.0

# odbc connection using native queries
con_native <- DBI::dbConnect(odbc::odbc(), "authentication")
# copy of mtcars uploaded to Hive database
mtcars_native <- tbl(con_native, in_schema("container_name", "tmp_mtcars"))
```

Scenario 1:
``` r
mtcars_native %>% filter(mpg > 30)
#> # Source:   lazy query [?? x 12]
#> # Database: Hive 1.1.0-cdh5.14.4[@Hive/HIVE]
#>   tmp_mtcars.car tmp_mtcars.mpg tmp_mtcars.cyl tmp_mtcars.disp
#>   <chr>                   <dbl>          <dbl>           <dbl>
#> 1 Fiat 128                 32.4              4            78.7
#> 2 Honda Civic              30.4              4            75.7
#> 3 Toyota Corolla           33.9              4            71.1
#> 4 Lotus Europa             30.4              4            95.1
#> # ... with 8 more variables: tmp_mtcars.hp <dbl>, tmp_mtcars.drat <dbl>,
#> #   tmp_mtcars.wt <dbl>, tmp_mtcars.qsec <dbl>, tmp_mtcars.vs <dbl>,
#> #   tmp_mtcars.am <dbl>, tmp_mtcars.gear <dbl>, tmp_mtcars.carb <dbl>

# same result (not run)
# head(DBI::dbGetQuery(con_native, "SELECT * FROM container_name.tmp_mtcars WHERE (`mpg` > 30.0)"))
```
Output is successful.  The column names are of the form tablename.columnname.

Scenario 2:
``` r
mtcars_native %>% select(car, mpg)
#> Error in .f(.x[[i]], ...): object 'car' not found

head(DBI::dbGetQuery(con_native, "SELECT `car`, `mpg` FROM haasbap0744_14730.tmp_mtcars"))
#>             car  mpg
#> 1     Mazda RX4 21.0
#> 2 Mazda RX4 Wag 21.0
#> 3     Merc 280C 17.8
#> 4    Merc 450SE 16.4
#> 5    Merc 450SL 17.3
#> 6   Merc 450SLC 15.2
```
dbplyr fails.  DBI produces the correct result and also does so without the tablename.columnname format from Scenario 1.

Scenario 3:
``` r
mtcars_native %>% 
  group_by(cyl) %>% 
  summarise(mpg_mean = mean(mpg, na.rm = TRUE)) %>% 
  mutate(kpl_mean = mpg_mean * 0.425)
#> # Source:   lazy query [?? x 3]
#> # Database: Hive 1.1.0-cdh5.14.4[@Hive/HIVE]
#>     cyl mpg_mean kpl_mean
#>   <dbl>    <dbl>    <dbl>
#> 1     4     26.7    11.3 
#> 2     6     19.7     8.39
#> 3     8     15.1     6.42

# same result (not run)
# head(DBI::dbGetQuery(con_native, "SELECT `cyl`, `mpg_mean`, `mpg_mean` * 0.425 AS `kpl_mean` FROM 
#                      (SELECT `cyl`, AVG(`mpg`) AS `mpg_mean` FROM container_name.tmp_mtcars GROUP BY `cyl`) `dbplyr_001`"))
```
Output is successful despite using mutate() which failed for dbplyr in Scenario 2.

**Comment by hadley** [comment]
Can you please make it even simpler? Showing me SQL that works isn't terribly useful in terms of figuring out what the problem with dbplyr is.

**Comment by martin-a-wade** [comment]
Sorry, I'm not really sure how I can simplify it further.  Three scenarios have been included to demonstrate the differing behaviours of dbplyr compared to DBI.
- Scenario 1 result returns column names of a different format (both dbplyr and DBI)
- Scenario 2 has the dbplyr error.
- Scenario 3 was included because dbplyr works despite using very similar syntax to Scenario 2.

**Comment by Voltemand** [comment]
Hi @martin-a-wade, 

Just stumbled on this issue while I was taking a look at dbplyr and though I might be able to help. 

A reprex for a issue you have with a package usually has two components:

1. A (minimal) snippet of (preferably runnable) code which produces the incorrect behaviour
2. A short description of what exactly you think is incorrect about the behaviour/ what you would expect to happen instead. 

In a lot of cases what is wrong is obvious and the description can be brief, but if the snippet is only producing output you don't expect (and not, say, unexpectedly erroring) then it very important to include it. 

So my advice would be to isolate the code that is producing the behaviour you don't expect and outline clearly what is unexpected about that behaviour. Include this (and really only this) in the reprex.

Your first issue includes a lot of detail which is great - but the detail does, I think, get in the way of seeing what the actual error you are having is which is what @hadley needs to do to fix it. 

Happy issue submitting and all the best!
