### ISSUE TITLE
MSSQL regression in boolean/bit coercion

### ISSUE THREAD

**Issue by EarlGlynn** [tidyverse/dbplyr#318]
On R Studio Pro Server, this MS SQL query worked fine in R 3.4.2 and R.3.5.0 but fails in R 3.5.1 and R 3.6.0. [Part of a much larger query originally.]

```{r}
ageIntervals <-
  fEncounter   %>%  
  head(10)  %>%
  summarize(n90plus = sum(as.integer(AGE_IN_YEARS >= 90), na.rm=TRUE))   %>%
  collect()
```

R 3.4.2 and 3.5.0 give this for `show_query` (everything worked fine)
sessionInfo:  dbplyr_1.2.2     odbc_1.1.6       DBI_1.0.0

```
<SQL>
SELECT SUM(CAST(CONVERT(BIT, IIF("AGE_IN_YEARS" >= 90.0, 1.0, 0.0)) AS INT)) AS "n90plus"
FROM (SELECT  TOP 10 *
FROM XXXXXXX.XX_X_ENCOUNTER) "uyzjpitrzg"
```

R 3.5.1 and R 3.6.0 show this for `show_query` and fails:
sessionInfo:  dbplyr_1.4.0     odbc_1.1.6       DBI_1.0.0

```
<SQL>
SELECT SUM(CAST("AGE_IN_YEARS" >= 90.0 AS INT)) AS "n90plus"
FROM (SELECT TOP(10) *
FROM XXXXXXX.XX_X_ENCOUNTER) "dbplyr_002"
```

The failure message:

```
Error: <SQL> 'SELECT SUM(CAST("AGE_IN_YEARS" >= 90.0 AS INT)) AS "n90plus" FROM (SELECT TOP(10) * FROM XXXXXXX.XX_X_ENCOUNTER) "dbplyr_001"' nanodbc/nanodbc.cpp:1587: 42000: [Microsoft][ODBC Driver 17 for SQL Server][SQL
17.	stop(structure(list(message = "<SQL> 'SELECT SUM(CAST(\"AGE_IN_YEARS\" >= 90.0 AS INT)) AS \"n90plus
```
Both examples run on the same R Studio Pro server with the specified versions of R.  

Both examples run with exact same database and same DB version:  Microsoft SQL Server Version: 12.00.2000.  The database is on Azure and I must specify the driver "ODBC Driver 17 for SQL Server".

**Comment by hadley** [comment]
I don't think this is related to R versions, but different versions of dbplyr. 

Here's a minimal reprex for the problem:

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

lazy_frame(AGE_IN_YEARS = 10, con = simulate_mssql()) %>% 
  head(10)  %>%
  summarize(n90plus = sum(as.integer(AGE_IN_YEARS >= 90), na.rm = TRUE))
#> <SQL>
#> SELECT SUM(CAST(`AGE_IN_YEARS` >= 90.0 AS INT)) AS `n90plus`
#> FROM (SELECT TOP(10) *
#> FROM `df`) `dbplyr_001`
```

<sup>Created on 2019-06-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment]
@edgararuiz could you take a look?

**Comment by ianmcook** [comment]
Looks like this is related to the removal of `mssql_logical_infix()` in https://github.com/tidyverse/dbplyr/pull/103. In dbplyr 1.2.2, `>=` translated to `mssql_logical_infix(">=")` but it now translates to `sql_infix(">=")`.

**Comment by hadley** [comment]
@ianmcook thanks! Do you use dbplyr with SQL server much?

**Comment by ianmcook** [comment]
@hadley I have in the past, but I'm not these days
