### ISSUE TITLE
dbplyr - Oracle - 

### ISSUE THREAD

**Issue by stvrd** [tidyverse/dbplyr#319]
Thank you so much for developing `dbplyr` - it is awesome to use `dplyr` directly on databases.

I am working with `dbplyr` on a connection created with `ROracle` (not using `odbc` because of [this](https://github.com/r-dbi/odbc/issues/206) unfortunate issue).

I create a table with   `akv <- tbl(con, in_schema("myschema","BILAN"))`   and can access the data.

The functions `group_by()`, `summarise()`, `n()`, `is.na()` work perfectly well. However, `mutate()` returns an Error:
```
> akv %>% filter(DATBILAN==201905) %>% select(DATBILAN, RENTE) %>%  mutate(R1 = RENTE>0)  
Error in .oci.SendQuery(conn, statement, data = data, prefetch = prefetch,  : 
  ORA-00923: FROM keyword not found where expected
```

The SQL query behind this is:

```
> show_query({  akv %>% filter(DATBILAN==201905) %>% select(DATBILAN, RENTE) %>%  mutate(R1 = RENTE>0)   })
<SQL>
SELECT "DATBILAN", "RENTE", "RENTE" > 0.0 AS "R1"
FROM (AOO_AKV.T_AKV_PREST_BILAN) 
WHERE ("DATBILAN" = 201905.0)

```
whereas it should be something like this:

```
SELECT DATBILAN, RENTE, CASE WHEN RENTE > 0.0 THEN 1 ELSE 0 END
FROM AOO_AKV.T_AKV_PREST_BILAN 
WHERE DATBILAN = 201905
```

(which works with `dbGetQuery()`)

Hope you can include this in the next version :)

**Comment by alexfun** [comment]
Try:

```
akv %>% 
     filter(DATBILAN==201905) %>% 
     select(DATBILAN, RENTE) %>% 
     mutate(R1 = if_else(RENTE > 0, 1, 0))
````

**Comment by NZambranoc** [comment]
![image](https://user-images.githubusercontent.com/17186026/179602627-2f51cc6e-b9e7-4c54-a911-6ebe1fffcc31.png)

**Comment by NZambranoc** [comment]
This is still an issue with Oracle SQL since it doesn't allow bare asterisks when there other columns explicitly on the select clause.
