### ISSUE TITLE
TOP 100 PERCENT is issued for MSSQL in absence of ORDER BY, breaking support for Azure DW

### ISSUE THREAD

**Issue by alexkyllo** [tidyverse/dbplyr#337]
PR #277 causes the mssql backend to issue `SELECT TOP 100 PERCENT` in sub queries even if there is no `ORDER BY` clause. This breaks dbplyr for Azure Data Warehouse, which is a version of MSSQL that does not support `SELECT [...] PERCENT` syntax. I'm working on a PR to change this so that `TOP 100 PERCENT` at least only gets issued if there is actually an `ORDER BY`, so that ADW users can use dbplyr again.

```r
mf <- lazy_frame(x = 1:3, con = simulate_mssql())
mf %>% mutate(x = -x) %>% mutate(x = -x) %>% sql_render()
#> <SQL> SELECT -`x` AS `x`
#> FROM (SELECT TOP 100 PERCENT -`x` AS `x`
#> FROM `df`) `dbplyr_001`
```

**Comment by filipwastberg** [comment]
#277 also breaks code for Parallell Data Warehouse for MSSQL which doesn't support TOP ... PERCENT

**Comment by filipwastberg** [comment]
We hade to roll back to `dbplyr` `1.4.0` to be able to use `dplyr` with our database. 

If anyone wonder how: `devtools::install_version("dbplyr", version = "1.4.0", repos = "http://cran.us.r-project.org")`
