### ISSUE TITLE
Default way of translating n() to sql code should be count(*) and not count()

### ISSUE THREAD

**Issue by kondofersky** [tidyverse/dbplyr#343]
Problem is described in the closed [issue 314](https://github.com/tidyverse/dbplyr/issues/314) . 

Particularly obvious if one tries to use e.g. the corrr:::correlate() function, where obviously n() is needed to calculate the number of rows. The error message provided says that the count function requires 1 argument but 0 are provided. I tested the count() vs. count(*) on [sqlfiddle](http://sqlfiddle.com) and the version without * did not work for any of the possible examples, including versions of PostgreSQL, MySQL, Oracle, SQLite. I actually do not know a single sql language where this meight work (although I am not very experienced tbh).

Workaround is described by @hadley [here](https://github.com/tidyverse/dplyr/issues/2720) but I think changing the translation to count(*) is the proper way of dealing with this.

**Comment by hadley** [comment]
My copy of "SQL-99 complete, really" states that there are two forms for `COUNT()`: `COUNT(*)` and `COUNT(<column expression>)`. Not sure how I managed to create a default translation that doesn't work anywhere!

**Comment by kondofersky** [comment]
Well, I am not sure if you are being sarcastic here but for what it’s worth, I really tried the count function without an argument in all of the provided languages and it did not work. I also asked more experienced SQL users (sample size = 3) but they all said that they always use count(*). 

I would also provide a solution myself if you hint me where the translation of n() actually happens. Yesterday, I tried to dig deep and was at some point looking into the C code of eval_tidy from the rlang package. Not sure if this is the right path though...

**Comment by hadley** [comment]
The implementation is at https://github.com/tidyverse/dbplyr/blob/master/R/backend-.R#L292, but once you've fixed it in the base implementation, you'll also need to look through the other backends and remove their custom `n()` translations (since they'll no longer be needed).
