### ISSUE TITLE
small correction for db_drop_table()

### ISSUE THREAD

**Issue by fahadshery** [tidyverse/dbplyr#353]
getting error when running:
```r
db_drop_table(con =db_pool, table = in_schema("my_schema","my_table"))
Error: `con` must not be NULL
```

After debugging. It seems that it is failing at:

```r
 else {
    sql <- build_sql("DROP TABLE ", ident(table))
  }
```

However, it works if we do:
```r
 else {
    sql <- build_sql("DROP TABLE ", ident(table),con=con)
  }
```

Thought its a quick fix so sharing it with you

**Comment by hadley** [comment]
In `db_drop_table.Oracle` (it would've been a quicker fix if you'd mentioned that you were using Oracle)
