### ISSUE TITLE
Money data in PostgreSQL gets converted to all 0s

### ISSUE THREAD

**Issue by trevorcampbell** [tidyverse/dbplyr#355]
It seems that columns in a postgresql database with the "money" datatype get converted to all 0s silently by dbplyr. For example, if I run code like (apologies in advance: I can't include the specific database info in the minimal example!):

```r
library(RPostgres)
library(dbplyr)
library(DBI)
con <- dbConnect(RPostgres::Postgres(), [database info here])
select(tbl(con, 'my_table'), 'my_money_column')
```

the output looks like
```

my_money_column
--

0
0
0
0
0
0
0
0
0
0
0

```

But if I send a raw SQL command that tells the database to first convert from money to numeric, I get the expected result:

```r
library(RPostgres)
library(dbplyr)
library(DBI)
con <- dbConnect(RPostgres::Postgres(), [database info here])
res <- dbSendQuery(con, "SELECT my_money_column::numeric FROM my_table")
dbFetch(res)
dbClearResult(res)
```
the output looks like
```

my_money_column
--

3887.00
0.00
36.00
1130.00
1384.00
0.00
11149.00
0.00
406.00
1231.00
0.00
8385.00
1289.00
130.00

```

I'm not 100% certain this is an issue with dbplyr (might be RPostgres itself) --- but since a different SQL command works I figured at a minimum it may be solvable through a modification to dbplyr.

Thanks!

**Comment by hadley** [comment]
Could you please create a reprex? You can assume I have a postgres database available, but I don't have any tables containing "money", so could you please create with some SQL?

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
