### ISSUE TITLE
sampling for modelling oracle

### ISSUE THREAD

**Issue by fahadshery** [tidyverse/dbplyr#358]
There is a Limit on `number of expressions in a list` in `oracle`. `1000` to be specific.

There is a work around [here](https://stackoverflow.com/questions/17842453/is-there-a-workaround-for-ora-01795-maximum-number-of-expressions-in-a-list-is).

I am trying to get samples more than 1000 to build a `parsnip` model and running `predictions` in the database.

the example in @edgararuiz webinar for getting 10,000 records using random sampling doesn't work for `oracle`.

I am having to clean the SQL and executing it via `dbGetQuery()` for now.

thanks

**Comment by hadley** [comment]
This doesn't seem like a dbplyr problem? At least you haven't included any dbplyr code.
