### ISSUE TITLE
Gupta ODBC driver

### ISSUE THREAD

**Issue by tvedebrink** [tidyverse/dbplyr#360]
When I use `tbl(con, "SOME TABLE")` I get the error:
`nanodbc/nanodbc.cpp:1344: HY000: [Gupta][ODBC Driver][SQLBase]00901 PRS CNE Command not properly ended`
This seem to match some related Oracle issues, but I can't see how to use those fixes with my issue. BTW: I have not chosen the Gupta platform - I'm just a user..

**Comment by hadley** [comment]
This is probably because Gupta is not supported by dbplyr.
