### ISSUE TITLE
str_replace_all mimics str_replace

### ISSUE THREAD

**Issue by shosaco** [tidyverse/dbplyr#362]
The current implementation of `str_replace_all` which was introduced in PR #131 for postgres backends has no global parameter, thus replacing only the first occurence of any match in a string:

File R/backend-postgres.R, line 58ff:

```r
str_replace_all = function(string, pattern, replacement){
        sql_expr(regexp_replace(!!string, !!pattern, !!replacement))
      }
```

To my mind, the correct implementation would be
```r
str_replace_all = function(string, pattern, replacement){
        sql_expr(regexp_replace(!!string, !!pattern, !!replacement, 'g'))
    }
```

Also, the fix of str_detect has disappeared from master and it is not possible to grep for regular expressions on Postgres databases at the moment: Line 55 in beforementioned file quotes

```r
      str_detect  = function(string, pattern) {
        sql_expr(strpos(!!string, !!pattern) > 0L)
      }
```

instead of the line that was implemented Pull request #131:

```r
str_detect = sql_infix("~"),
```

Thanks for the great effort and package!
sandro

**Comment by hadley** [comment]
Would you be interested in doing a PR?

**Comment by shosaco** [comment]
> 
> 
> Would you be interested in doing a PR?

Created PR #392 

best regards,
sandro
