### ISSUE TITLE
Surprisingly case-sensitive name lookup behavior

### ISSUE THREAD

**Issue by lukerobert** [tidyverse/dbplyr#364]
Perhaps this is intended behavior but I found it unintuitive. When using remote tbls with uppercase column names I frequently refer to the columns by their lowercase name so I don't feel like I'm yelling at my computer. However, this doesn't work if the lowercase name has a direct match in the local environment. It seems like the name lookup behavior is:

1. Look for a case-sensitive match in the remote tbl
2. Look for a case-sensitive match in the local env
3. Look for a case-insensitive match in the remote tbl

I personally expected it to do both types of lookups in the remote tbl before checking the local environment. Is this intended?

reprex:
```r
library(dplyr)
library(dbplyr)

# SQL is not case sensitive, so this will work
memdb_frame(FOO = 1:10) %>% summarize(n_distinct(foo))
#> # Source:   lazy query [?? x 1]
#> # Database: sqlite 3.29.0 [:memory:]
#>   `n_distinct(foo)`
#>               <int>
#> 1                10

# However, it _won't_ work if the lowercase name matches something in
# the local environment, like if it matches a dplyr function that also happens
# to be a common column name.
memdb_frame(ID = 1:10) %>% summarize(n_distinct(id))
#> Error in UseMethod("escape"): no applicable method for 'escape' applied to an object of class "function"
```

**Comment by hadley** [comment]
R is case sensitive so that’s the semantics that dbplyr follows, the challenge being that untranslated expressions are left as is.

**Comment by lukerobert** [comment]
Makes sense. Thanks for taking a look!
