### ISSUE TITLE
Quote identifier discrepancy between simulated postgres and dbi driver

### ISSUE THREAD

**Issue by stiberger** [tidyverse/dbplyr#365]
I have a problem where dbplyr translate_sql() function with simulated postgres driver, produces SQL which is not compatible with Postgres.

Specifically - identifiers are quoted with back-ticks, whereas expected would be double quotes.

Expected behavior occur when translate_sql() is given a DBI connection with RPostgreSQL driver.

```r
# reprex
pgcon <- DBI::dbConnect(
  drv      = RPostgreSQL::PostgreSQL(),
  host     = "host",
  dbname   = "dbname",
  user     = "user",
  password = "password",
  port     = 5432
)
dbplyr::translate_sql(x == 1, con = dbplyr::simulate_postgres())
# <SQL> `x` = 1.0 -- Invalid postgres SQL
dbplyr::translate_sql(x == 1, con = pgcon)
# <SQL> "x" = 1.0 -- Valid postgres SQL
DBI::dbDisconnect(pgcon)
```

```r
# environment
packageVersion("dbplyr") # 1.4.2
packageVersion("DBI") # 1.0.0
packageVersion("RPostgreSQL") # 0.6.2
sessionInfo()
# R version 3.6.1 (2019-07-05)
# Platform: x86_64-suse-linux-gnu (64-bit)
# Running under: openSUSE Tumbleweed
```

The start of my rabbit hole was [tidypredict](https://github.com/tidymodels/tidypredict) giving me invalid Postgres SQL, given simulated dbplyr driver.

Am I missing something? Because some digging in [test cases](https://github.com/tidyverse/dbplyr/blob/b7fdb56af3fac4d3ce9c0b835fbcff76400bfaf5/tests/testthat/test-backend-postgres.R) shows this to be expected.

**Comment by hadley** [comment]
The simulation is imperfect, unfortunately. It would be quite a lot of work to fix it, and it's already documented:

>  Simulated SQL always quotes identifies with `` `x` ``, and strings with `'x'`.
