### ISSUE TITLE
How to access tables with unsupported column types?

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dbplyr#369]
There are scenarios where `tbl(src, "table_name") %>% select(...)` doesn't work because enumerating the columns after `tbl()` fails. This can happen if the table contains columns not supported by the DBI backend. The workaround

```r
tbl(src, sql("SELECT col1, col2, ... FROM table_name"))
```

is clumsy.

Perhaps we can add a `select` argument to `tbl.src_dbi()` with tidyselect semantics?

**Comment by hadley** [comment]
This feels a bit too specialised to me; I don't like the idea of exposing multiple ways of selecting columns.
