### ISSUE TITLE
add SQL translation for weighted.mean

### ISSUE THREAD

**Issue by saadaslam** [tidyverse/dbplyr#376]
I often encounter the need to perform weighted average calculations. R has a neat functionality to perform this with `weighted.mean`. It's even more useful when there are missing values, in which I can provide `na.rm = TRUE`. 

I think it's worthwhile providing a `weighted.mean` translation for dbplyr. Mainly because, the method in which we produce weighted average calculations is verbose:

```r
library(tidyverse)
library(babynames)
library(dbplyr)
baby_db <- tbl_memdb(babynames)

## R and dplyr
babynames %>% 
  summarize(wavg_prop = weighted.mean(prop, n))
## dbplyr
baby_db %>% 
  summarize(wavg_prop = sum(prop * n) / sum(n))
```
This becomes a little more verbose and repetitive when missing values are apparent:

```r
set.seed(1337)
babynames_missing <- babynames
babynames_missing[sample(1:nrow(babynames), 1e5, replace = F), "prop"] <- NA
baby_missing_db <- tbl_memdb(babynames_missing)

babynames_missing %>% 
  summarize(wavg_prop = weighted.mean(prop, n, na.rm = TRUE))
baby_missing_db %>% 
  summarize(
    wavg_prop = sum(prop * n) / sum(if_else(! is.na(prop), n, 0)),
    wavg_prop2 = sum(prop * n) / sum(n)
  )
```

Note the difference in between `wavg_prop` and `wavg_prop2` when missing values are apparent. 

I wrote code in `backend-.R` to supply a translator. If you think it's worthwhile, I can add that on for a pull request.

**Comment by AdeelK93** [comment]
This is great stuff! Would love to see it in dbplyr

**Comment by hadley** [comment]
A PR would be great! 

I think you also need to check that `n` isn't missing?

**Comment by saadaslam** [comment]
Yes, I would need to add a condition for the weighting variable to be missing, as well. Thanks for pointing it out.

**Comment by ahcyip** [comment]
I'm getting "operator does not exist" "no operator matches given name and argument types" when I try to do the manual weighted average as above. `show_query` seems to produce the right query, but `collect` fails.

Comparing to `baby_db %>% summarize(wavg_prop = sum(prop * n) / sum(n))`, I see that my names are all quoted with " - could that be causing a problem?

I've posted on StackOverflow to see if anyone else can help: https://stackoverflow.com/questions/65545756/r-dbplyr-translation-produces-operator-does-not-exist-error

```
> query_polk_fe %>% show_query()
<SQL>
SELECT "STATE", "COUNTY", "YEAR MODEL", "FUEL TYPE", "REGISTRATION TYPE", "SEGMENT", SUM("VIO" * "EPA MILEAGE COMBINED") / SUM("VIO") AS "WMPG_EPA", SUM("VIO" / "EPA MILEAGE COMBINED") / SUM("VIO") AS "WGPM_EPA", SUM("VIO") AS "VIO"
FROM polk.polk18
GROUP BY "STATE", "COUNTY", "YEAR MODEL", "FUEL TYPE", "REGISTRATION TYPE", "SEGMENT"
> polk_fe <- query_polk_fe %>% collect()
Error: Failed to prepare query: ERROR:  operator does not exist: smallint * character varying
LINE 1: ... TYPE", "REGISTRATION TYPE", "SEGMENT", SUM("VIO" * "EPA MIL...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by ahcyip** [comment]
never mind - StackOverflow helped resolve this for me!

**Comment by ahcyip** [comment]
Just a note, if this were to be implemented in the future, summed weights of zero will also cause failure (specially handled in `weighted.mean`)
```
Error: Failed to fetch row: ERROR:  division by zero
CONTEXT:  parallel worker
```

**Comment by GitHunter0** [comment]
Is there a manual workaround to achieve the same result as `weighted.mean`?

**Comment by hadley** [comment]
@GitHunter0 `weighted.mean(x, w)` is the same as `sum(x * w) / sum(w)`.

**Comment by GitHunter0** [comment]
@hadley , yes, my concern is dealing with missing values, but the comment above indicates a way, thank you.
