### ISSUE TITLE
Code of Conduct link in README.md  is not working for dbplyr

### ISSUE THREAD

**Issue by hannes101** [tidyverse/dbplyr#400]
In the README.md there is a link at the end to the Code of Conduct for the package. In case of dbplyr this link is not working, since the webpage https://dbplyr.tidyverse.org/CODE_OF_CONDUCT.html does not exist.
I guess it should link to a similar page like this:
https://dplyr.tidyverse.org/CODE_OF_CONDUCT

Should be easy to fix.

**Comment by hadley** [comment]
It looks like this is work on the dev version of the site (https://dbplyr.tidyverse.org/dev/CODE_OF_CONDUCT), so it'll be fixed automatically when we next update the main site.
