### ISSUE TITLE
vctrs support for "sql"

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/dbplyr#403]
This comes up in the revdep checks of dplyr 1.0.0, breaking package `geospark`

``` r
library(dbplyr, warn.conflicts = FALSE)
library(vctrs)

x <- sql("")
vec_c(x)
#> Error: Can't cast <sql> to <sql>.
chops <- vec_chop(x, list(1L))
vec_unchop(chops, list(1L))
#> Error: Can't cast <sql> to <sql>.
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Thanks to changes in vctrs, I now see:

``` r
library(dbplyr)
vctrs::vec_c(sql("a"), sql("b"))
#> <SQL> a
#> <SQL> b
```

<sup>Created on 2020-04-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
