### ISSUE TITLE
Make .keep_all = TRUE available in distinct() while using dbplyr

### ISSUE THREAD

**Issue by ftoresh** [tidyverse/dbplyr#404]
When applying distinct() using dbplyr there is no way to apply **.keep_all = TRUE**

**Comment by PauloJhonny** [comment]
@ftoresh I’ve been struggling with this one as well. And it would be really great if this feature was implemented.

What I’m doing for the time being is grouping the variables I want to keep in the data frame `dplyr::group_by(x, ...)` and then using `dplyr::summarise_all(min)` function.

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

There's some specific advice on creating a dbplyr reprex at https://dbplyr.tidyverse.org/articles/reprex.html

**Comment by ftoresh** [comment]
> Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)!
> 
> There's some specific advice on creating a dbplyr reprex at https://dbplyr.tidyverse.org/articles/reprex.html



**This is the reprex**


library(dplyr, quietly = TRUE)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

dataset <- dbplyr::memdb_frame(category = c("a", "a", "b", "b", "b"), 
                       total.today = 1:5, 
                       total.week = 10)

dataset %>% 
  group_by(category) %>% 
  # I don't use summarise() because it would take out total.week
  mutate(total.today.per.category = sum(total.today, na.rm = TRUE)) %>% 
  distinct(category, .keep_all = TRUE)
#> Error: Can only find distinct value of specified columns if .keep_all is FALSE

**Comment by ftoresh** [comment]
> Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)!
> 
> There's some specific advice on creating a dbplyr reprex at https://dbplyr.tidyverse.org/articles/reprex.html

**Reprex**


library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

dataset <- dbplyr::memdb_frame(category = c("a", "a", "b", "b", "b"), 
                       total.today = 1:5, 
                       total.week = 10)

dataset %>% 
  group_by(category) %>% 
  mutate(total.today.per.category = sum(total.today, na.rm = TRUE)) %>% 
  distinct(category, .keep_all = TRUE)
#> Error: Can only find distinct value of specified columns if .keep_all is FALSE

**Comment by hadley** [comment]
GitHub issues use [markdown](https://guides.github.com/features/mastering-markdown/) and they're much easier to read if you learn a little bit about it. The most important thing is to put your R code inside a block that starts with ```` ```R ```` and ends with ```` ``` ````. I've done that for you here, but I'd really appreciate it if you would format it yourself in the future.

**Comment by hadley** [comment]
Somewhat more minimal reprex:

``` r
library(dplyr, warn.conflicts = FALSE)
df <- dbplyr::memdb_frame(x = 1, y = 2)

df %>% distinct(x, .keep_all = TRUE)
#> Error: Can only find distinct value of specified columns if .keep_all is FALSE
df %>% collect() %>% distinct(x, .keep_all = TRUE)
#> # A tibble: 1 x 2
#>       x     y
#>   <dbl> <dbl>
#> 1     1     2
```

<sup>Created on 2020-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ftoresh** [comment]
@Hadley thanks for the advice. 

I'm dealing with hundreds of millions of data points, therefore collect() is not an option at the moment I want to apply the distinct(.keep_all = TRUE). An incredible feature would be to be able to do it before collecting the data :)

**Comment by ftoresh** [comment]
> @ftoresh I’ve been struggling with this one as well. And it would be really great if this feature was implemented.
> 
> What I’m doing for the time being is grouping the variables I want to keep in the data frame `dplyr::group_by(x, ...)` and then using `dplyr::summarise_all(min)` function.

could you please provide a simple reprex to this. I don't quite understand your approach to it. 

thanks!

**Comment by PauloJhonny** [comment]
Hi, @ftoresh. I can't say if my approach works in all cases, but it worked in my case and in your example.

Actually, in your example, you don't need to group all columns you want to keep in the data frame. You just need to group by column `category`, create the new column `total.today.per.category` and then summarise all columns using min.

``` r
library(dplyr, warn.conflicts = FALSE)

# database query
dataset <- dbplyr::memdb_frame(category = c("a", "a", "b", "b", "b"), 
                               total.today = 1:5, 
                               total.week = 10)

dataset %>% 
  dplyr::group_by(category) %>% 
  dplyr::mutate(total.today.per.category = sum(total.today, na.rm = TRUE)) %>%
  dplyr::summarise_all(min)
#> # Source:   lazy query [?? x 4]
#> # Database: sqlite 3.30.1 [:memory:]
#>   category total.today total.week total.today.per.category
#>   <chr>          <int>      <dbl>                    <int>
#> 1 a                  1         10                        3
#> 2 b                  3         10                       12

# dataframe query with distinct and .keep_all = TRUE in order to show the results are the same
dataset1 <- data.frame(category = c("a", "a", "b", "b", "b"), 
                       total.today = 1:5, 
                       total.week = 10)

dataset1 %>% 
  dplyr::group_by(category) %>% 
  dplyr::mutate(total.today.per.category = sum(total.today, na.rm = TRUE)) %>%
  dplyr::distinct(category, .keep_all = TRUE)
#> # A tibble: 2 x 4
#> # Groups:   category [2]
#>   category total.today total.week total.today.per.category
#>   <fct>          <int>      <dbl>                    <int>
#> 1 a                  1         10                        3
#> 2 b                  3         10                       12
```

<sup>Created on 2020-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I hope it helps you!

**Comment by ftoresh** [comment]
> Hi, @ftoresh. I can't say if my approach works in all cases, but it worked in my case and in your example.
> 
> Actually, in your example, you don't need to group all columns you want to keep in the data frame. You just need to group by column `category`, create the new column `total.today.per.category` and then summarise all columns using min.
> 
> ```r
> library(dplyr, warn.conflicts = FALSE)
> 
> # database query
> dataset <- dbplyr::memdb_frame(category = c("a", "a", "b", "b", "b"), 
>                                total.today = 1:5, 
>                                total.week = 10)
> 
> dataset %>% 
>   dplyr::group_by(category) %>% 
>   dplyr::mutate(total.today.per.category = sum(total.today, na.rm = TRUE)) %>%
>   dplyr::summarise_all(min)
> #> # Source:   lazy query [?? x 4]
> #> # Database: sqlite 3.30.1 [:memory:]
> #>   category total.today total.week total.today.per.category
> #>   <chr>          <int>      <dbl>                    <int>
> #> 1 a                  1         10                        3
> #> 2 b                  3         10                       12
> 
> # dataframe query with distinct and .keep_all = TRUE in order to show the results are the same
> dataset1 <- data.frame(category = c("a", "a", "b", "b", "b"), 
>                        total.today = 1:5, 
>                        total.week = 10)
> 
> dataset1 %>% 
>   dplyr::group_by(category) %>% 
>   dplyr::mutate(total.today.per.category = sum(total.today, na.rm = TRUE)) %>%
>   dplyr::distinct(category, .keep_all = TRUE)
> #> # A tibble: 2 x 4
> #> # Groups:   category [2]
> #>   category total.today total.week total.today.per.category
> #>   <fct>          <int>      <dbl>                    <int>
> #> 1 a                  1         10                        3
> #> 2 b                  3         10                       12
> ```
> 
> Created on 2020-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)
> 
> I hope it helps you!

@PauloJhonny looks like a smart approach. Thanks for the solution!

**Comment by Tazinho** [comment]
Can this please be reopened. I am needing this feature (or an implementation of `duplicated()`) and it seems to me that grouping is a rather expensive alternative!?

**Comment by ftoresh** [comment]
@Tazinho I don't know if this will help in your case, but if your intention is to eliminate duplicated rows if you apply distinct() with no variable inside, it should leave unique rows even if reading a database

dataset %>% distinct()

**Comment by Tazinho** [comment]
My usecase is 

```r
df <- tibble(a = c(1,1,2,2),
             b = c(1,2,2,1))
df %>% 
  arrange(b) %>%
  distinct(a, .keep_all = TRUE)
```

This works well, because distinct returns the first unique match. (Basically this resembles [ + duplicated). However, just distinct alone doesn’t help here. For now I live with the group_by approach, but it’s much slower than duplicated.

**Comment by hadley** [comment]
Please open a new issue with the minimal reprex above, and suggest what SQL you think dbplyr should generate for this case.
