### ISSUE TITLE
Translate str_detect() to REGEXP_INSTR instead of STRPOS for Redshift

### ISSUE THREAD

**Issue by kmishra9** [tidyverse/dbplyr#409]
Problem: Similar issue to #168, `str_detect` translates to a Redshift function ([`STRPOS`](https://docs.aws.amazon.com/redshift/latest/dg/r_STRPOS.html)) that doesn't appear to be able to work with regex strings. In contrast, the Redshift function [`REGEXP_INSTR`](https://docs.aws.amazon.com/redshift/latest/dg/REGEXP_INSTR.html) seems to have the same sort of regex functionality as `str_detect`.

There is a relevant discussion about Redshift's lack of support for "E strings" constructs from PostgresSQL that appears to have reached resolution [here](https://github.com/npgsql/npgsql/issues/515) as well, if that's helpful. 

```r
# Check if there are two periods in result_txt
> df %>% filter(str_detect(result_txt, "\\..*\\.")) %>% show_query()
<SQL>
SELECT *
FROM <dbpath>
WHERE (STRPOS("result_txt",  E'\\..*\\.') > 0)
```
Fails with error `Error: Failed to prepare query: ERROR:  type "e" does not exist` on an actual Redshift table

Writing it manually using `sql()` (after navigating a few gotchas -- hooray for quadruple backslashes) worked as expected:
```r
> df %>% filter(sql("REGEXP_INSTR(result_txt, '\\\\..*\\\\.') > 0")) %>% show_query()
<SQL>
SELECT *
FROM <dbpath>
WHERE (REGEXP_INSTR(result_txt, '\\..*\\.') > 0)
```
an alternative translation that also works:
```r
> df %>% filter(sql("result_txt ~ '\\\\..*\\\\.'")) %>% show_query()
<SQL>
SELECT *
FROM <dbpath>
WHERE (result_txt ~ '\\..*\\.')
```

**Comment by hadley** [comment]
Could you please create a reprex, following the advice at https://dbplyr.tidyverse.org/articles/reprex.html?

**Comment by cole-johanson** [comment]
This issue extends to PostGres. Should a separate ticket be filed?

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(dbplyr)
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql

x = c('in situ neoplasms','benign tumors')
lazy_frame(x=x,con = simulate_postgres()) %>%
  filter(str_detect(x,'neoplasm|tumor'))
#> <SQL>
#> SELECT *
#> FROM `df`
#> WHERE (STRPOS(`x`, 'neoplasm|tumor') > 0)
```

<sup>Created on 2020-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
@cole-johanson thanks for the reprex!

Looks like this is already fixed in devel:

``` r
library(dplyr, warn.conflicts = FALSE)

lf <- dbplyr::lazy_frame(x = "a", con = dbplyr::simulate_postgres())
lf %>% filter(str_detect(x, 'a|b'))
#> <SQL>
#> SELECT *
#> FROM `df`
#> WHERE (`x` ~ 'a|b')
```

<sup>Created on 2020-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
