### ISSUE TITLE
Feature request: background collect()

### ISSUE THREAD

**Issue by kmishra9** [tidyverse/dbplyr#410]
Brief description of the problem: collecting large tables can take a long time. This is especially true if, as part of a sequence, there's a repeated patten of

1. Transform big data in dbplyr
2. Collect in long form
3. pivot_wider 

I attempted to use the `future` package to parallelize this pattern for what I imagine is a reasonable speed up.

```r
# Parallelized download & pivot
df_wide = future({
    df_long %>%
    collect() %>%
    mutate(value = 1) %>%
    pivot_wider(
        names_from = "predictor",
        values_from = "value",
        values_fill = list("value" = 0),
        values_fn = list("value" = sum)
    )
})
```

`Future`, however, [only supports DBI objects being passed to sequential, rather than parallel futures](https://github.com/HenrikBengtsson/future/issues/367), so a long `collect()` still blocks things. It'd be great if there was a way to background a collect, such that it wouldn't block the console. Then, something like this would be possible, since the collected object will be a `tibble` instead of a DBI object:

```r
# Parallelized download & pivot
df_long_local = df_long %>% collect(background = TRUE) 

df_wide = future({
df_long_local %>%
    mutate(value = 1) %>%
    pivot_wider(
        names_from = "predictor",
        values_from = "value",
        values_fill = list("value" = 0),
        values_fn = list("value" = sum)
    )
})
```
The code _within_ the future() call would block (as expected) until df_long was collected, but it would allow someone to essentially parallelize the collection and pivots, at least until pivot_wider is implemented in dbplyr (I see you #344!)

**Comment by kmishra9** [comment]
Alternatively, some sort of multipart download scheme to speed things up, such as the [`aws.s3::put_object`](https://rdrr.io/cran/aws.s3/man/put_object.html) multipart option? 

Basically anything to take advantage of using maximum bandwidth available, if its not already being used

**Comment by hadley** [comment]
Unfortunately this is outside of the scope of dbplyr — it just uses the `dbGetQuery()` methods provided by individual backends.
