### ISSUE TITLE
intersect_all() and setdiff_all()

### ISSUE THREAD

**Issue by adithya604** [tidyverse/dbplyr#414]
Teradata supports other set operations like `EXCEPT ALL` and `INTERSECT ALL` on the lines of `UNION ALL` (implemented through `union_all.tbl_lazy`). Can we have implementations for verbs like `intersect_all.tbl_lazy` and `setdiff_all.tbl_lazy` to handle these cases?

**Comment by adithya604** [comment]
@hadley Thanks for making note of the request. 
Is it part of the dbplyr pipeline upcoming release and when it will be (estimated)?
Thanks.

**Comment by hadley** [comment]
I just marked it as an issue as part of regular issue triage; it wasn't an indication that I planned to work on it. And indeed, when I look at it now, I remember that `dplyr::intersect_all()`  doesn't exist, so implementing a method won't work.  It looks like `ALL` is a valid clause when applied to any of `union`, `intersect`, or `except` so I think we could just add an `all` argument.
