### ISSUE TITLE
Support collect(n = 0)

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dbplyr#415]
This is useful for getting column metadata, and seems to be supported across databases:

- https://stackoverflow.com/q/6033957/946850
- https://stackoverflow.com/q/37495497/946850

If not supported, the database will yell at us. The only risk I see is a misbehaving DBI driver, we could subclass.

**Comment by hadley** [comment]
Support means change the first line to `assert_that(length(n) == 1, n >= 0L)`, right?

**Comment by krlmlr** [comment]
Yes -- and perhaps for some databases we really need `n = 1` and remove the first line.

I'm wondering if we want a `tbl_ptype()` function that returns a zero-row tibble with correctly typed columns -- this is my use case for `n = 0`.
