### ISSUE TITLE
request for SAP's SQL Anywhere to be added to supported SQL dialects

### ISSUE THREAD

**Issue by tedmoorman** [tidyverse/dbplyr#418]
After a long road tracking down why my code wasn't working, I learned the particular #**SQL dialect** I'm forced to  use is not supported by dbplyr. Would it be possible to add SAP's #**SQL Anywhere** to one of the dialects supported by dbplyr? 

From [Sybase's website](http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.help.sqlanywhere.12.0.1/dbusage/ug-watcom-sql.html): "The dialect of SQL supported by SQL Anywhere is referred to as #**Watcom SQL**. The original version of SQL Anywhere was called Watcom SQL when it was introduced in 1992. The term Watcom SQL is still used to identify the dialect of SQL supported by SQL Anywhere. SQL Anywhere also supports a large subset of #**Transact-SQL**, the dialect of SQL supported by Sybase Adaptive Server Enterprise."

I'm sure this isn't the easiest thing in the world to do, but it would be appreciated by those of us who happen to be in an SQL Anywhere environment but love R and dplyr language.

**Comment by hadley** [comment]
Unfortunately we don't have the resources to provide translations for arbitrary backends. There's a little documentation available at https://dbplyr.tidyverse.org/articles/new-backend.html if you want to try yourself.
