### ISSUE TITLE
Add count method

### ISSUE THREAD

**Issue by hadley** [tidyverse/dbplyr#420]

**Comment by hadley** [comment]
It's not actually a generic, but I need to leave this open until I figure out what to do in dplyr.

**Comment by hadley** [comment]
I'm now confident that we can fix in dplyr — https://github.com/tidyverse/dplyr/pull/5114

**Comment by philibe** [comment]
:+1: 

I have moved  dplyr 0.8.4 to 1.0.0 and I get a new bad column ".add" with dbplyr. After upgrading dbplyr to 1.4.4 (>= 1.4.3), the bad column has gone :)

It was for that
```
req<-((tbl(
        connexion_bdd,  
        build_sql(
          con=connexion_bdd,
             !!(sqlcurrent)
        )
      )  
      %>% select_at(vars(.... ) )
      %>% mutate_at(vars(.... ) ,~(...)) 
      %>% group_by_at(vars(...),~sum(., na.rm = TRUE) )   # <---
      )%>% dbplyr::sql_render())
```
