### ISSUE TITLE
Can't take numeric mean (avg) of boolean with postgres backend.

### ISSUE THREAD

**Issue by roboton** [tidyverse/dbplyr#430]
Taking the mean of a boolean expression results in a postgres SQL error:

`nanodbc/nanodbc.cpp:1587: 42883: ERROR: function avg(boolean) does not exist;`

because the [avg](https://www.postgresql.org/docs/8.2/functions-aggregate.html) aggregate function in postgres expects a smallint, int, bigint, real, double precision, numeric, or interval.

```r
x <- c("abc", "def", "ghif")

lazy_frame(x = x, con = simulate_postgres()) %>%
  summarise(y = mean(is.na(x))) %>% show_query()
```

```sql
<SQL>
SELECT AVG(((`x`) IS NULL)) AS `y`
FROM `df`
```

The not so elegant workaround casts the boolean expression as an int:
```r
x <- c("abc", "def", "ghif")

lazy_frame(x = x, con = simulate_postgres()) %>%
  summarise(y = mean(sql("(x IS NULL)::int"))) %>% show_query()
```
```sql
<SQL>
SELECT AVG((x IS NULL)::int) AS `y`
FROM `df`
```

**Comment by krlmlr** [comment]
Not sure we can do much here, there's no way to detect that the input is a logical and should be coerced to integer. You can work around using R:

``` r
library(tidyverse)
library(dbplyr)
#> 
#> Attaching package: 'dbplyr'
#> The following objects are masked from 'package:dplyr':
#> 
#>     ident, sql

x <- c("abc", "def", NA)

db <- src_dbi(DBI::dbConnect(RPostgres::Postgres()), TRUE)

tibble(x = x) %>%
  copy_to(db, ., "temp3") %>%
  summarise(y = mean(as.integer(is.na(x)), na.rm = TRUE))
#> # Source:   lazy query [?? x 1]
#> # Database: postgres [kirill@/var/run/postgresql:5432/kirill]
#>       y
#>   <dbl>
#> 1 0.333
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
