### ISSUE TITLE
postgres check action failing

### ISSUE THREAD

**Issue by rjpat** [tidyverse/dbplyr#441]
The postgres checks have been failing ever since the release of R 4.0. This seems to be due to the fact that the cached version of `{remotes}` is from before R 4.0.

[This line](https://github.com/tidyverse/dbplyr/blob/8ec3227803b7f12711f4f847d9be424cce4a1562/.github/workflows/postgres.yaml#L49) specifies the cache which expects a `matrix.config.R` which is not defined, so the cache just reverts to what it was when the actions were originally defined.

I'm happy to go through and update but thought it would be good to have a discussion first around if the postgres check should test against multiple versions of R, like the R-CMD check. Or if that functionality should be stripped out so it tests the current version only.

**Comment by krlmlr** [comment]
Seems to be working again, e.g. https://github.com/tidyverse/dbplyr/pull/435?

**Comment by rjpat** [comment]
The cache does expire after a week or so which may have caused it to work. This issue will most likely come up again at the vest R version increment
