### ISSUE TITLE
`na.rm` argument in median() for consistency with stats::median()

### ISSUE THREAD

**Issue by lorenzwalthert** [tidyverse/dbplyr#442]
I want to compute a median in-memory and on the DB with the same code. Because my data may have missing values, I set `na.rm = TRUE` in `median()`. However, this does not work on the database.

``` r
dbplyr::translate_sql(median(x, na.rm = TRUE))
#> Error in median(x, na.rm = TRUE): unused argument (na.rm = TRUE)
median
#> function (x, na.rm = FALSE, ...) 
#> UseMethod("median")
#> <bytecode: 0x7f98e111c070>
#> <environment: namespace:stats>
```

<sup>Created on 2020-05-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I expected it to work the same as with `mean`, i.e. 
```r
dbplyr::translate_sql(mean(x, na.rm = TRUE))
#> <SQL> AVG(`x`) OVER ()
```

Don't know what happens with missing values currently and if that generalizes to all databases, but I thought probably the missing values are removed anyways as stated in the above warning for `mean`? 
```r
dbplyr::translate_sql(mean(x))
#> Warning message:
#> Missing values are always removed in SQL.
#> Use `AVG(x, na.rm = TRUE)` to silence this warning
#> This warning is displayed only once per session. 
#> <SQL> AVG(`x`) OVER ()
```

If that's the case, the in-memory version would by default not remove the NAs, the DB version would, and there is no way to set the `na.rm` argument to align them.

Can we add an argument `na.rm` for consistency to make the same code running with the same result on both engines?

**Comment by hadley** [comment]
Are you interested in doing a PR? You'd need to modify `sql_median()` to match how  `win_aggregate()` does the warning.

**Comment by lorenzwalthert** [comment]
Sorry for the late reply. Yes, happy to contribute, I opened #483.
