### ISSUE TITLE
str_detect keyword arguments generate errors

### ISSUE THREAD

**Issue by kmishra9** [tidyverse/dbplyr#444]
Code that ran fine under past versions of dbplyr threw some errors. I'm assuming the changes made in the newest dbplyr changelog ([1.4.3](https://dbplyr.tidyverse.org/news/index.html)) probably created the issue? 

``` r
library("dplyr", warn.conflicts = FALSE)

lf <- dbplyr::lazy_frame(x = "0.88", con = dbplyr::simulate_postgres())

lf %>% mutate(has_88 = str_detect(string = x, pattern = "88"))
#> <SQL>
#> Error in str_detect(string = x, pattern = "88"): unused arguments (string = x, pattern = "88")

lf %>% mutate(has_88 = str_detect(x, "88"))
#> <SQL>
#> SELECT `x`, `x` ~ '88' AS `has_88`
#> FROM `df`
```

<sup>Created on 2020-05-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kmishra9** [comment]
Including a value for the negate argument (even without a keyword) also appears to fail with the same "unused argument" issue as above

**Comment by hadley** [comment]
Generally, I think it's bad practice to name the first ~2 arguments because you can generally expect the reader to know what they are if they recognise the function name.

**Comment by kmishra9** [comment]
As one of the readers of my old code, I tend to disagree with that principle, but even ignoring the semantics of that, its still... broken, no? And the fact that it doesn't take a third argument (or accept the third argument with a message that it will be ignored) indicates an issue as well?

More importantly, I think it's a "breaking change" where code that's part of a production pipeline no longer works as written if keywords then have to be removed...

**Comment by hadley** [comment]
Yes, that's why I fixed it.

**Comment by kmishra9** [comment]
Oops -- thought it was closed as irrelevant, my bad, didn't see the attached commit
