### ISSUE TITLE
copy_to MySQL UTF8 database fails

### ISSUE THREAD

**Issue by ericemc3** [tidyverse/dbplyr#447]
Copying to a MySQL UTF8 database results in an error:
```r
data <-  tribble(
  ~lib, ~x1, ~x2,
  "Bâgé-le-Châtel", 2, 3,
  "Asnières-sur-Saône",  1,  1,
  "Asnières", 4,  1,
)

copy_to( DB, data, overwrite=T ) 

##Error in .local(conn, statement, ...) : 
##  could not run statement: Invalid utf8 character string: 'Asni'
```
As far as i can see, copy_to generates a csv file, then there is a SQL instruction:
```SQL
LOAD DATA LOCAL INFILE 'C:\\\\Users\\\\...\\\\Temp\\\\RtmpwpfPJV\\\\file15d451951e7.csv' INTO TABLE `data` 
``` 
But it fails because the csv is not UTF8 encoded, although the target table has character fields defined with utf8 charset (which is expected for any table created in a database which has UTF8 charset by default).

So i would suggest: if the MySQL database is UTF8, run write.csv with fileEncoding = "UTF-8"

**Comment by hadley** [comment]
Can you please file in the appropriate database backend package? dbplyr relies on RMySQL or RMariaDB for this.

**Comment by ericemc3** [comment]
Of course i'll do that

**Comment by ericemc3** [comment]
Are you definitely sure this is not on your side?
In backend-mysql.R, i can read, in the db_write_table function (line136), what looks like the csv generation before the LOAD DATA LOCAL INFILE:
```r
  utils::write.table(values, tmp, sep = "\t", quote = FALSE, qmethod = "escape",
    na = "\\N", row.names = FALSE, col.names = FALSE)
#...
 sql <- build_sql("LOAD DATA LOCAL INFILE ", encodeString(tmp), " INTO TABLE ",
    as.sql(table), con = con)
```
a fileEncoding="UTF-8"  looks adjustable in utils::write.table, depending on what you get with
SELECT @@character_set_database

**Comment by hadley** [comment]
Oh hmmm, I'll double check!

**Comment by hadley** [comment]
Yes, you're write. I think I'll fix this so that dbplyr just calls `dbWriteTable()` hopefully resolving the problem (or at least pushing it upstream to where it belongs).

**Comment by hadley** [comment]
I've removed that old code, and confirmed that `copy_to()` works as expect:

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

df <- tibble::tribble(
  ~lib, ~x1, ~x2,
  "Bâgé-le-Châtel", 2, 3,
  "Asnières-sur-Saône",  1,  1,
  "Asnières", 4,  1,
)

con_maria <- DBI::dbConnect(RMariaDB::MariaDB(),
  dbname = "test",
  host = "localhost",
  username = Sys.getenv("USER")
)
con_maria %>% copy_to(df) %>% collect()
#> # A tibble: 3 x 3
#>   lib                   x1    x2
#>   <chr>              <dbl> <dbl>
#> 1 Bâgé-le-Châtel         2     3
#> 2 Asnières-sur-Saône     1     1
#> 3 Asnières               4     1
```

<sup>Created on 2020-09-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
