### ISSUE TITLE
translation of paste not working for Redshift query

### ISSUE THREAD

**Issue by dsen6644** [tidyverse/dbplyr#458]
`paste()` is translated as `concat_ws` which is not a function in redshift. It uses either the `concat` function or the `||` operator. Similiar issue to #155 .

```r
df %>% mutate(month_year = paste(year, month))

#> Error in new_result(connection@ptr, statement, immediate): nanodbc/nanodbc.cpp:1374: 00000: [Amazon][Amazon Redshift] (30) Error occurred while trying to execute a query: [SQLState 42883] ERROR:  function concat_ws("unknown", character varying, character varying) does not exist
#> HINT:  No function matches the given name and argument types. You may need to add explicit type casts.
#> 
```

**Comment by cmohamma** [comment]
I too am experiencing this issue!

**Comment by hadley** [comment]
Some discussion at SO: https://stackoverflow.com/questions/56708136/postgres-9-1s-concat-ws-equivalent-in-amazon-redshift

Probably simplest is to override `paste()`, `paste0()`, and `str_c()` to use infix `||`.
