### ISSUE TITLE
Get rid of join_query and semi_join_query class

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dbplyr#470]
Joins and semi-joins should create instances of the `"select_query"` class instead. This allows for better optimization with fewer subqueries.

Proposing to add new components `$join` and `$semi_join` to the class, and use these in `sql_build()`. For `select_query_clauses()`, the `$semi_join` component acts like a `$where`.

The `"set_op_query"` class needs to stay for now.

**Comment by hadley** [comment]
This will reduce the number of subqueries, but substantially increases the complexity of two already complex functions. I'd prefer to not worry about this optimisation for now.
