### ISSUE TITLE
Feature Request: Force use of indices in query

### ISSUE THREAD

**Issue by kmishra9** [tidyverse/dbplyr#484]
Hey there,

I'm sure the particular use case I'm going to describe here is relatively rare, but I still feel like adding additional customizability could further improve `dbplyr`. I'm running an absolutely gigantic disk-based SQLite DB in a sandbox for data analysis and to get literally anything done, I have to rely pretty heavily on indexes. Most of my other `dpblyr` work typically does not rely heavily on indices so I haven't seen any native patterns for forcing their use before. I've appreciated the ability to create indexes in `copy_to`, but wish there was a way to force a query generated by `dbplyr` to use provided indices. For example, suppose we have a common join column, `join_col` in two datasets, `x` and `y`. 

I have indexed column `join_col` in both `x` and `y`, but it appears that the query optimizer occasionally doesn't use these two indexes when joining the datasets. In SQL, there are typically ways to enforce usage of indices, so a similar `dbplyr` pattern would be the goal.

Feature request: add an optional argument, similar to `copy`, to `*_join` and maybe (?) `filter` that one can provide names of indices to
```r
left_join(x, y, by = 'join_col', copy = TRUE, indexes = list('x_join_col_index', 'y_join_col_index')) 

```

**Comment by hadley** [comment]
Optimiser hints don't seem to be at all standardised across databases, so unfortunately I think this is just going to be too much work for the expected payoff.

**Comment by vituri** [comment]
Just adding a workaround here, since I had the same problems with wrong indexes being selected by Mariadb:
it is possible to extract the query generated by `dbplyr` and edit it with `stringr` or similars. I defined this different version of collect: given a lazy_tbl `x`, we first obtain the query, then try to add the "USE INDEX (`index_name`)" in front of the "FROM table_name" statements. 

```
collect_with_index = function(x, table_names = NULL, index_names = NULL, print_query = FALSE) {

# retrieve the query as string
  query =
    x %>%
    dbplyr:::remote_query() %>%
    as.character()
  
# retrieve the connection
  con = x$src$con
  
# if no index, just use a normal collect
  if (is.null(index_names)) {
    table = DBI::dbGetQuery(conn = con, statement = query)
  }
  
# if no table_names, try to guess all the table names in the query
  if (is.null(table_names)) {
    table_names =
      query %>%
      stringr::str_split(pattern = '\n') %>%
      unlist() %>%
      stringr::str_subset(pattern = 'FROM `') %>%
      stringr::str_split(pattern = "`") %>%
      map_chr(\(x) x[2])
  }
  
# create a tibble with table_names and indexes
  list_tables_index = tibble(
    tabela = table_names
    ,index = index_names
  )
  
# create the indexed query which we will edit
  indexed_query = query
  
# replace the FROM TABLE statements to add USE INDEX (index_name) in front of it
  list_tables_index %>%
    pwalk(function(tabela, index) {
      
      pattern = glue('\nFROM `{tabela}`\n')
      
      if (is.na(index)) {
        replacement = glue('\n  FROM `{tabela}` \n')
      } else {
        replacement = glue('\n FROM `{tabela}` USE INDEX (`{index}`) \n')
      }
      
      indexed_query <<-
        indexed_query %>%
        stringr::str_replace(pattern = pattern, replacement = replacement)
    })
  
# collect the table
  table = DBI::dbGetQuery(conn = con, statement = indexed_query)
}
```
