### ISSUE TITLE
Overwrite in compute 

### ISSUE THREAD

**Issue by gregleleu** [tidyverse/dbplyr#488]
I use compute to save non-temporary tables to remote databases. When I re-run some analysis I get an error as the table already exists. It would be nice if `compute` had an overwrite option like `copy_to`.

It feels like the philosophy in dbplyr is more around creating temporary tables, but it such cases are a natural extension I believe. 

```r
library(tidyverse)
library(magrittr)
library(DBI)

con <- dbConnect(RSQLite::SQLite(), ":memory:")

mtcars_rm <- con %>% copy_to(mtcars)

mtcars_rm %>% 
  summarise(mpg_avg = mean(mpg)) %>% 
  compute(name = "mtcars_avg", temporary = FALSE)

mtcars_rm %>% 
  summarise(mpg_avg = mean(mpg)) %>% 
  compute(name = "mtcars_avg", temporary = FALSE, overwrite = TRUE)
```

**Comment by hadley** [comment]
All the `overwrite` argument in `copy_to` is deletes the table if it already exists, so I think I'd suggest you just do that — adding an `overwrite` argument to `compute()` feels a bit too "in the weeds" to me. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
