### ISSUE TITLE
Error in new today function for oracle - Will currently return date and time rather than just date 

### ISSUE THREAD

**Issue by rlh1994** [tidyverse/dbplyr#505]
There is a missing piece of SQL code in the oracle implementation of the `today()` translation into the Oracle backend. The code is currently as follows:
https://github.com/tidyverse/dbplyr/blob/d4522efada213eff61b2113f84c5215e18f8610e/R/backend-oracle.R#L79

however Oracle SQL has no pure date variable (or variable type), so the SYSDATE must first be truncated for the time component to be set to 00:00:00, I believe the line should be
```r
 today = function() sql_expr(TRUNC(SYSDATE)), 
```
I believe this was the case in #267 but I'm aware there was a lot of other functions in that pull request so it I understand that it might have been missed.

**Comment by hadley** [comment]
Then why does `now()` use `CURRENT_TIMESTAMP`? I think it would make more sense for both `today()` and `now()` to use the same function, with `today()` additionally applying `TRUNC`.

**Comment by rlh1994** [comment]
You're right they should both be the same that's my mistake not realising `today()` runs on the current timezones...

Personally I only use `SYSDATE/SYSTIMESTAMP` as require the database timezone rather than the session timezone, but to match the other SQL dialects (and ANSI standard), and the behaviour of `now/today` it should use the `CURRENT_` variants to use the session timezone (as set either via executing a change to NLS within session or set to the machine tz when `dbConnect` is run).

So for session timezone:
```r
today = function() sql_expr(TRUNC(CURRENT_TIMESTAMP)), # sql_expr(TRUNC(CURRENT_DATE)) returns equivalent output if you want consistent looks with other dialect implementations
now = function() sql_expr(CURRENT_TIMESTAMP)
```

**Comment by hadley** [comment]
Thanks for clarifying!
