### ISSUE TITLE
Easy way to copy output of show_query()?

### ISSUE THREAD

**Issue by adhi-r** [tidyverse/dbplyr#506]
I often use the show_query() function to get the SQL, copy it and then paste it into BigQuery in my browser so I can create a view. I have to manually click and drag in the console to copy the output of that function - is there a way I can send it directly to my clipboard?

**Comment by ianmcook** [comment]
@adhi-r you could install [clipr](https://cran.r-project.org/package=clipr) and use it like this:
```r
capture.output(tbl_sql %>% select(columns) %>% show_query())[-1] %>% 
  paste(collapse = " ") %>%
  clipr::write_clip()
```

**Comment by hadley** [comment]
Thanks @ianmcook!
