### ISSUE TITLE
Deprecate first edition in dbplyr_fallback

### ISSUE THREAD

**Issue by hadley** [tidyverse/dbplyr#507]
Needs minor version bump; must happen after April 1, 2021.

**Comment by mgirlich** [comment]
@hadley I'm not quite sure how the deprecation should look like. Can you take care of that so that we can include into the next release?

**Comment by hadley** [comment]
Notes to self: 

* Details of overall process in https://dbplyr.tidyverse.org/articles/backend-2.html
* So probably needs some warning in `dbplyr_fallback()` if the edition is 1, encouraging the user to upgrade the package. Not sure how to tell them which package to upgrade. Maybe inspect `con`?

**Comment by hadley** [comment]
@mgirlich it's likely to be at least 10 days before I can get to this
