### ISSUE TITLE
Bring str_like to dbplyr

### ISSUE THREAD

**Issue by rjpat** [tidyverse/dbplyr#509]
Currently have `str_like()` in `{stringr}`, will add a PR

**Comment by rjpat** [comment]
Realised some problems. Will review and resubmit

**Comment by hadley** [comment]
stringr doesn't have a `str_like()` function?

**Comment by rjpat** [comment]
Sorry should have been more explicit, [`str_like()`](https://github.com/tidyverse/stringr/blob/master/R/detect.r#L131) is here, there has not been a release since it was merged.

**Comment by hadley** [comment]
I clearly totally forgot about `str_like()`; I'm happy to re-review the PR if you want to re-submit it 😄
