### ISSUE TITLE
temp table name in subquery keeps incrementing

### ISSUE THREAD

**Issue by kohleth** [tidyverse/dbplyr#511]
hi,

see the code below, a query that involves a sub-query. Everytime I run the query the number `00x` in the temp table name `dbplyr_00x` increases. This makes the database engine not able to utilize any cached result. Is there a way to reset the counter or make the translated sql the same across repeated runs?

```r
library(dbplyr)
library(dplyr)
con=dbplyr::simulate_odbc()
tbl_temp<- tbl_lazy(df = iris,con=con)
intermediate_table=tbl_temp%>%
  mutate(x=1)%>%
  count(Species)
tbl_temp%>%
  inner_join(intermediate_table)%>%
  show_query
tbl_temp%>%
  inner_join(intermediate_table)%>%
  show_query

```

**Comment by hadley** [comment]
This has been fixed in the dev version
