### ISSUE TITLE
option to silence create table inform message

### ISSUE THREAD

**Issue by samssann** [tidyverse/dbplyr#517]
A small feature request: option to silence table creation inform message. e.g. 
`options(dbplyr.inform_create_table = TRUE)` 
Would be `TRUE` by default, but can be set to `FALSE` so that inform messages on temporary table creation will not appear.

``` r
library(dbplyr)
dbplyr:::mssql_temp_name("test", T)
#> Created a temporary table named: #test
#> [1] "#test"
```

<sup>Created on 2020-10-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
You can just name the table yourself:

```R
library(dbplyr)
dbplyr:::mssql_temp_name("#test", T)
```

**Comment by samssann** [comment]
What about the auto generated temporary tables?
`Created a temporary table named: #dbplyr_085`

**Comment by hadley** [comment]
When does that happen?

**Comment by samssann** [comment]
With `dplyr::auto_copy()` and `dbplyr:::auto_copy.tbl_sql()` functions
```r
library(dplyr, warn.conflicts = F)
library(dbplyr, warn.conflicts = F)
library(tibble, warn.conflicts = F)
library(odbc, warn.conflicts = F)
con <- dbConnect(odbc::odbc(), .connection_string = "xxx") # SQL Server connection object
temp <- tibble(a = 1, b = 2)
dbWriteTable(con, "temp", temp)
temp2 <- tibble(a = 1, b = 2)
auto_copy(tbl(con, "temp"), temp2, copy = T)
#> Created a temporary table named: #dbplyr_100
```

**Comment by hadley** [comment]
Then don't use those functions? I feel like I'm missing something here.

**Comment by samssann** [comment]
Sorry, I presented the case for this feature poorly. On the top level, this happens when using e.g. `dm::rows_*()` functions and `dbplyr::*_join()` functions with `copy = TRUE` and src is a SQL Server.
