### ISSUE TITLE
Should tbl_lazy support [ for column selection?

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dbplyr#523]
This would allow us to reduce the size of the data that needs to be fetched from the database for printing: `format.tbl()` could select only the columns it can possibly print. It may change the rows that are displayed, though, if the query doesn't specify an explicit sort order.

Currently:

``` r
dbplyr::memdb_frame(a = 1:3, b = 4:6)[1:2, ]
#> Error in dbplyr::memdb_frame(a = 1:3, b = 4:6)[1:2, ]: incorrect number of dimensions
```

<sup>Created on 2020-10-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
I don't think so — the one of the major reasons for introducing the dplyr interface was to avoid dispatch on `[`.

**Comment by krlmlr** [comment]
I guess we'd need a lower-level interface for pillar support, do we have one in vctrs?

**Comment by krlmlr** [comment]
(Should pillar provide a generic?)
