### ISSUE TITLE
bigint does not download as character

### ISSUE THREAD

**Issue by LukasWallrich** [tidyverse/dbplyr#524]
I have a Google bigquery table with bigint fields that I would like to download as text. DBI::dbConnect( lets me set bigint = "character" but that only seems to work for SQL queries run without dbplyr. If I understand the documentation correctly, the option should also be respected by dbplyr. If not, then I'd be grateful for a hint.

I don't quite know how to provide a reprex. Below an outline of the code I use.

```r
con <- DBI::dbConnect(
  bigquery(),
  project = projectid,
  dataset = datasetid,
  billing = projectid,
  bigint = "character"
)

# This works
tb <- DBI::dbGetQuery(con, "SELECT `user_id` FROM `tweets`")

# This doesn't - returns NAs due to integer overflow
mini_tweets_bq <- tbl(con, "mini_tweets")
mini_tweets_bq  %>% select(user_id) %>%  collect()

```

**Comment by hadley** [comment]
Can you please file in the bigrquery repo?
