### ISSUE TITLE
dbplyr:::sql_translate_env.Oracle not found

### ISSUE THREAD

**Issue by TuomoNieminen** [tidyverse/dbplyr#529]
The Known Issues section in the RStudio database Oracle page (https://db.rstudio.com/databases/oracle/) describes the following workaround to be used for Oracle connections.

```r
sql_translate_env.JDBCConnection <- dbplyr:::sql_translate_env.Oracle
sql_select.JDBCConnection <- dbplyr:::sql_select.Oracle
sql_subquery.JDBCConnection <- dbplyr:::sql_subquery.Oracle
```

However, with dbplyr version 2.0 there is no function dbplyr:::sql_translate_env.Oracle:

```r
sql_translate_env.JDBCConnection <- dbplyr:::sql_translate_env.Oracle
```

Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'sql_translate_env.Oracle' not found

How to use dbplyr 2.0 with Oracle connections?

**Comment by MartinInFrankfurtAM** [comment]
It used to work prior to the update to 2.0.0.

**Comment by hadley** [comment]
This might work:

```R
sql_translation.JDBCConnection <- dbplyr:::sql_translation.Oracle
```

**Comment by MartinInFrankfurtAM** [comment]
Great Hadley, Thank you for bringing me 1/3 step forward:
Now my script fails at
sql_select.OraConnection <- dbplyr:::sql_select.Oracle
sql_subquery.OraConnection <- dbplyr:::sql_subquery.Oracle

The naive attempt
sql_select.JDBCConnection        <- dbplyr:::sql_select.Oracle

fails with 
Object 'sql_select.Oracle' not found.
I will dig into the namespace.

**Comment by MartinInFrankfurtAM** [comment]
This worked for me. Thank you Hadley!

**Comment by greg-botwin** [comment]
I found this github issue after updating to dbplyr 2 and encountering similar errors.  It was also necessary for me to update the following

`sql_select.JDBCConnection <- dbplyr:::sql_query_select.Oracle`

`sql_subquery.JDBCConnection <- dbplyr:::sql_query_wrap.Oracle`

The instructions found here might now be out of date https://db.rstudio.com/databases/oracle/

**Comment by blairj09** [comment]
The instructions at https://db.rstudio.com/databases/oracle/ have been updated.

**Comment by hadley** [comment]
Thanks @blairj09!
