### ISSUE TITLE
Incomplete dplyr requirements

### ISSUE THREAD

**Issue by bersbersbers** [tidyverse/dbplyr#531]
I need to pin `dplyr==0.8.5`. CRAN says I should still be able to install `dbplyr==2.0.0` since it requires `dplyr>=0.8.0`. However, upon installation of `dbplyr`, I get this error:

```
Error: object ‘relocate’ is not exported by 'namespace:dplyr'
Execution halted
```

In fact, `dplyr::relocate()` was introduced in `dplyr==1.0.0`:
https://www.tidyverse.org/blog/2020/03/dplyr-1-0-0-select-rename-relocate/

So I guess `dbplyr` should require `dplyr>=1.0.0`, and I should pin `dbplyr==1.4.4`. Alternative, you might opt to not use `dplyr::relocate()`.

**Comment by hadley** [comment]
Given that the implicit dplyr 1.0.0 dependency doesn't seem to have caused widespread problems, I think it's simpler to require dplyr 1.0.0.
