### ISSUE TITLE
dbplyr should escape NA_real_ correctly

### ISSUE THREAD

**Issue by yitao-li** [tidyverse/dbplyr#540]
This is related to https://github.com/sparklyr/sparklyr/issues/985.

The tl;dr is with `dbplyr` 2.0 involved, the following code in `sparklyr`

```
library(sparklyr)

sc <- spark_connect(master = "local")

the_spark_table <- dplyr::copy_to(sc, data.frame(x = 1:2), 'the_spark_table')
the_spark_table <- the_spark_table %>% dplyr::mutate(z = NA_real_)
```

doesn't produce the expected result of a new column named "z" of type Double in Apache Spark.

I believe `NA_real_` should be translated to `CAST(NULL AS DOUBLE)` in SQL instead of just `NULL`.

**Comment by yitao-li** [comment]
Proposed fix: https://github.com/tidyverse/dbplyr/pull/541

**Comment by hadley** [comment]
What does casting a `NULL` to double actually do? i.e. what value does it yield?

**Comment by yitao-li** [comment]
@hadley It yields a `NULL` value (not `NaN`) of type double (at least that is the case with Spark SQL)

**Comment by yitao-li** [comment]
Or put it in a slightly different way, `DBI::dbGetQuery(conn, "select cast(null as double) as x")` will make sure the schema of the result has a column named "x" that is of type nullable-double.

**Comment by hadley** [comment]
If we're going to add this conversion to dbplyr, I'd want more reassurance that this is something multiple databases support.  Is there a reason you can't use `z = as.numeric(NA)`? That seems a bit more explicit to me.

**Comment by yitao-li** [comment]
@hadley Re: `z = as.numeric(NA)` -- Yes I think it's way better :+1: , but still, I'm hoping for some workaround that doesn't require everyone to change their apparently valid R code. Also, there could be cases where some expression that is not `NA_real_` the literal evaluates to `NA_real_` as well.

Re: DB portability -- I did more research using sqlfiddle.com and db-fiddle.com and found out the only truly portable way is `NULL * 2e-16` instead of type-casting. So I have revised my PR accordingly.

Fun-aside, type-casting `NULL` is something well-defined in ISO/IEC 9075:1992 [*], but MySQL 5.x and even later versions don't really fully comply to it. Meanwhile `NULL * 2e-16` is something that will definitely evaluate to null value of type double on any sane DB backends and that has been verified empirically thanks to {sql,db-}fiddle.com

[*] It looks like the only version of it that everyone can view for free online is https://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt)

**Comment by hadley** [comment]
Unfortunately, currently the trade off in this case between improved results and increased complexity just doesn't seem worth it to me. dbplyr has to walk a fine line here when doing translations, and while the current behaviour is not 100% correct, it rarely causes problems.
