### ISSUE TITLE
Add option to translate SQL for Oracle 11 and below

### ISSUE THREAD

**Issue by mfherman** [tidyverse/dbplyr#545]
Unfortunately, my organization is living in the past and still uses Oracle 11g. This means the changes to the Oracle translation in version 2.0 essentially break all interactive usage of dbplyr for me because the `FETCH` command was not implemented until Oracle 12c.

Here's some example output:

```r
> tbl(con, "TEST_TABLE")
Error: nanodbc/nanodbc.cpp:1655: HY000: [Oracle][ODBC][Ora]ORA-00933: SQL command not properly ended
 
<SQL> 'SELECT *
FROM ("TEST_TABLE") 
FETCH FIRST 11 ROWS ONLY'
```

Would you consider an option or setting in dbplyr that would allow compatibility with Oracle 11 and earlier?

I believe it would require rolling back this for the "Oracle Legacy" translation: https://github.com/tidyverse/dbplyr/commit/a848022cd11981fb1def0103f62f7600072f01eb.

**Comment by hadley** [comment]
Unfortunately I just don't have the resources to support an unmtained database that's over 10 years old. I know this is likely to be disappointing/frustrating, but I have to allocate resources as best I can to support the widest number of R users.

**Comment by mfherman** [comment]
That is certainly understandable! Because I’m unlikely to convince my organization’s IT department to upgrade Oracle anytime soon, I reckon I can create a dbplyr backend that still works for Oracle 11 and include it in our internal package.

Thanks for all these amazing tools you and your team has built and support!
