### ISSUE TITLE
bracket filter in summarize not work in MS SQL after update 2.0.0

### ISSUE THREAD

**Issue by coponhub** [tidyverse/dbplyr#546]
bracket filter not work on dbplyr 2.0.0 on MS SQL like berow
`tbl(con, "HOGE") %>% group_by(City_ID) %>% summarise(userVisit = n_distinct(visit_id[isUser == 1L]))`
>  Error: nanodbc/nanodbc.cpp:1617: 00000: [FreeTDS][SQL Server]Statement(s) could not be prepared.  [FreeTDS][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'THEN'. 
<SQL> 'SELECT TOP 11 "City_ID", COUNT(DISTINCT CASE WHEN ("isUser") THEN ("visit_id") END) AS "usrVisit"
FROM "HOGE"
GROUP BY "City_ID"'

It worked on dbplyr 1.4.4

**Comment by hadley** [comment]
Can you please create a reprex, following the advice at https://dbplyr.tidyverse.org/articles/reprex.html?

**Comment by coponhub** [comment]
2.0.0
``` r
library(tidyverse)
dbplyr::lazy_frame(x = 1:5, y = 5:1, con = dbplyr::simulate_mssql()) %>%
    summarize(z = n_distinct(x[x > y])) %>%
    show_query()
#> <SQL>
#> SELECT COUNT(DISTINCT CASE WHEN (CAST(IIF(`x` > `y`, 1, 0) AS BIT)) THEN (`x`) END) AS `z`
#> FROM `df`
dbplyr::lazy_frame(x = 1:5, y = 5:1, con = dbplyr::simulate_mssql()) %>%
    summarize(z = sum(x[x > y], na.rm = TRUE)) %>%
    show_query()
#> <SQL>
#> SELECT SUM(CASE WHEN (CAST(IIF(`x` > `y`, 1, 0) AS BIT)) THEN (`x`) END) AS `z`
#> FROM `df`
```
> ```SUM(CASE WHEN (CAST(IIF(`x` > `y`, 1, 0) AS BIT)) THEN (`x`) END)```

An expression of non-boolean type(BIT) specified in a context where a condition is expected.

But it seem correct SQL generate in 1.4.4 

1.4.4
``` r
library(tidyverse)
dbplyr::lazy_frame(x = 1:5, y = 5:1, con = dbplyr::simulate_mssql()) %>%
    summarize(z = n_distinct(x[x > y])) %>%
    show_query()
#> <SQL>
#> SELECT COUNT(DISTINCT CASE WHEN (`x` > `y`) THEN (`x`) END) AS `z`
#> FROM `df`
dbplyr::lazy_frame(x = 1:5, y = 5:1, con = dbplyr::simulate_mssql()) %>%
    summarize(z = sum(x[x > y], na.rm = TRUE)) %>%
    show_query()
#> <SQL>
#> SELECT SUM(CASE WHEN (`x` > `y`) THEN (`x`) END) AS `z`
#> FROM `df`
```

<sup>Created on 2020-11-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Thanks! Please let me know if you spot any other places where the translation fails — it's not possible to get it 100% correct, but we should be able to catch the problems in most real world SQL.
