### ISSUE TITLE
IIF being generated on SQL Server 2008 in dbplyr 2.0.0

### ISSUE THREAD

**Issue by tonyk7440** [tidyverse/dbplyr#547]
I was using the dbplyr 1.4.4 library version which translated code like below

```
df %>%
    dplyr::mutate(location= ifelse(location== "old", "new", location))
```
to
```
CASE WHEN ("location" = 'old') THEN ('new') WHEN NOT("location" = 'old') THEN ("location") END AS "location"
```

But after upgrading to dbplyr 2.0.0 it results in
```
IIF("location" = 'old', 'new', "location") AS "location"
```

This isn't supported in MS SQL 2008. Microsoft itself isn't supporting that database since last year so I am wondering if that is also the case here or if it is a bug?

**Comment by hadley** [comment]
According to https://docs.microsoft.com/en-us/sql/t-sql/functions/logical-functions-iif-transact-sql?view=sql-server-ver15, it's available in all versions of SQL server that MS supports. In general, we tie our SQL generation to supported version of products in order to maximise the utility of the time we spend developing this package.

**Comment by philibe** [comment]
> In general, we tie our SQL generation to supported version of products in order to maximise the utility of the time we spend developing this package.

:)

But 
- `IIF()` is not standard SQL and  the algorithm  of `CASE WHEN` could be useful for other RDBMS and therefore used for MS SQL.
   * [BNF Grammar for ISO/IEC 9075:1992 - Database Language SQL (SQL-92), Case specification ](https://ronsavage.github.io/SQL/sql-92.bnf.html#case%20specification)
- It's a sort of regression :P of dbplyr

I could understand that it could be take time and there is other priorities, but IMHO it has to be remain open :)

**Comment by philibe** [comment]
I workarounded with [`case_when()`](https://dplyr.tidyverse.org/reference/case_when.html) and I get `CASE WHEN`.
