### ISSUE TITLE
Materialise tables in DB, that are dbplyr producs

### ISSUE THREAD

**Issue by spirosparaskevasFBB** [tidyverse/dbplyr#569]
Hi! I am quite new to dbplyr so hopefully I ll explain the issue effectively. My intention is materialise a table produced through a dbplyr query back to original DB. The issue is that I would prefer I did not collected prior pushing back the table. Hence, how can I materialise a table that is a product of a complex query (combining multiple initial tables) back to the DB. Hope I am clear in what I ask. Thanks in advance.

**Comment by mgirlich** [comment]
If I understand correctly what you want than you should be happy with `dbplyr::compute(x, name = "your_fancy_table_name", temporary = FALSE)`. You can check the documentation with `?dbplyr::compute.tbl_sql`
