### ISSUE TITLE
When Querying data from an oracle database, TRUNC() has no effect, and LAST_DAY results in random times

### ISSUE THREAD

**Issue by LukasTang** [tidyverse/dbplyr#581]
I am querying from an oracle 12c database and in one step I want to create a column with the last day of the month, based on another date column. In doing so, dblyr fails to format the output to Date, and yields data of the format dttm instead (see screenshot),. In the oracle SQL developer, on the other hand, everything looks fine. Besides: the dttm value don't all have the same time (see screenshot): some show 00:00:00 and others show 01:00:00. 

I don't think I can provide a working example since this would require reproducing the whole environment, but my code is as follows and the poblem is not limited to one table, but to all tables that I query:

```r
  zp<-tbl(con,in_schema("DWH_MART_DMA","VW_MRT_AKT_ZAHLUNGSPLAN")) %>%
    dplyr::filter(DWH_OPCO_ID ==opco  & year(FAELLIGKEITSDATUM)>2015) %>%#& STATUS_RATE=="faellig"
    dplyr::select(DWH_OPCO_ID,ZVINDEX,FAELLIGKEITSDATUM,FAELLIGERBETRAG) %>%
    mutate(
      FAELLIGKEITSDATUM=TRUNC(FAELLIGKEITSDATUM)
      ,FAELLIGKEITSMONAT = LAST_DAY(FAELLIGKEITSDATUM))
```
The resulting SQL: 

```sql
SELECT "DWH_OPCO_ID", "ZVINDEX", "FAELLIGKEITSDATUM", "FAELLIGERBETRAG", LAST_DAY("FAELLIGKEITSDATUM") AS "FAELLIGKEITSMONAT"
FROM (SELECT "DWH_OPCO_ID", "ZVINDEX", TRUNC("FAELLIGKEITSDATUM") AS "FAELLIGKEITSDATUM", "FAELLIGERBETRAG"
FROM (SELECT *
FROM (DWH_MART_DMA.VW_MRT_AKT_ZAHLUNGSPLAN) 
WHERE ("DWH_OPCO_ID" = 1.0 AND
 EXTRACT(year FROM "FAELLIGKEITSDATUM") > 2015.0)) "dbplyr_054") "dbplyr_055"
```

See Screenshots for the results.

I am a big fan of dbplyr, this is just a little nuisance factor because it leads to me formating the columns after collecting them just to be on the safe side. 

![scree_ora_result](https://user-images.githubusercontent.com/49587161/105855104-feb08f00-5fe7-11eb-8a17-2979e2581331.PNG)
![scree_r_result](https://user-images.githubusercontent.com/49587161/105855106-ff492580-5fe7-11eb-88aa-4031bfee4847.PNG)

**Comment by hadley** [comment]
Can you please try and explain your problem a bit more clearly? I don't understand what you want, especially given that your `mutate()` calls Oracle SQL functions directly rather than relying on dplyr translations.

**Comment by LukasTang** [comment]
What I find puzzling is that the formats differ. Why do I receive 'datetime' in R when I make sure that the dates are formatted as dates in Oracle already (using TRUNC)? Shouldn't the format be the same after pulling from the database? 

Besides that, I find the times of the datetime-result in R odd, why is it 00:00:00 for some observations and 01:00:00 for others?

**Comment by hadley** [comment]
This doesn't sound like a dbplyr issue; it sounds like it's more likely that the issue is with whatever database package/driver you're using. All this would be much easier to tell if you'd provided a reprex; even I couldn't run your code I'd be able to see exactly what you did.

**Comment by LukasTang** [comment]
Alright, thanks anyway. Not sure if this is closer to a reprex, but the only missing piece in the code that I provided is the creation of the connection object con:
`  
#Load the driver
  drv <- dbDriver("Oracle")

  # Read the connection details
  #dwhlogin <- read.table(file = path, header=T, sep=",", stringsAsFactors = FALSE)

  #Connect wth the data base
  con <- dbConnect(drv,
                   username = as.character(login$username),
                   password = as.character(login$password),
                   dbname = dbname)

  zp<-tbl(con,in_schema("DWH_MART_DMA","VW_MRT_AKT_ZAHLUNGSPLAN")) %>%
    dplyr::filter(DWH_OPCO_ID ==opco  & year(FAELLIGKEITSDATUM)>2015) %>%#& STATUS_RATE=="faellig"
    dplyr::select(DWH_OPCO_ID,ZVINDEX,FAELLIGKEITSDATUM,FAELLIGERBETRAG) %>%
    mutate(
      FAELLIGKEITSDATUM=TRUNC(FAELLIGKEITSDATUM)
      ,FAELLIGKEITSMONAT = LAST_DAY(FAELLIGKEITSDATUM))

zp%>%show_query()
`  
And the ROracle library ROracle 1.3-1 is taken from here: https://www.oracle.com/database/technologies/roracle-downloads.html
Also, Oracle Client or Instant Client version 12.x is installed.

Anyhow, apologies for misplacing the issue, and thanks for the consideration. As my company currently migrates to Oracle 19, I can soon check if the issue persists on the new database. So I guess I should reach out to Oracle next time with an issue like that? (clearly, there is some interplay between the packages at work, which makes it difficult to know the 'responsibilites').

**Comment by hadley** [comment]
I'd suggest reproduce the problem by using `DBI::dbGetQuery()` and then filing an issue with the developers of the ROracle package.
