### ISSUE TITLE
Split-Apply-Combine (Divide and conquer) in a remote tibble or dblplyr class

### ISSUE THREAD

**Issue by bwcastillo** [tidyverse/dbplyr#587]
Hi,

Does there exist any way to apply a  ["Split-Apply-Combine"](https://towardsdatascience.com/functional-programming-in-r-with-purrr-469e597d0229) (divide and conquer algorithm) method to a dbplyr object class? I found the Replyr package but it method wasn't work.

`diris %>% 
  replyr_split('Species') %>%
  lapply(f2) %>%
  replyr_bind_rows()`

Currently I am connected with Rpostgres library to a Postgresql data base. So, in this way I am querying my data hosted in a postgres database, now just I need to apply the "Split-Apply-Combine" method (Divide and Conquer Algorithm) to get some results.

Thanks for you help.
Regards!

**Comment by hadley** [comment]
You can use [do()](https://dbplyr.tidyverse.org/reference/do.tbl_sql.html).  But rhis sort of question is a better fit for <https://community.rstudio.com> so I'd recommend asking it over there. (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
