### ISSUE TITLE
Translation error with SQL server

### ISSUE THREAD

**Issue by yiugn** [tidyverse/dbplyr#601]
I have a table in SQL server database, and I want to manipulate this table with dbplyr/dplyr in R packages.

    library(odbc)
    library(DBI)
    library(tidyverse)
    
    con <- DBI::dbConnect(odbc::odbc(),
                          Driver    = "SQL Server", 
                          Server    = "xx.xxx.xxx.xxx",
                          Database  = "stock",
                          UID       = "userid",
                          PWD       = "userpassword")
    
    startday = 20150101
    day = tbl(con, in_schema("dbo", "LogDay")) 

![image](https://user-images.githubusercontent.com/9432179/108229925-9470b180-7183-11eb-81c9-22e2aae245f0.png)

I tried this simple dplyr function after connecting to remote database, but only to fail with error messages.

    day %>% 
      mutate(ovnprofit = ifelse(stockCode == lead(stockCode,1),lead(priceOpen,1)/priceClose, NA)) %>% 
      select(logDate,stockCode, ovnprofit)

How can I solve this problem?

![image](https://user-images.githubusercontent.com/9432179/108229995-a5212780-7183-11eb-886d-1e757df42db5.png)

p.s. When I apply dplyr function after transforming 'day' into tibble first, it works. However, I want to apply dplyr function directly, not transforming into tibble because it's to time consuming and memory intensive.

**Comment by hadley** [comment]
Can you please create a reprex following the advice in https://dbplyr.tidyverse.org/articles/reprex.html?

**Comment by mgirlich** [comment]
@yiugn I close this as the reprex is still missing. Happy to reopen if you add a reprex.
