### ISSUE TITLE
simulate_mysql missing dbQuoteLiteral and does not work with glue::glue_sql

### ISSUE THREAD

**Issue by robchallen** [tidyverse/dbplyr#603]
Testing sql generation using glue::glue_sql with simulate_mysql does not work.

Raising this against dbplyr rather than glue as similar issue as:

https://github.com/rstudio/pool/issues/96
https://github.com/tidyverse/glue/issues/179

Non systematically tested a few other of the dbplyr::simulate_* methods which also seem to have the same problem

``` r
# reprex
con = dbplyr::simulate_mysql()
db = "mysqlDb"
tbl = "mysqlTable"
cat(glue::glue_sql("SELECT * FROM {db}.{tbl};",.con=con))
#> Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'dbQuoteLiteral' for signature '"MySQLConnection"'
```

<sup>Created on 2021-02-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
The simulation function are used for internal testing of dbplyr only; I wouldn't expect them to work with other packages.
