### ISSUE TITLE
NA int values for expected integer64 column in BigQuery table (despite working with dbGetQuery)

### ISSUE THREAD

**Issue by zoews** [tidyverse/dbplyr#610]
When attempting to use `dbplyr` along with `dbConnect` to access a table in BigQuery, I cannot find a way to preserve `bit::integer64` type on a particular column. This is despite that type support appearing successfully in base dbConnect().

## Connection supports bit64::integer64 column without `dbplyr`
The following dbConnect() code uses the `bit64::integer64` implementation + `bigrquery()` to successfully return query results with `integer64` column:

```
# bq_auth and project_id config

con <- dbConnect(
  bigrquery::bigquery(),
  project = project_id,
  dataset = "test_data",
  billing = project_id,
  bigint = "integer64"
)

dbGetQuery(con,'
  select * from test_data.table limit 10') %>%
  glimpse()

```

as expected, `column_one` shows `<int64>`. However..

## No `integer64` with `tbl`, `glimpse()`, `collect()`, etc.

When attempting to form the connection the following way:

```{r}
note_info <- tbl(con, "test_data.table")

note_info %>%
   glimpse()
```
outputs that `column_one` is `<int>` type. 

```
note_info %>% 
  select(column_one, column_two, column_three) %>%
  head(10) %>%
  collect()

```
outputs `column_one` with `<int>` types and NA values for all observations.

## Other attempts 

The behaviors above persist no matter what I specify for the `bigint` paramter for `dbConnect()` (`character`, `integer`, not setting an explicit parameter).

I also attempted to coerce in the query itself via:

```
note_info %>% 
  select(column_one, column_two, column_three) %>%
  mutate(column_one = as.integer64(column_one)) %>%
  head(10) %>%
  collect()

note_summary
```

but throws :
```
x Type not found: BIGINT at [1:26] [invalidQuery]
```
Which may imply an upstream issue with the the `tbl` method not seeing the `integer64` column type.

Any ideas? Thank you! (My apologies for not writing a true `reprex` -- I was unsure how to do so when relying on BigQuery specifically. I can look into mocking/other approaches if preferable!)

**Comment by zoews** [comment]
on reviewing closed issues, I found a nearly identical issue in #524 -- should I pursue in bigrquery as well? 

The main difference is that given a dataset with mixed biting and non-bigint types, the BQ database connection appears to have integrity, and returns correct columns for non-int64 columns along with NA int for any bigints. May be useful to consider whether `dbplyr` should throw exceptions in this case as opposed to silent type coercion.

I found [this issue](https://github.com/r-dbi/bigrquery/issues/411) from 2020-10-19 but no further action (I would be interested in researching in the code base(s) and attempting a PR as well!)

**Comment by hadley** [comment]
Could you please create a reprex that illustrates the problem?  It will be useful even if I can't run it without manually supplying my own bq credentials.

**Comment by zoews** [comment]
@hadley sure thing! here is a reprex (without bq credentials):

``` r
library(tidyverse)
library(DBI)
library(reprex)
library(bigrquery)

# Authenticate and connect to bigquery project

bq_auth(path = ---)
project_id <- bq_projects()

con <- DBI::dbConnect(
  bigrquery::bigquery(),
  project = project_id,
  dataset = "dataset",
  billing = project_id,
  bigint = "integer64"
)

# DBI::dbGetQuery correctly returns tibble with integer64 column

output_tibble <- DBI::dbGetQuery(con,'
  select * from dataset.table limit 10')

output_tibble %>%
  select(int64_identifier) %>%
  glimpse()
#> Rows: 10
#> Columns: 1
#> $ int64_identifier <int64> 444444444444, 5555555555555, 6666666666666, 777…

# HOWEVER: dbplyr attempts to coerce to integer, overflow results in NAs

note_info <- tbl(con, dataset.table", bigint = "integer64")

note_dbplyr_query <- note_info %>%
  select(int64_identifier) %>%
  head(10)

note_data <- note_dbplyr_query %>%
  collect()
#> Warning in as.integer.integer64(x): NAs produced by integer overflow

note_data %>%
  select(int64_identifier) %>%
  glimpse()
#> Rows: 10
#> Columns: 1
#> $ int64_identifier <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA
```

<sup>Created on 2021-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## Notes
From generating the reprex, I see how `dplyr::collect()` ignores the `bigint` parameter in the `DBI::dbConnect` connection and attempts to `int` via `as.integer.integer64(x)`. In contrast, `DBI::dbGetQuery` is able to use `bit64::integer64` as the container for `int64` values.

(From reading the [DBI spec](https://cran.r-project.org/web/packages/DBI/vignettes/spec.html), I better understand DBI's philosophy behind handling integer64 values).

Any guidance would be great, thank you! As mentioned upthread, I would be interested in helping via a PR too, eg masking `dplyr::collect()` with a int64-aware `dbplyr::collect()` or similar approach.

**Comment by hadley** [comment]
Oh, this is actually a bigrquery problem — can you please file an issue over there? Could you please also work on minimising your reprex a little? e.g. there's no need to load the whole tidyverse, or reprex, and you could collapse all the dbplyr code into a single pipeline.

And are you sure that the `bigint` in `tbl(con, dataset.table", bigint = "integer64")` actually does anything?

(It looks like the root cause is that in `collect.tbl_BigQueryConnection` `bq_table_download()` doesn't get the value of the bigint field from `x$src$con`, so a PR should be straightforward if you want to give it a go).
