### ISSUE TITLE
add_count returns grouped dataframe

### ISSUE THREAD

**Issue by davidchall** [tidyverse/dbplyr#614]
According to the [dplyr docs](https://dplyr.tidyverse.org/reference/count.html), `add_count()` is supposed to:

> group transiently, so the output has the same groups as the input.

Although this is true for the dplyr version, I discovered that the dbplyr version does change the groups.

``` r
library(tidyverse)
library(dbplyr)

df <- tribble(
  ~name,    ~gender,   ~runs,
  "Max",    "male",       10,
  "Sandra", "female",      1,
  "Susan",  "female",      4
)

# ungrouped output
df %>% add_count(gender, wt = runs)
#> # A tibble: 3 x 4
#>   name   gender  runs     n
#>   <chr>  <chr>  <dbl> <dbl>
#> 1 Max    male      10    10
#> 2 Sandra female     1     5
#> 3 Susan  female     4     5

# grouped output
memdb_frame(df) %>% add_count(gender, wt = runs)
#> # Source:   lazy query [?? x 4]
#> # Database: sqlite 3.34.1 [:memory:]
#> # Groups:   gender
#>   name   gender  runs     n
#>   <chr>  <chr>  <dbl> <dbl>
#> 1 Sandra female     1     5
#> 2 Susan  female     4     5
#> 3 Max    male      10    10
```

<sup>Created on 2021-03-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by davidchall** [comment]
I think this might be related to how `dplyr_reconstruct` handles dbplyr tables.

**Comment by mgirlich** [comment]
Unfortunately, there needs to be done something in `dplyr` to fix this. See https://github.com/tidyverse/dplyr/issues/5837

**Comment by davidchall** [comment]
Excellent - thanks for digging into this!

**Comment by davidchall** [comment]
Looks like this will be addressed by https://github.com/tidyverse/dplyr/pull/5848
