### ISSUE TITLE
slice_sample() throwing error on a MariaDB database

### ISSUE THREAD

**Issue by josswright** [tidyverse/dbplyr#617]
I've recently had to pull a random sample of a fairly large (>1.5M row) database that's stored in a MariaDB instance. I wrote a fairly basic dbplyr filter:

```r
# pseudocode: <set up database connection>
# pseudocode: db_tbl <- tbl( <connection>, "tablename" )

all_articles <-   
   db_tbl %>%
   slice_sample( n=5000 ) %>%
   collect 

```

I receive:

```
Error: FUNCTION tablename.random does not exist [1305]
```

I assume that this may be a limitation in functions internally provided by MariaDB, but I'm also unsure from searching around whether this is something I can fix (by implementing tablename.random directly on the DB side?) or if I'm just missing something obvious.

As an aside, I'm in a lucky position here where we're about to move this whole dataset and collection across to a new system, so I have the option to move database servers. Is there a recommended database implementation that's most compatible for dbplyr?

**Comment by hadley** [comment]
Could you please work on at least a partial reprex using the advice in https://dbplyr.tidyverse.org/articles/reprex.html?
