### ISSUE TITLE
Computing query results causes attributes to be dropped

### ISSUE THREAD

**Issue by nathaneastwood** [tidyverse/dbplyr#618]
Let's consider a simple example

```r
sc <- sparklyr::spark_connect(master = "local")
mtcars_spark <- dplyr::copy_to(dest = sc, df = mtcars)

blah <- dplyr::select(mtcars_spark, mpg)                                                                                                                          
attr(blah, "testAttr") <- "hello"                                                                                                                                 
attributes(blah)                                                                                                                                                  
# $names
# [1] "src" "ops"
# $class
# [1] "tbl_spark" "tbl_sql"   "tbl_lazy"  "tbl"      
# $testAttr
# [1] "hello"

blah <- dplyr::compute(blah)                                                                                                                                      
attributes(blah)                                                                                                                                                  
# $names
# [1] "src" "ops"
# $class
# [1] "tbl_spark" "tbl_sql"   "tbl_lazy"  "tbl"
```

When using `dplyr::compute()` on a `tbl_spark` object, for example, it will dispatch to `dbplyr:::compute.tbl_sql()`. I feel like this should maybe have some similar method to `dplyr::dplyr_reconstruct()` to ensure that attributes are not dropped. This seems to be a recent problem as we've experienced this since upgrading to the latest dbplyr from 1.4.2.

**Comment by hadley** [comment]
This seems to be due to `sparklyr:::compute.tbl_spark()`, so you'll need to file an issue in sparklyr.

**Comment by nathaneastwood** [comment]
So `sparklyr:::compute.tbl_spark()` is actually a completely new method added 8 days ago (see here: https://github.com/sparklyr/sparklyr/pull/2987). The issue I raised here actually predates that new method so I believe this issue still exists for `dbplyr:::compute.tbl_sql()` which was the dispatch method at the time.

I have, however, just tested this with the latest GitHub version of sparklyr and I can see that it is also an issue with `sparklyr:::compute.tbl_spark()` so I will file an issue there too.

**Comment by hadley** [comment]
In general, you shouldn't expect to be able to add attributes to other people's objects. There is definitely no expectation that `compute.tbl_sql()` should preserve attributes.
