### ISSUE TITLE
Translate `window_order` to `arrange` for local data frames

### ISSUE THREAD

**Issue by iangow** [tidyverse/dbplyr#627]
Feature request: Add `window_order` to `dplyr` for local data frames. 

Following on from tidyverse/dplyr#2874, it seems that using `arrange()` to produce windows using SQL sources yields a warning like this:

```
## Warning: ORDER BY is ignored in subqueries without LIMIT
## ℹ Do you need to move arrange() later in the pipeline or use window_order() instead?
```

This is fine, as either I can just swap out `arrange` for `window_order` and the code runs or I can select `warning=FALSE` in the code chunk options.

There are two downsides to the former approach:

1. Because `window_order` lives in `dbplyr`, its use requires either `dbplyr::window_order` or `library(dbplyr)`.
2. The code becomes adapted to SQL sources, as it will no longer work with local data frames. (I find myself often inserting or removing a `collect()` call as I mess around with data, as **if one is careful and uses standard `dplyr` verbs**, code works in either place. This is a really nice feature.)

If `window_order` existed for local data frames, then both problems would be solved. And it seems it has a well-defined meaning in that new context.

**Comment by iangow** [comment]
> Maybe dbplyr could allow `window_order()` to work on data frames? (Just be calling `arrange`).

I think that would work for my use case. I will edit the issue title accordingly.

> It doesn't feel right to me to expose this in dplyr because it's so database focused. 

*In principle*, there are benefits from being able to run window functions for particular variables without sorting the whole data frame. That said, I couldn't find any compelling examples of this *in practice* (my sample may be too limited; I couldn't find the examples I vaguely remember from many years ago).

**Comment by hadley** [comment]
Right, but to make `window_order()` work like that would be a bunch of implementation work in dplyr, which definitely wouldn't be worth it.

**Comment by hadley** [comment]
Do you want to do a PR for this?  You'd need to turn `window_order()` into an S3 generic, then add `tbl_lazy()` and `data.frame()` methods.

**Comment by iangow** [comment]
Let me see what I can do. Probably in a month or so.

(I'm up to p.61 of "Advanced R" … it seems another 240 pages of reading will allow me to make sense of what you're saying. I made my [first R package](https://github.com/iangow/farr) today---consisting of nothing but the #628 function---so there's hope.)

**Comment by hadley** [comment]
@iangow I can also do it 😄

**Comment by mgirlich** [comment]
@iangow Do you want to have a go at a PR now? 😄

**Comment by iangow** [comment]
@mgirlich Hmm. I'm getting loads of messages. It seemed fine on my laptop, where I installed the versions of the packages I have. But because the pull request inherently affects two different packages, it doesn't work on whatever system is behind GitHub.

I guess the solution to my first point about additional arguments (previous comment) would be to hard-wire these to their defaults when `window_order` calls `arrange`.

**Comment by hadley** [comment]
Oooh, I meant for the PR to be here, not in dplyr.

**Comment by mgirlich** [comment]
It was decided to not translate to `arrange()` (https://github.com/tidyverse/dplyr/issues/6146#issuecomment-1192825426) and instead improve the error message (#953).
