### ISSUE TITLE
`copy_to` fails with local data to Redshift

### ISSUE THREAD

**Issue by kmishra9** [tidyverse/dbplyr#640]
I love the `copy_to()` function and have sadly been unable to use it with Redshift for the last couple years due to the following error when using the `RPostgres` package. Whenever I _need_ `copy_to()` functionality, I've been able to use the older, slower, and less well-maintained `RPostgreSQL` package for my needs. I'm delighted to see that `RPostgres::Redshift()` now exists and hope a custom `copy_to()` implementation/translation for Redshift can one day exist!

This issue also impacts/breaks the `copy = TRUE` argument in `*_join()` calls, which would be a natural alternative to workflows trying to use `copy_to()`!

A final point of nuance is that `copy_to()` and `copy = TRUE` both work when the tables are remote, but if the table is local and you're trying to 'send' it to the db, it doesn't work.

```r
Error: Failed to prepare query: ERROR:  function generate_subscripts(name[], integer) does not exist
HINT:  No function matches the given name and argument types. You may need to add explicit type casts.
```

**Comment by kmishra9** [comment]
This actually looks to be an issue that seems to be derived from `DBI::writeTable()`, since I think `copy_to()` is mostly a wrapper and the same issue occurs when trying to use the DBI function directly!

**Comment by mgirlich** [comment]
Closing the issue as this seems to be an issue with RPostgres. If the issue still exists, you should open an issue in the [RPostgres repository](https://github.com/r-dbi/RPostgres/issues)
