### ISSUE TITLE
Code highlighting in console

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dbplyr#644]
Would be nice to have code highlighting. Together with #642 it would be much easier to skim over SQL code generated by `dbplyr`.

**Comment by hadley** [comment]
You're thinking of using cli to colour the SQL clauses differently?

**Comment by mgirlich** [comment]
Exactly. A very simple hack could simply use something like `sql <- gsub("SELECT", cli::col_blue("SELECT"), sql, fixed = TRUE)` in `show_query()`. While this is not perfect it should work most of the time and it is only a cosmetical thing.

Here a quickly created example

![image](https://user-images.githubusercontent.com/18258854/162693312-9d3d4807-5095-4322-8f3b-06c154020798.png)

and with CTE

![image](https://user-images.githubusercontent.com/18258854/162693155-cca6ed82-3a64-4f04-91a4-38dab4d74155.png)

**Comment by hadley** [comment]
I assume `sql_format_clauses()` gets called too early in order to be able to conditional apply ANSI escapes?

**Comment by mgirlich** [comment]
It can be done in `sql_format_clauses()`. I was just not so keen on passing around another argument all the way down to `sql_format_clauses()`.

**Comment by hadley** [comment]
We could do something with a global option? It's a bit icky, but I think it's defensible in a situation like this.
