### ISSUE TITLE
Error message when translating any() for bigquery: "Error: Window function LOGICAL_OR() is not supported by this database" #445

### ISSUE THREAD

**Issue by LukasWallrich** [tidyverse/dbplyr#648]
I am trying to translate `filter(any(a, b))` in an SQL query to BigQuery, but get the error message ``LOGICAL_OR()` is not supported by this database"` - that [does not seem to be true](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators), so I am wondering how to get this to work. I cannot produce a working SQL using LOGICAL_OR(), though, so it might be better to translate this into a chain of ORs?

My code:

```r
con <- DBI::dbConnect(
  bigquery(),
  project = projectid,
  dataset = datasetid,
  billing = projectid,
  bigint = "character"
)
bq_tweets <- tbl(con, "tweet_topics")
#Fails
bq_tweets  %>% filter(any(leave, neutral, remain, shambles, questioning)) %>% select(status_id) %>% show_query()
#Does what I want
bq_tweets %>% filter(leave | neutral | remain | shambles | questioning) %>% select(status_id) %>% show_query()
```

Unfortunately, I cannot create a reprex because there is no attempt to translate any() when I simulate_dbi(). As said, I have an easy workaround, but might still be worth fixing this / the error message?

``` r
library(dbplyr)
library(dplyr)

df <- data.frame(id = 1:10, a = c(rep(c(T,F), 5)), b = c(rep(T, 5), rep(F, 5)))

df_lazy <- tbl_lazy(df, con = simulate_dbi())

df_lazy %>% filter(any(a, b)) %>% select(id) %>% show_query()
#> <SQL>
#> SELECT `id`
#> FROM `df`
#> WHERE (any(`a`, `b`))
```

<sup>Created on 2021-04-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by mgirlich** [comment]
What you want to use is `if_any()` (like for a normal data frame):

``` r
library(dbplyr, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)

lazy_frame(id = 1:10, a = c(rep(c(T,F), 5)), b = c(rep(T, 5), rep(F, 5))) %>% 
  filter(if_any(c(a, b), ~ .)) %>% 
  show_query()
#> <SQL>
#> SELECT *
#> FROM `df`
#> WHERE (`a` OR `b`)
```

<sup>Created on 2021-12-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

In a future release it should be possible to leave out the second argument `~ .` to `if_any()` so that you can write  `filter(if_any(c(a, b)))`
