### ISSUE TITLE
Add vignettes to documentation

### ISSUE THREAD

**Issue by williamlai2** [tidyverse/dbplyr#657]
Are you able to provide some more detail on some of the functions in the documentation? Perhaps add some vignettes?

https://dplyr.tidyverse.org/reference/backend_dbplyr.html

For example, for `db_write_table(con, table, types, values, temporary = FALSE, ...)` what goes in `types`? It is nowhere on the page. Some examples would be good. I couldn't find any anywhere in my quick search.

I assume that this is the `field.types (default: NULL)` optional argument from  `DBI::dbWriteTable()` but I only just found out about that. https://dbi.r-dbi.org/reference/dbwritetable

**Comment by hadley** [comment]
If you're writing your own backend, at this point our expectation is that you'll have to read some of the source code for dbplyr to figure this out. This isn't a great answer but there aren't that many people writing backends and there are plenty of examples to learn from, so improving this developer facing documentation is low on our priority list.
