### ISSUE TITLE
function tbl doesn't work anymore

### ISSUE THREAD

**Issue by DrFabach** [tidyverse/dbplyr#658]
I use dbplyr to extract information from an oracle database with odbc driver. 
I download last version of dbplyr and dyplr and since yesterday i got some errors with tbl().

My connection is active in rstudio and i am able to see the table i want to work with .
I am able to use sql to get data from table.

When i use this fonction 
```r
tbl(con, in_schema("schema","table"))
```

I got the following error  :

Erreur : nanodbc/nanodbc.cpp:1655: 42S02: [Oracle][ODBC][Ora]ORA-00942: table or view does not exist

<SQL> 'SELECT *
FROM ("schema"."table") "q01"
WHERE (0 = 1)'

**Comment by einarhjorleifsson** [comment]
I am aware that with dbplyr version 2 schema and table name calls have become case sensitive.
so if table name is e.g. all-caps this no longer works:
```
tbl(con, in_schema("schema", "table"))
```
but this does:
```
tbl(con, in_schema("SCHEMA", "TABLE"))
```
may this be bugging you?
e

**Comment by DrFabach** [comment]
Thank you for your answer 
I already tried it and this give me this error : 


Erreur : nanodbc/nanodbc.cpp:1655: HY000: [Oracle][ODBC][Ora]ORA-00933: SQL command not properly ended
 
<SQL> 'SELECT *
FROM ("SCHEMA"."REPONSE_TEXTE_LONG") 
FETCH FIRST 11 ROWS ONLY'

I cannot collect() data.

**Comment by DrFabach** [comment]
The error come frome the "FETCH FIRST 11 ROWS ONLY"

**Comment by DrFabach** [comment]
issue is report here : https://github.com/tidyverse/dbplyr/pull/27

**Comment by fschiefenhoevel** [comment]
Hi!

is there a way you could help me to implement your solution in the current dbplyr version? I am stuck with the same problem (oracle 11 not being supported, FETCH FIRST not working), and I can't fix it with your code (since dbplyr has changed too much, I guess)

**Comment by mgirlich** [comment]
This is fixed in the dev version which should be released to CRAN soon.

**Comment by fschiefenhoevel** [comment]
ahh, that would be supergood. Thanks!
