### ISSUE TITLE
Translate conditional sums in Hive differently

### ISSUE THREAD

**Issue by alex-m-ffm** [tidyverse/dbplyr#659]
Translate conditional sums in Hive differently
---

Hi everyone,

I don't know if this is a specific issue of the Hive version in my company (2.1.1-cdh6.2.1) or a general one, but it seems that it does not like to sum up Booleans.
I had experimented doing some calculations with Impala first where these operations worked, but for some specific calculations (approximate percentiles) it made more sense to move everything to Hive. In both Impala and Hive these conditional sums in R `sum(var == specific_value)` are translated the same, but only work in Impala.

```r
library(tidyverse)
library(dbplyr)
df <- tibble(x = 1:10,
            group = c(rep("a", 3), rep("b", 4), rep("c", 3))
            )

lazy_frame(df = df, con = simulate_impala()) %>% 
  summarise(n_a = sum(group == "a"),
            n_b = sum(group == "b"),
            n_c = sum(group == "c")) %>% 
  show_query()

lazy_frame(df = df, con = simulate_hive()) %>% 
  summarise(n_a = sum(group == "a"),
            n_b = sum(group == "b"),
            n_c = sum(group == "c")) %>% 
  show_query()
```

```sql
SELECT SUM(`group` = 'a') AS `n_a`, SUM(`group` = 'b') AS `n_b`, SUM(`group` = 'c') AS `n_c`
FROM `df`
````

Would it be useful in Hive connections to translate conditions in a sum by default into an `IF(group = 'a', 1, 0)`, as also described [on SO](https://stackoverflow.com/questions/25130681/how-hive-ql-do-query-with-multiple-count-function-and-make-a-divides-methon-with)? I tested this within HUE and it worked fine.

For now I will probably just solve my issue by explicitly changing the condition in the R code, that should do the trick. 
This conditional sum was the better way to do this as I had other calculations that were not done at this grouping. The alternative way of doing those other calculations separately, then grouping by the group, counting, pivoting and joining everything together seemed more cumbersome in this context.

Looking forward to hearing your feedback on this!

In the same context I also noticed that there were problems translating unions into a Hive query while they were fine for Impala, but those queries were quite complex and will require some digging on Monday... I will just open a different issue for that.

Best,
Alex

**Comment by mgirlich** [comment]
I like the idea but unfortunately this looks quite difficult to implement. Also, I don't see many other places where this added complexity would pay off. So, I'm closing the issue. Thanks for the suggestion!
