### ISSUE TITLE
n_distinct function doesn;t work on grouped data

### ISSUE THREAD

**Issue by Waftmaster** [tidyverse/dbplyr#664]
When trying to group a dataframe and then generate a distinct count using n_distinct like this:

"geog_gen_eth_hes <- hes_geog %>%
  group_by(ethnicity, gender, region) %>%
  mutate(value = n_distinct(hesid)) %>%
  distinct(ethnicity, gender, region, value) %>%
  ungroup %>%
  compute"

 I get the following error:

"Error: nanodbc/nanodbc.cpp:1617: XX000: ERROR: WINDOW definition is not supported; Error while preparing parameters RROR: WINDOW definition is not supported; Error while preparing parameters <SQL> 'SELECT "hesid", "ethnicity", "gender", "region", COUNT(DISTINCT "hesid") OVER (PARTITION BY "ethnicity", "gender", "region") AS "value" FROM "dbplyr_001" LIMIT 1000'"

I'm confused as to why it's creating a window function rather than just writing:

"SELECT ethnicity, gender, region, COUNT(DISTINCT hesid) FROM hes_geog GROUP BY ethnicity, gender, region;"

**Comment by mgirlich** [comment]
The queries are actually quite different. The query you proposed

```sql
SELECT ethnicity, gender, region, COUNT(DISTINCT hesid) FROM hes_geog GROUP BY ethnicity, gender, region;
```

changes the number of rows, so it would use `summarise()` not `mutate()`

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

lazy_frame(g = c(1, 1, 1, 2, 2), x = c(1, 1, 2, 3, 3)) %>% 
  group_by(g) %>% 
  summarise(value = n_distinct(x))
#> <SQL>
#> SELECT `g`, COUNT(DISTINCT `x`) AS `value`
#> FROM `df`
#> GROUP BY `g`
```

<sup>Created on 2022-03-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

In `mutate()` it is not so easy to count the distinct values (e.g. see [stackoverflow](https://stackoverflow.com/questions/63527035/how-to-do-a-countdistinct-using-window-functions-with-a-frame-in-sql-server))
