### ISSUE TITLE
confusing output after multiple `arrange()` calls

### ISSUE THREAD

**Issue by yitao-li** [tidyverse/dbplyr#665]
For example,

```
library(dplyr)
library(dbplyr)

df <- memdb_frame(a = 1, b = 2)

df %>% arrange(a) %>% arrange(b) %>% print()
```

will output

```
# Source:     table<dbplyr_001> [?? x 2]
# Database:   sqlite 3.35.5 [:memory:]
# Ordered by: a, b
      a     b
  <dbl> <dbl>
1     1     2
```

even though its generated query is

```
df %>% arrange(a) %>% arrange(b) %>% remote_query() %>% print()
```

```
<SQL> SELECT *
FROM `dbplyr_001`
ORDER BY `b`
```
(as expected)

So, the generated query is what I expected, but the "Ordered by: a, b" from the first print() output was confusing.

Similarly,

```
df %>% arrange(a, b) %>% print()
```

will also output "Ordered by: a, b", even though it will generate "ORDER BY `a`, `b`" instead of "ORDER BY `b`" as the SQL query.

Similar confusion happens for

```
df %>% arrange(a) %>% arrange(b) %>% arrange(a) %>% print()
```

as well (generated query will say "ORDER BY `b`" as expected but the print() output will say "Ordered by: a, b, a").

Anyhow, this seems to have caused some confusion and panicking for folks who probably mostly relied on REPL for debugging their SQL queries (e.g., see https://github.com/sparklyr/sparklyr/issues/1847) but hopefully it's something that's easy to fix.

**Comment by mgirlich** [comment]
Actually, the reprex also outputs a warning which is quite helpful here as it hints that multiple `arrange()` in a row probably don't make much sense. Still, the output is indeed confusing

``` r
library(dplyr, warn.conflicts = FALSE)
library(dbplyr, warn.conflicts = FALSE)

df <- memdb_frame(a = 1, b = 2)

df %>% 
  arrange(a) %>% 
  arrange(b)
#> Warning: ORDER BY is ignored in subqueries without LIMIT
#> ℹ Do you need to move arrange() later in the pipeline or use window_order() instead?
#> # Source:     table<dbplyr_001> [?? x 2]
#> # Database:   sqlite 3.35.5 [:memory:]
#> # Ordered by: a, b
#>       a     b
#>   <dbl> <dbl>
#> 1     1     2
```

<sup>Created on 2021-07-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

It seems to be that this was intended behaviour in the past but I think it doesn't make sense anymore.
