### ISSUE TITLE
transmute() discards groups

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dbplyr#670]
but shouldn't? The resulting lazy frame still refers to the now discarded columns.

``` r
library(tidyverse)

dbplyr::memdb_frame(a = 1, b = 2) %>%
  group_by(a) %>%
  transmute(b)
#> # Source:   lazy query [?? x 1]
#> # Database: sqlite 3.35.5 [:memory:]
#> # Groups:   a
#>       b
#>   <dbl>
#> 1     2

tibble(a = 1, b = 2) %>%
  group_by(a) %>%
  transmute(b)
#> # A tibble: 1 x 2
#> # Groups:   a [1]
#>       a     b
#>   <dbl> <dbl>
#> 1     1     2
```

<sup>Created on 2021-07-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mgirlich** [comment]
Note that in `dplyr` the order of grouping variables can change. For simplicity and consistency with `dplyr` the same thing happens in my PR

``` r
library(dplyr, warn.conflicts = FALSE)

# column `b` gets pushed to the front
data.frame(a = 1, b = 2) %>%
  group_by(a, b) %>%
  transmute(a = a + 1)
#> # A tibble: 1 x 2
#> # Groups:   a, b [1]
#>       b     a
#>   <dbl> <dbl>
#> 1     2     2
```

<sup>Created on 2021-07-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
