### ISSUE TITLE
Add support for week function on PostgreSQL backend

### ISSUE THREAD

**Issue by andyquinterom** [tidyverse/dbplyr#675]
Add support for `week` function to be translated in PostgreSQL backend. This should be fairly easy to do since PostgreSQL has a native implementation of this.

As specified in [Postgres documentation](https://www.postgresql.org/docs/9.1/functions-datetime.html), we can extract the week from a Date column with the following:

```sql
SELECT EXTRACT(WEEK FROM TIMESTAMP '2001-02-16 20:38:40');
Result: 7
```

We can easily implement this directly into the backend.

**Comment by mgirlich** [comment]
I added a PR for this. Note that `SELECT EXTRACT(WEEK FROM TIMESTAMP '2001-02-16 20:38:40');` is not the equivalent of `week()` but of `isoweek()`.
