### ISSUE TITLE
Month label Abbreviations while using the month() function

### ISSUE THREAD

**Issue by asimumba** [tidyverse/dbplyr#680]
Hi,

Is it possible based on the month() function [translation](https://github.com/tidyverse/dbplyr/blob/47e53ce30402d41ae4b38c803de12e63d64a9b6c/R/backend-mssql.R#L181-L190) to support abbreviation while using the month() function with MS SQL Server? 

For instance, using SQL, we can get an abbreviated month name with `month = sql(LEFT(DATENAME(mm,my_date),3))`.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄

**Comment by asimumba** [comment]
Thanks for your consideration... Adding this here in case someone may find this solution useful. I eventually applied a workaround to the problem outlined here https://community.rstudio.com/t/r-equivalent-of-sql-server-datename-function/109976/5
