### ISSUE TITLE
Extending `tbl$src$disco`?

### ISSUE THREAD

**Issue by jonkeane** [tidyverse/dbplyr#681]
This is neither a bug nor a feature request — more a question of clarification. How stable / appropriate would it be to add custom cleanup functions to custom `tbl` classes in a manner similar to [what is done already.](https://github.com/tidyverse/dbplyr/blob/47e53ce30402d41ae4b38c803de12e63d64a9b6c/R/src_dbi.R#113). By assigning them to `tbl$src$disco`?

For context: I'm working on extending Arrow to interact with the DuckDB package, and in that process I want to make transient tables in a DuckDB connection that will get cleaned up when the `tbl` is garbage collected. A simplified toy implementation (in the real implementation there would be options to turn this behavior off, not have hard-coded names, etc of course) would be something like:

```r
arrow_to_duckdb <- function(arrow_table, con) {
  # this creates a table/View with the name "table_name"
  duckdb::duckdb_register_arrow(con, "table_name", arrow_table)
  tbl <- tbl(con, table_name)
  tbl$src$disco <- duckdb_disconnector(con, table_name)
}

duckdb_disconnector <- function(con, tbl_name) {
  reg.finalizer(environment(), function(...) {
    if (DBI::dbIsValid(con)) {
      duckdb::duckdb_unregister_arrow(con, tbl_name)
    }
  })
  environment()
}
```

Such that when when the object that is returned from `arrow_to_duckdb()` is removed+gced it will be unregistered just before.

I'm hesitant to do this since `$src$disco` is something of an internal to dbplyr tables. If this is a functionality that seems useful for other cases I'm happy to put together a PR to dbplyr that would add a proper API here for assigning these instead of reaching in like this. Alternatively, for our custom class we could use some other place in our `tbl`s to store these cleanup environments if `$src$disco` is fragile, but extending them isn't desired.

**Comment by hadley** [comment]
How about extending `src_dbi()` so that `auto_disconnect` could be `TRUE`, `FALSE`, or a custom function? I think that would give you the flexibility you'd need while only expanding the dbplyr API by a very small amount.

**Comment by hadley** [comment]
Although in this case, you could also subclass `tbl` and add the environment + finalizer there; that way that tbl would be cleaned up as soon as its deleted (and gc'd) rather than waiting for the `src` to be deleted.

**Comment by jonkeane** [comment]
> How about extending src_dbi() so that auto_disconnect could be TRUE, FALSE, or a custom function? I think that would give you the flexibility you'd need while only expanding the dbplyr API by a very small amount.

I'm happy to send a PR that does this (would `src_dbi()` be the right place since it has been marked as superseded or an option in `tbl`?).

In arrow's case we ended up using a different name (that is highly unlikely to clash), but the second approach you mention is probably even better for us. So maybe leaving dbplyr alone and recommending subclassing is the way to go generally?

**Comment by hadley** [comment]
Yeah, I think subclassing is likely to be a better way to go.
