### ISSUE TITLE
packages depending on dbplyr fail to install, again and again

### ISSUE THREAD

**Issue by torbjorn** [tidyverse/dbplyr#688]
I just tried to `update.packages(ask=F,checkBuilt=T)` on my system.

Very predictably it failed with one of the first packages to install (_np_ in this case) error'ing out with:

    Error in completeSubclasses(classDef2, class1, obj, where) : 
      trying to get slot "subclasses" from an object of a basic class ("NULL") with no slots
    Error: package or namespace load failed for ‘dbplyr’:
     .onLoad failed in loadNamespace() for 'dbplyr', details:
      call: setClass(cl, contains = c(prevClass, "VIRTUAL"), where = where)
      error: error in contained classes ("character") for class “ident”; class definition removed from ‘dbplyr’
    Error in .requirePackage(package) : 
      unable to find required package ‘dbplyr’
    Calls: <Anonymous> ... .recacheSubclasses -> getClassDef -> .requirePackage
    Execution halted
    ERROR: lazy loading failed for package ‘np’
    * removing ‘/home/tlindahl/R/x86_64-pc-linux-gnu-library/4.1/np’
    * restoring previous ‘/home/tlindahl/R/x86_64-pc-linux-gnu-library/4.1/np’

    The downloaded source packages are in
            ‘/tmp/RtmpezqLbW/downloaded_packages’
    Warning message:
    In install.packages("np") :
      installation of package ‘np’ had non-zero exit status

This has happened very frequently as of late. Each time I spend ~ 30 minutes with soul wrenching debuging trying to pin down where this happens, and with some clever guesswork I'm able to install some other arbitrary package first which makes this problem go away.

Now, I realise this may not be `dbplyr`'s problem, but this is the package that's being listed as unable to load, causing the update to fail, and it's what people are seeing.

Is there anything dbplyr developers can do to rectify or help people? Is there some dependent package that perhaps not could be depended upon?

Is there some general guideline you could offer on how to best debug this? It's perhaps unfair to take this here, as said, but this package is what people will see as the problem without knowing better.

**Comment by mgirlich** [comment]
The problem was actually not in dbplyr but in another package (Brobdingnag). It is fixed in the dev version which you can install with `devtools::install_github("RobinHankin/Brobdingnag")` and you should have no more issues loading and installing dbplyr.
