### ISSUE TITLE
insert custom SQL before/after dplyr query?

### ISSUE THREAD

**Issue by caljnj** [tidyverse/dbplyr#698]
Hi 

is it possible to insert custom SQL before/after the main query?

e.g. for MSSQL i would like to use at the beginning: 

SET STATISTICS IO ON

and turn it off after the query with

SET STATISTICS IO OFF

happy to attempt to add a feature into dplyr for this if it doesnt exist

**Comment by romainfrancois** [comment]
This probably belongs to `dbplyr` rather than `dplyr`, but also this might be better suited for a community.rstudio.com question.

**Comment by caljnj** [comment]
aha oops thanks. not really a bug

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
