### ISSUE TITLE
Method to convert a lazy query to a table in the remote database

### ISSUE THREAD

**Issue by apalacio10** [tidyverse/dbplyr#699]
Hello there

I want to know if there is any method to convert a lazy query to a table in the remote database. Something like dbWriteTable.

![imagen](https://user-images.githubusercontent.com/40868159/131014873-3efe97b9-d2c9-4972-a975-91475e8b84b2.png)

Thanks

**Comment by mgirlich** [comment]
You can use `compute()` for this, e.g.

```r
library(dbplyr)
x <- memdb_frame(x = 1)

compute(
  x,
  name = "my_dest_table"
)
```

Use `temporary = FALSE` to store it permanently. See `?dbplyr::compute.tbl_sql()` for information on the arguments.
