### ISSUE TITLE
SQL Syntax Error when using MariaDB

### ISSUE THREAD

**Issue by stephenashton-dhsc** [tidyverse/dbplyr#709]
Hi,

This might be a bit more of a question than a bug, so feel free to close it if needed!

We've been running a large amount of code using dplyr/dbplyr with an MSSQL server with the following version details:
`
Microsoft SQL Server 2019 (RTM-CU4) (KB4548597) - 15.0.4033.1 (X64)   Mar 14 2020 16:10:35   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: )
`

With this server, we have no issues with the code, however, we have recently been asked to run the same code on with a MariaDB server with the following version details:
`
5.5.60-MariaDB
`

We've appropriately switched our connection scripts etc., and can read/write/execute on the new SQL server, but when we run our code, we receive the following error:
`
Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(ORDER BY 'COL1', 'COL2', 'COL3', 'COL4', 'COL5') AS 'q0' at line 3 [1064]'
`

We also receive the following warning:
`
ORDER BY is ignored in subqueries without LIMIT
Do you need to move arrange() later in the pipeline or use window_order() instead? 
`

I might be able to cobble together a repex, but wanted to check that this isn't being caused by our version of MariaDB being incompatible with dbplyr or something first?

Many thanks,

Stephen

**Comment by mgirlich** [comment]
I think it isn't due to an outdated version of MariaDB. Can you please create a reprex?

**Comment by stephenashton-dhsc** [comment]
I've just created the following reprex and it returns the same style error and warning:

```r
library(dplyr)
library(dbplyr)
library(RMariaDB)

conn <- DBI::dbConnect(
  RMariaDB::MariaDB(),
  dbname = DATABASE_NAME
  username = USERNAME,
  password = PASSWORD,
  host = HOST,
  timeout = Inf
)

data <- dplyr::tbl(conn, "distribution_tbl") %>%
  dplyr::filter(Year == 2019) %>%
  dplyr::filter(Type == "Projected") %>%
  dplyr::group_by(Col1, Col2, Col3,  Col4, Col5) %>%
  dplyr::summarise(Proportion = sum(Proportion, na.rm = TRUE),  .groups = "drop") %>%
  dplyr::arrange(dplyr::across(-Proportion)) %>%
  dplyr::mutate(CumProp = cumsum(Proportion) / sum(Proportion, na.rm = TRUE))

random <- stats::runif(1)

random_row <- data %>%
  dplyr::filter(CumProp>= random) %>%
  dplyr::filter(dplyr::row_number() == 1) %>%
  dplyr::select(-Proportion, -CumProp) %>%
  dplyr::collect()
```

The SQL table `distribution_tbl` has 9 columns - `Year` (float), `Type` (varchar), `Col1` (varchar), `Col2` (float), `Col3` (varchar), `Col4` (float), `Col5` (float) and `Proportion` (float)

**Comment by mgirlich** [comment]
Thanks for the example. Two things would help a lot: 1) create a dummy table in the Reprex so that I can actually execute the reprex and 2) if you can boil it down a bit more (e.g. less columns, remove some `filter()` calls, ...).

**Comment by stephenashton-dhsc** [comment]
Thanks for responding - I've tried to simplify the Reprex. It's now returning a slightly different error, but I would hazard a guess that fixing it for the new Reprex will fix it for the old one:

``Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(PARTITION BY `Col1` ORDER BY `Col1` ROWS UNBOUNDED PRECEDING) / SUM(`Proportion' at line 1 [1064]``

```r
library(dplyr)
library(dbplyr)
library(tibble)
library(DBI)
library(RMariaDB)

conn <- DBI::dbConnect(
  RMariaDB::MariaDB(),
  dbname = DATABASE_NAME
  username = USERNAME,
  password = PASSWORD,
  host = HOST,
  timeout = Inf
)

data_tbl <- tibble::tibble(Col1 = 1:5, Proportion = 0.2)

DBI::dbWriteTable(conn, "test_tbl", data_tbl)

data <- dplyr::tbl(conn, "test_tbl") %>%
  dplyr::group_by(Col1) %>%
  dplyr::arrange(dplyr::across(-Proportion)) %>%
  dplyr::mutate(CumulProp = cumsum(Proportion) / sum(Proportion, na.rm = TRUE)) %>%
  dplyr::collect()
```

**Comment by mgirlich** [comment]
Hmm, works for me. Can you post the query produced by `dbplyr`? (use `show_query()` to see the query)

**Comment by stephenashton-dhsc** [comment]
```
<SQL>
SELECT `Col1`, `Proportion`, SUM(`Proportion`) OVER (PARTITION BY `Col1` ORDER BY `Col1` ROWS UNBOUNDED PRECEDING) / SUM(`Proportion`) OVER (PARTITION BY `Col1`) AS `CumulProp`
FROM `test_tbl`
ORDER BY `Col1`
```

**Comment by stephenashton-dhsc** [comment]
Just for completeness, we are also receiving the following warning message, but I do not believe it is relevant:

```
Warning message:
Invalid time zone 'UTC', falling back to local time.
Set the `timezone` argument to a valid time zone.
CCTZ: Unrecognized timezone of the input vector: "" 
```

**Comment by mgirlich** [comment]
The query works for me, so it might really be due to an older version of MariaDB.

**Comment by stephenashton-dhsc** [comment]
Which version of MariaDB are you running? Just so that I can pass the information onto the infrastructure team and (hopefully) get them to upgrade us to a working version!

**Comment by stephenashton-dhsc** [comment]
Actually - I think I've found something on the MariaDB documentation. It looks like window functions such as `PARTITION BY` and `ORDER BY` were only introduced in MariaDB 10.2 - see [here](https://mariadb.com/kb/en/window-functions-overview/).

We should be able to update our version, but could it be worth putting a check within dbplyr for <10.2 versions of MariaDB and either returning an incompatibility error or translating the code differently?

**Comment by hadley** [comment]
From https://mariadb.com/kb/en/changes-improvements-in-mariadb-102/:

> The first stable release was in May 2017, and it will be supported until May 2022.

So not really worth modifying the docs given that it will no longer be supported in <6 months
