### ISSUE TITLE
Postgres function identifiers should be quoted

### ISSUE THREAD

**Issue by dbaston** [tidyverse/dbplyr#711]
Postgres allows the definition of functions that contain special characters, e.g.

```sql
CREATE FUNCTION "is.finite"(x float) RETURNS bool AS '' LANGUAGE plr;
```

I can call the function by quoting its name:

```sql
SELECT "is.finite"('NaN'::float);
```

However, `dbplyr` does not quote function names when constructing queries, so the function is not recognized:

```r
tbl(con, 'iris') %>% mutate(z = is.finite(Sepal.Width))
Error: Failed to prepare query: ERROR:  syntax error at or near "."
LINE 1: ...dth", "Petal.Length", "Petal.Width", "Species", is.finite("S...
```

**Comment by eutwt** [comment]
As a workaround, it looks like double-quoting generates the desired SQL

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

lazy_frame(x = 1, con = simulate_postgres()) %>% 
  mutate(y = '"g"'(x))
#> <SQL>
#> SELECT `x`, "g"(`x`) AS `y`
#> FROM `df`
```

<sup>Created on 2021-10-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately this feels like a pretty unusual case, and I don't think it's worth the time to figure out how to support it. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
