### ISSUE TITLE
Only select necessary columns in nested queries

### ISSUE THREAD

**Issue by ben1787** [tidyverse/dbplyr#725]
Currently when you instantiate a table with tbl(conn,'table_name') it creates a select a, b, c from table_name with all columns referenced.

With a columnar database pulling fewer columns make for a faster query. It would be great both from that perspective and from a clean query perspective, for dbplyr to be able to drop unused columns from the query.

For example: 
table = tbl(conn,'poes')
table %>% 
group_by(id) %>% 
summarise(a = max(username, na.rm=T)) %>% 
sql_render()

<SQL> SELECT "id", MAX("username") AS "a"
FROM (SELECT "tickerexchange", "tickervalue", "confidence", "createddate", "updateddate", "deleted", "username", "fund", "tickernoteid", "currencycode", "createdby", "tickervalueloc", "systemcreateddate", "systemupdateddate", "subfund", "confidenceoverride", "lastfileupdateddate", "islatestrecord", "id", "overridestatus", "convictionoverridereason", "initial_ticker", "system_created_datetime", "client_created_datetime"
FROM quant.dbo.poes) "dbplyr_002"
GROUP BY "id"

Ideally this query should instead look like:
<SQL> SELECT "id", MAX("username") AS "a"
FROM (SELECT "username", "id"
FROM quant.dbo.poes) "dbplyr_002"
GROUP BY "id"

**Comment by mgirlich** [comment]
With the dev version of dbplyr your query already is way shorter. Further optimisations are likely to come this year.
