### ISSUE TITLE
Dates escaped incorrectly in Postgres

### ISSUE THREAD

**Issue by carlganz** [tidyverse/dbplyr#727]
Possibly similar to https://github.com/tidyverse/dbplyr/issues/661 but originally posted here: https://github.com/r-dbi/RPostgres/issues/362

```
library(RPostgres)
# use whatever Postgres connection you have
con <- postgresDefault()
dbplyr::sql_escape_date(con, Sys.Date())
# <SQL> '2021-12-02'
dbQuoteLiteral(con, Sys.Date())
# <SQL> '2021-12-02'::date
```

**Comment by hadley** [comment]
What should it be?

**Comment by carlganz** [comment]
The second one with the explicit date casting is correct. @krlmlr can confirm

**Comment by mgirlich** [comment]
The same is true for other databases and also for datetimes. Maybe we should simply use `dbQuoteLiteral()` for real databases instead of using custom escape functions?

**Comment by hadley** [comment]
@mgirlich yeah, if `dbQuoteLiteral()` is implemented we should use it, but I'm not sure how widespread support is.

**Comment by hadley** [comment]
In general we want to push these sorts of fixes upstream as much as possible, but it's fiddly to make sure everything keeps working for folks regardless of the combination of dbplyr and upstream package installed.

**Comment by hadley** [comment]
I think the easiest fix here would be to supply `sql_escape_date` and `sql_escape_datetime` methods for Postgres that just called `dbQuoteLiteral()`.
