### ISSUE TITLE
Feature request: a version of janitor::make_clean_names / clean_names for dbplyr

### ISSUE THREAD

**Issue by sfirke** [tidyverse/dbplyr#752]
This may be out of scope for dbplyr, and I won't be offended if this issue is closed for that reason.  I'm still a SQL beginner but am now using it everyday at work, and often use dbplyr to work with the database from R.  It has been a huge help, thank you for developing and maintaining it!

I find myself missing `janitor::clean_names()` and having to work with the annoying database column names.  If I knew how to program a dbplyr-style version of it, I would.  But since I don't, I thought I'd come here and ask an expert / the community:

- How hard would it be to write a function like `clean_names` that works in a dbplyr pipeline?
- Is anyone here interested in working on it?
- Would it be in scope for dbplyr?  If not I would be willing to host it in janitor and add dbplyr etc. as dependencies.  Or make some new package `dbjanitor`.

**Comment by mgirlich** [comment]
Actually, you (basically) don't need to know anything about `dbplyr` to create a `clean_names()` method. Knowing `dplyr` is sufficient.

Code for a method

``` r
library(dbplyr)

clean_names.tbl_lazy <- function(x, ...) {
  dplyr::rename_with(x, janitor::make_clean_names, .cols = everything(), ...)
}

memdb_frame(caseID = 1, DOB = 2, Other = 3) %>% 
  janitor::clean_names()
#> # Source:   lazy query [?? x 3]
#> # Database: sqlite 3.37.0 [:memory:]
#>   case_id   dob other
#>     <dbl> <dbl> <dbl>
#> 1       1     2     3
```

<sup>Created on 2022-01-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If you want to add it to `janitor` you should add `dbplyr` as Suggested package and load the method lazily (see https://github.com/tidyverse/dbplyr/blob/main/R/zzz.R).

If you don't want to add it to `janitor` in the end you could simply write

```r
memdb_frame(caseID = 1, DOB = 2, Other = 3) %>% 
  dplyr::rename_with(janitor::make_clean_names)
```

Whether it is out of scope for `dbplyr` is something @hadley should decide.

**Comment by sfirke** [comment]
Whoa awesome, thank you for the explanation! 🙌 I will take this for a spin
and assuming it goes well I can incorporate this into the janitor package.

**Comment by sfirke** [comment]
Hi @mgirlich - I am adding this to janitor now and am stuck on how to use `memdb_frame` in a test.  I posted a question here: https://stackoverflow.com/questions/74952450/how-to-use-memdb-frame-in-an-r-package-test  If you're able to take a look at some point I'd appreciate it.

**Comment by hadley** [comment]
@sfirke you need to suggest RSQLite too.

**Comment by sfirke** [comment]
Thanks @hadley, I got help from @mgirlich over on the janitor repo and this function is now merged into main 🎉   Will be going to CRAN ahead of dplyr 1.1.0.  I'll self-answer that StackOverflow question too to wrap this up.
