### ISSUE TITLE
Extra arguments in explain() do not reach backend specific sql_query_explain -method

### ISSUE THREAD

**Issue by rsund** [tidyverse/dbplyr#783]
Postgres-backend includes a format argument to the [`sql_query_explain` -method](https://github.com/tidyverse/dbplyr/blob/27dec37db0187328ba9080e56603bacc4ec708f9/R/backend-postgres.R#L224-L233). However, that argument never survives to the function, and default value is always used. This is very restrictive for the backends that would benefit for passing arguments to the method.

To demonstrate the issue, the following reprex changes the `sql_query_explain` -method of SQLiteConnection so that the value of the argument becomes visible.

``` r
library(dplyr, warn.conflicts = FALSE)
library(dbplyr, warn.conflicts = FALSE)

# Adding format argument (from Postgres explain) to SQLite explain
sql_query_explain.SQLiteConnection <- function(con, sql, format = "text", ...) {
  dbplyr:::cat_line("Parameter 'format' with value: ", format)
  build_sql("EXPLAIN QUERY PLAN ", sql, con = con)
}
assignInNamespace("sql_query_explain.SQLiteConnection", sql_query_explain.SQLiteConnection, ns = "dbplyr")

con = DBI::dbConnect(RSQLite::SQLite(), ":memory:")
df <- copy_to(con, tibble(x=1))
df %>% explain(format="json") # Value below should be: json
#> <SQL>
#> SELECT *
#> FROM `tibble(x = 1)`
#> 
#> <PLAN>
#> Parameter 'format' with value: text
#>   id parent notused             detail
#> 1  2      0       0 SCAN tibble(x = 1)
DBI::dbDisconnect(con)
```

<sup>Created on 2022-02-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by mgirlich** [comment]
Thanks, `explain()` now passes `...` to `sql_query_explain()`
