### ISSUE TITLE
na_matches='na' SQL causes error for spark

### ISSUE THREAD

**Issue by 001ben** [tidyverse/dbplyr#787]
https://github.com/tidyverse/dbplyr/blob/8a1b7b659e213503b2cdab6be09ad09c7c3e6807/tests/testthat/_snaps/verb-joins.md?plain=1#L56

This SQL when run against spark causes the following error:
```
AnalysisException: "cannot resolve 'CASE WHEN ((LHS.`a` = RHS.`a`) OR ((LHS.`a` IS NULL) AND (RHS.`a`
IS NULL))) THEN 0 ELSE (1 = 0) END' due to data type mismatch: THEN and ELSE expressions should all be
 same type or coercible to a common type...
 ```

I believe the correct SQL expression would be:
```sql
(CASE WHEN (`LHS`.`x` = `RHS`.`x`) OR (`LHS`.`x` IS NULL AND `RHS`.`x` IS NULL) THEN 0 ELSE 1 END = 0)
```
Note: Just moved the `END` for the case when before the `= 0`.

Last time the base function/documentation was changed was in this PR https://github.com/tidyverse/dbplyr/issues/704

**Comment by mgirlich** [comment]
Thanks for reporting this.
