### ISSUE TITLE
Pagination with LIMIT and OFFSET 

### ISSUE THREAD

**Issue by Ada-Nick** [tidyverse/dbplyr#795]
Feature Request.

I'm working on a plumber API and am looking to add pagination to one of my endpoints with LIMIT and OFFSET as described [here](https://www.petefreitag.com/item/451.cfm). 

My database is mysql driven and I connect using a pool.

I expected to be able to build a query that translated to:

```sql

SELECT * FROM iris ORDER BY index LIMIT 2 OFFSET 1

```
I'm unable to build the functionality with current dbplyr functions without building the query with string manipulation. My entire code base uses dbplyr constructed queries and I'd like to maintain that consistency.

```r
library(odbc)
library(DBI)
library(pool)

library(tidyverse) 
library(dbplyr)

con <- pool::dbPool(drv = RSQLite::SQLite(), host = ":memory:")

iris$index = seq(nrow(iris))
dbWriteTable(con, "iris", iris)
iris2 <- tbl(con, "iris")

iris2 %>% 
  select(index, Sepal.Length) %>%
  arrange(index) %>%
  head(n = 2) %>% # expected to add an offset here
  show_query() %>%
  collect() # or expected to add an offset here
```

My work around involved creating a row_number column which I then filter by to get the selected entries.

```r
start = 2
end = 3

iris2 %>% 
  select(index, Sepal.Length) %>%
  arrange(index) %>%
  mutate(row_number = row_number()) %>%
  filter(row_number >= start & row_number <= end) %>%
  select(-row_number) %>%
  show_query()

```
This gives the required output in this case by chance, but ignores the `ORDER BY` part of the query due to the additional `SELECT`. I want my users to be able to collect the pages of entries with a specific order given, hence I can't move the arrange to the end of the pipeline to prevent this.

I also tried a solution described [here](https://stackoverflow.com/questions/57651458/how-to-read-data-from-a-database-by-chunk-in-r). But as I'm using pool I cannot use `sql_render` to easily append to the query, I could checkout a connection but really like the pool handling of my database connections.

This functionality would really help enable R in a production setting I feel. 

Thanks

**Comment by mgirlich** [comment]
Have you considered implementing the pagination differently?
I know there are some general issues with `LIMIT` and `OFFSET` (I quickly googled and found an article from [MariaDB](https://mariadb.com/kb/en/pagination-optimization/#implementation-getting-rid-of-offset)). You could have a look at `DBI::dbFetch()`. An example from the help for fetching in chunks

```r
con <- dbConnect(RSQLite::SQLite(), ":memory:")
dbWriteTable(con, "mtcars", mtcars)

# Fetch in chunks
rs <- dbSendQuery(con, "SELECT * FROM mtcars")
while (!dbHasCompleted(rs)) {
  chunk <- dbFetch(rs, 10)
  print(nrow(chunk))
}

dbClearResult(rs)
```

I don't know much about the `pool` package but I think this should work basically the same way by just using `pool:: dbPool()` instead of `DBI::dbConnect()`.
