### ISSUE TITLE
Bug: can use `distinct()` on removed variable

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dbplyr#803]
The issue exists in the CRAN and the dev version of `dbplyr`.

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

lazy_frame(x = 1, y = 1) %>% 
  select(-x) %>% 
  distinct(x)
#> <SQL>
#> SELECT DISTINCT `x`
#> FROM `df`
```

<sup>Created on 2022-03-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The issue is in `partial_eval_sym()`:

```r
partial_eval_sym <- function(sym, data, env) {
  vars <- op_vars(data)
  name <- as_string(sym)
  if (name %in% vars) {
    sym
  } else if (env_has(env, name, inherit = TRUE)) {
    eval_bare(sym, env)
  } else { # this else clause is the issue
    sym
  }
}
```

Currently, this is needed in three places:

* `across()`: this calls `partial_eval_call()` where we might use `.x` or function arguments.
* `mutate()` with references to previously created variables (this won't be necessary after merging #802).
* one test for `partial_eval()` where this behaviour is explicitly tested ("existing non-variables get inlined"). But this test was only added recently when aligning `partial_eval()` with `dtplyr`, so I think it can be removed.

So, overall I think this can be removed and the evaluation can be made a bit safer.

**Comment by hadley** [comment]
Looks like this would also handle much of #822 (I just confirmed by intuition by replacing the `else` clause with an error).
