### ISSUE TITLE
Return an informative error message when group_by column does not exist

### ISSUE THREAD

**Issue by edonnachie** [tidyverse/dbplyr#818]
When trying to group by a column that does not exist in a table, the following rather cryptic error message is returned:

```
Error in is_missing(x) : 
  promise already under evaluation: recursive default argument reference or earlier problems?
```

No further context is provided, making debugging difficult. A more informative error message would be appreciated. Other functions (select, mutate) seem to handle this error much better (see output below).

A simple REPREX:

```r
library(dbplyr)
library(DBI)

# Create a DB connection
con <- dbConnect()

# Write the iris dataset for testing
dbWriteTable(con name = "IRIS", value = iris)

# Try to group by a non-existant column
tbl(con, "IRIS") |> group_by(NONEXISTANT_COL)
```

Here is my output, using Oracle database:

```
> tbl(db, "IRIS") |> mutate(X = 10 * NON_EXISTANT_COL)
Error in .oci.SendQuery(conn, statement, data = data, prefetch = prefetch,  : 
  ORA-00904: "NON_EXISTANT_COL": invalid identifier

> tbl(db, "IRIS") |> select(NON_EXISTANT_COL)
Error in `stop_subscript()`:
! Can't subset columns that don't exist.
x Column `NON_EXISTANT_COL` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.

> tbl(db, "IRIS") |> group_by(NON_EXISTANT_COL)
Error in is_missing(x) : 
  promise already under evaluation: recursive default argument reference or earlier problems?
```

**Comment by mgirlich** [comment]
Thanks, I fixed this in #821.
I already have something in mind to improve other error messages as well but this is unlikely to happen before the release.

**Comment by edonnachie** [comment]
I'm getting the same error now, when select() contains a column that does not exist (dbplyr v2.3.0, dplyr v1.1.0)

**Comment by mgirlich** [comment]
Please open a new issue with a reprex. And it would be great if you could test whether this still happens in the dev version (install via `devtools::install_github("tidyverse/dbplyr")`).

**Comment by edonnachie** [comment]
A simple reprex suggests that this only occurs when distinct() is called after a more complex query. I'll try to isolate the issue and file an issue if I'm successful.
