### ISSUE TITLE
Running the same tests against multiple backends

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dbplyr#828]
Should we implement a wrapper around `test_that()` that would run the tests with all (registered) backends?

```r
test_that_db(except = "mysql", "some test on the database", {
  df <- memdb_frame(a = 1)
  ...
})
```

This code would run the tests once for each backend, except `"mysql"`, and append the backend to the test description. Calls to `src_memdb()` would return a connection to the test database, `memdb_frame()` should work by extension. In conjunction with #827 we would get snapshots for all supported backends at once.

I see that we can do a lot of testing with lazy frames, these would be "integration tests" that test the generated SQL against the real database.

**Comment by hadley** [comment]
This doesn't seem an obvious win to me; I'd prefer to selectively test backends where we know they are supposed to give different results to the default.
