### ISSUE TITLE
expand() call is translated to LEFT JOIN

### ISSUE THREAD

**Issue by plogacev** [tidyverse/dbplyr#836]
Using `expand(column1, column2)` on a BigQuery table is translated to a LEFT JOIN statement and thus to the following error: 
"LEFT JOIN must have an immediately following ON or USING clause"

If I'm not mistaken, the expression should be translated to a CROSS JOIN. 

I suspect that the translation to a left join may have to do with the fact that the `by` attribute of the resulting structure is `character(0)` and not `NULL`. 

```r
library(tidyverse)
library(bigrquery)
library(dbplyr)
library(DBI)

project_id = ...
dataset_id = ...

con <-  dbConnect(bigquery(), project = project_id, billing = project_id, dataset = dataset_id, use_legacy_sql = FALSE)
table <- tbl(con, "TableName")
table %>% expand(column1, column2) # causes an error
```

**Comment by hadley** [comment]
Can you please provide a reprex along the lines of the one below? This looks ok to me:

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

db <- lazy_frame(x = 1, y = 2, con = simulate_dbi())
db %>% tidyr::expand(x, y)
#> <SQL>
#> SELECT `x`, `y`
#> FROM (
#>   SELECT DISTINCT `x`
#>   FROM `df`
#> ) `LHS`
#> CROSS JOIN (
#>   SELECT DISTINCT `y`
#>   FROM `df`
#> ) `RHS`
```

<sup>Created on 2022-04-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mgirlich** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
