### ISSUE TITLE
tbl(vars = ) still uses SELECT * when rendering

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dbplyr#854]
Working on a fix that involves using `select_query()` in `sql_build.lazy_query_base_remote()`, but this adds extra levels of nesting. I'll review `is_select_trivial()` .

``` r
library(dbplyr)

tbl <- memdb_frame(a = 1)

tbl_fake <- dplyr::tbl(remote_con(tbl), remote_name(tbl), vars = "b")
colnames(tbl_fake)
#> [1] "b"
tbl_fake %>%
  dplyr::show_query()
#> <SQL>
#> SELECT *
#> FROM `dbplyr_001`
tbl_fake
#> # Source:   table<dbplyr_001> [1 x 1]
#> # Database: sqlite 3.38.2 [:memory:]
#>       a
#>   <dbl>
#> 1     1
```

<sup>Created on 2022-04-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by krlmlr** [comment]
The lesson here might bethat the user must be very certain about the correctness of `vars`. My use case was lowercase `vars` when they were stored in uppercase in the (case-insensitive) database.

We could consider explicitly putting all remote tables into their own subquery/CTE with explicit column names, this will give us safer but much longer queries -- with clearer error messages if the underlying table is not what we expect.

``` r
library(dbplyr)

tbl <- memdb_frame(A = 1)
tbl
#> # Source:   table<dbplyr_001> [1 x 1]
#> # Database: sqlite 3.38.2 [:memory:]
#>       A
#>   <dbl>
#> 1     1

sql <- paste0("SELECT a FROM ", remote_name(tbl))
tbl_lc <- dplyr::tbl(remote_con(tbl), sql(sql), vars = "a")

tbl_lc %>%
  dplyr::show_query()
#> <SQL>
#> SELECT a FROM dbplyr_001

tbl_lc
#> # Source:   SQL [1 x 1]
#> # Database: sqlite 3.38.2 [:memory:]
#>       a
#>   <dbl>
#> 1     1
```

<sup>Created on 2022-04-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
I think `vars` is really a developer only feature and something you should only use if you really are certain about the column names. I'm happy to leave a mismatch between supplied and actual names as undefined behaviour.
