### ISSUE TITLE
`cte` support in `collect`.

### ISSUE THREAD

**Issue by randy3k** [tidyverse/dbplyr#861]
The coming version adds CTE support in `show_query`.
Is there any reason why `cte` is not an option in `collect`? I suppose that some backends would be more efficient by reusing expressions with CTE.

cf: #790

**Comment by yutannihilation** [comment]
+1

IMHO, it would be confusing if the actual SQL is different from the one that `show_query()` shows. Maybe dbplyr should have a global option, rather than `cte` argument on each function, to switch the CTE support for consistency?

**Comment by hadley** [comment]
`cte` support is experimental so we haven't yet committed to an interface for turning it on globally.

**Comment by mgirlich** [comment]
I think adding the `cte` argument to `collect()` and `compute()` makes sense but I would also wait for a global option.

**Comment by yutannihilation** [comment]
Yes, I agree with you it's not the time. But, `collect()` might be executed inside other functions (e.g. `ggplot2::fortify()`) and the user cannot always pass `cte = TRUE` in those cases, so I think the preference should be stored in somewhere (a global option, or in the `tbl` object?) somehow.
