### ISSUE TITLE
Default variable names use backticks

### ISSUE THREAD

**Issue by hadley** [tidyverse/dbplyr#868]
They used to use `"`. I'm not sure if this change was deliberate, but if so we need to update https://dbplyr.tidyverse.org/articles/translation-function.html#basic-differences

**Comment by hadley** [comment]
Somewhat related, it would be nice to have someway to suppress the default variable quoting all together for teaching as it makes the generated SQL closer to what you'd write by hand (and in simple teaching examples it's unlikely to generate invalid SQL).

**Comment by hadley** [comment]
Ah got it, thanks. I'll update the vignette at some point.

Maybe we should start some options data structure that you can set in `tbl()` in order to control the SQL generation? That's also where you could opt-in to CTEs.

**Comment by hadley** [comment]
Identifier escaping is done by `sql_escape_ident()` which takes `con` and a character vector of identifiers. Threading down options from the `tbl` is going to be complicated, so maybe it's better to create some new `simulate_teaching()` that is mostly identical to `simulate_dbi()` except for its `sql_escape_ident()` method?

**Comment by mgirlich** [comment]
Or maybe don't escape identifiers if it doesn't seem necessary, e.g. if it only contains lower case a to z and no spaces. This is easy to check and should still always work.

**Comment by hadley** [comment]
@mgirlich the problem is the reserved words, which varies from database to database.
