### ISSUE TITLE
Incorrect translation of dplyr verbs involving use of across() inside filter()

### ISSUE THREAD

**Issue by andreassoteriadesmoj** [tidyverse/dbplyr#869]
Here's an interesting one. When `dplyr::across()` is used inside `dplyr::filter()`, it seems like `dbplyr` (v. 2.1.1) gets somehow confused and assigns a name to the filtering operation in the translated SQL script.

I have prepared an example below. I'm sorry that it's not reproducible, but I'm working with databases on a private server.

**Incorrect translation:**
```
some_table_field <- 'field1'

dplyr::show_query(
    some_tbl_object %>% 
        dplyr::filter(
            dplyr::across(
                dplyr::all_of(some_table_field),
                ~ !is.na(.)
            )
        )
)
```

The above returns an SQL script where the last line is a filtering combination that is assigned the name of the field:

```
<SQL>
SELECT *
FROM (SELECT *
FROM "some_database"."some_table") "q01"
WHERE (NOT((("offender_id") IS NULL)) AS "offender_id")
```

However, if we manually specify the field we want to filter by in `dplyr::filter()`, the translation is correct.

Unsurprisingly, running

```
some_tbl_object %>% 
        dplyr::filter(
            dplyr::across(
                dplyr::all_of(some_table_field),
                ~ !is.na(.)
            )
        )
```

returns this error:

```
Error: InvalidRequestException (HTTP 400). line 4:39: mismatched input 'AS'. Expecting: <expression>
```

**Correct translation:**

```
dplyr::show_query(
    some_tbl_object %>% 
        dplyr::filter(!is.na('field1'))
)

#<SQL>
#SELECT *
#FROM (SELECT *
#FROM "some_database"."some_table") "q01"
#WHERE (NOT((('offender_id') IS NULL)))
```

**Comment by mgirlich** [comment]
This is fixed in the dev version.
