### ISSUE TITLE
Consider support for `HAVING` clause?

### ISSUE THREAD

**Issue by hadley** [tidyverse/dbplyr#870]
Low priority, but it would be nice to avoid the subquery if you do a `filter()` after a `summarise()`.

**Comment by mgirlich** [comment]
I gave this some thought and toyed around a little with `HAVING`. I think the scope of it is quite limited but still useful.
From the [Postgres documentation](https://www.postgresql.org/docs/current/sql-select.html#SQL-HAVING)

> Each column referenced in condition must unambiguously reference a grouping column, unless the reference appears within an aggregate function or the ungrouped column is functionally dependent on the grouping columns.

So, the SQL query must look like

```sql
SELECT <grouping columns>, <aggregated columns>
GROUP BY <grouping columns>
HAVING ...
```

and with dplyr verbs I think this can only be achieved via

1. `summarise() + filter()`

```r
df %>% 
  group_by(<grouping columns>) %>% 
  summarise(<aggregated columns>) %>% 
  filter(<condition>)
```

where `<condition>` may only refer to `<grouping columns>` and `<aggregated columns>`. E.g.

```r
lazy_frame(g = 1, x = 1, y = 1) %>% 
  group_by(g) %>% 
  summarise(x_mean = mean(x)) %>% 
  filter(x_mean > 1, g == 1)
```

And one cannot use `x` or `y` in `filter()` (though in SQL this would be possible).
This case should be relatively simple. It could be done directly in `add_filter()` but also later in `sql_optimise()` (though this is probably a bit more difficult).

2. `filter() + summarise()`

```r
lazy_frame(g = 1, x = 1, y = 1) %>% 
  group_by(g) %>% 
  filter(sum(x) > 1, mean(y) == 1, g == 1) %>% 
  summarise(x_mean = mean(x))
```

Now, it is also possible to use `x` and `y` in `filter()` if they are both used in an aggregate function. This can be done in `add_summarise()` or in `sql_optimise()`.

@hadley Do you think these are all cases where `HAVING` can be used?

**Comment by hadley** [comment]
Yeah, I think that's right.

We could also consider supporting `QUALIFY` at the same time. I know less about whether it's supported in most databases, but it does a similar thing but for filtering the result of window functions (i.e. it would be useful for `summarise()` after a grouped `mutate()`). Again, not terribly important, but if it fit in the same framework as `HAVING` it might make implementing both slightly more worthwhile.

**Comment by mgirlich** [comment]
I never heard of `QUALIFY` before but I already missed such a functionality a couple of times 😞  Some quick googling suggested support in Snowflake, Teradata, BigQuery, and DuckDB. Unfortunately, no support (yet?) in Postgres and SQLite. I'll give it a try and see whether it is easy enough to add.

**Comment by mgirlich** [comment]
The `summarise()` + `filter()` case is done via #877.
The `filter()` + `summarise()` case requires undoing the substitutions for the window functions done in `filter()`. This is doable but does not feel worth it currently. In case someone (e.g. future me) actually wants to have a go at this:

* check that `lazy_query$last_op` is `"filter"`
* check that `lazy_query$select` is trivial
* check that all columns used in `filter()` are either grouping columns or aggregated
* undo the substitutions from `filter()`
* remove `lazy_query$where` and use `lazy_query$having` instead
