### ISSUE TITLE
Simplify `copy_inline()` using column aliases

### ISSUE THREAD

**Issue by hadley** [tidyverse/dbplyr#893]
eg. 
```sql
SELECT CAST(`x` AS INTEGER) AS `x`, CAST(`y` AS TEXT) AS `y`
FROM 
  (VALUES (1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e')) AS inline(x, y)
```

At least duckdb and postgresl support this (although SQLite does not). Postgres calls it a "column alias list", the [SQL standard](http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt) calls it "derived column list".

**Comment by mgirlich** [comment]
From [modern-sql](https://modern-sql.com/use-case/naming-unnamed-columns)

> Even though from aliases were already required for [intermediate SQL-92](https://modern-sql.com/feature/table-column-aliases) and became mandatory in SQL:1999, with is nevertheless better supported:

With SQL I often wonder why there is a standard when people don't even want to use it...
