### ISSUE TITLE
`sd()` should accept `na.rm` argument

### ISSUE THREAD

**Issue by hadley** [tidyverse/dbplyr#899]
For consistency with the other aggregation functions.

I think we could also consider warning about `na.rm` once per session for all aggregation functions, rather than once per session for each aggregation function. And that way we could take advantage of `warn()`'s `frequency` and `frequency_id` arguments, rather than hand rolling it.

**Comment by hadley** [comment]
Maybe `sd()` is common enough that we should provide a default translation that errors.

**Comment by krlmlr** [comment]
This will be closed with the PR.

Should the default translation be `SQRT(VAR(...))` ?

**Comment by hadley** [comment]
@krlmlr I don't think `VAR` is any more widely available. We could translate to `SUM(AVG(POW(x - AVG(x), 2))) / (COUNT(x) - 1)`?
