### ISSUE TITLE
Should strict_sql also error on unknown variables?

### ISSUE THREAD

**Issue by hadley** [tidyverse/dbplyr#905]
``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

options(dplyr.strict_sql = TRUE)

lazy_frame(x = 1) |> 
  mutate(z = foo(x))
#> Error in `foo()`:
#> ! Don't know how to translate `foo()`
```

<sup>Created on 2022-05-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

But 

``` r
library(dbplyr)
library(dplyr, warn.conflicts = FALSE)

options(dplyr.strict_sql = TRUE)

lazy_frame(x = 1) |> 
  mutate(z = x + y)
#> <SQL>
#> SELECT *, `x` + `y` AS `z`
#> FROM `df`
```

<sup>Created on 2022-05-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mgirlich** [comment]
What is the use case of **not** erroring on unknown variables? If there are any, then this should be a separate option.

This is also related to #803, https://github.com/tidyverse/dbplyr/pull/792#issuecomment-1137835401, and #822.

I started working on this and this will help to greatly improve error messages 😄
