### ISSUE TITLE
not working with bigrquery

### ISSUE THREAD

**Issue by ewright-vcan** [tidyverse/dbplyr#910]
I'm new to bigrquery and dbplyr. I just started learning when I came to notice some errors posted on the bigrquery GitHub. There have been no answers, so I thought I would check here but there has been nothing posted. 

The two descriptions can be shown: [#495](https://github.com/r-dbi/bigrquery/issues/495), and [#492](https://github.com/r-dbi/bigrquery/issues/492).

Hopefully we can get this fixed so I can keep learning :) Thanks!

**Comment by mgirlich** [comment]
I created a [PR for bigrquery](https://github.com/r-dbi/bigrquery/pull/503) that fixes the issue. As this is a bigrquery issue I'm already closing this here.

**Comment by mgirlich** [comment]
> Hopefully we can get this fixed so I can keep learning :) Thanks!

Hope this didn't stop you from learning 😄
