### ISSUE TITLE
error with `tidyr::complete(data, year = 2010:2020)` syntax

### ISSUE THREAD

**Issue by eitsupi** [tidyverse/dbplyr#911]
It seems that `tidyr::complete(data, year = 2010:2020)` syntax, which completes a specific column with a vector, is not interpreted correctly by dbplyr.

``` r
df <- data.frame(
    col1 = c(1, 3, 4),
    col2 = letters[1:3]
)

df |>
    tidyr::complete(col1 = 1:4)
#> # A tibble: 4 × 2
#>    col1 col2
#>   <dbl> <chr>
#> 1     1 a
#> 2     2 <NA>
#> 3     3 b
#> 4     4 c

df |>
    dbplyr::tbl_memdb() |>
    tidyr::complete(col1 = 1:4) |>
    dplyr::collect()
#> Error: row value misused
```

<sup>Created on 2022-06-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mgirlich** [comment]
Closing as there is already an issue #720 for the underlying problem. Unfortunately, it is not that easy to solve.
