### ISSUE TITLE
Error when summarizing

### ISSUE THREAD

**Issue by Janlow** [tidyverse/dbplyr#912]
Hello, I have been working with dbplyr for several years connecting to an Oracle database and it has been great. However I just updated some packages to the latest version and now I am getting the following error specifically when using summarize: 

```
Error in app$vspace(new_style$`margin-top` %||% 0) : 
  attempt to apply non-function
```

I can filter, select, group and join just as before. Here is my sessionInfo:

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252    LC_MONETARY=Swedish_Sweden.1252 LC_NUMERIC=C                    LC_TIME=Swedish_Sweden.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] cli_3.3.0       pool_0.1.6      lubridate_1.8.0 dbplyr_2.2.0    DBI_1.1.2       odbc_1.3.3      forcats_0.5.1   stringr_1.4.0   dplyr_1.0.9     purrr_0.3.4    
[11] readr_2.1.2     tidyr_1.2.0     tibble_3.1.7    ggplot2_3.3.6   tidyverse_1.3.1 plumber_1.1.0  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3      prettyunits_1.1.1 ps_1.7.0          assertthat_0.2.1  digest_0.6.29     utf8_1.2.2        R6_2.5.1          cellranger_1.1.0 
 [9] backports_1.4.1   reprex_2.0.1      httr_1.4.3        pillar_1.7.0      rlang_1.0.2       readxl_1.4.0      rstudioapi_0.13   callr_3.7.0      
[17] blob_1.2.3        DT_0.23           webutils_1.1      htmlwidgets_1.5.4 bit_4.0.4         munsell_0.5.0     tinytex_0.39      broom_0.8.0      
[25] httpuv_1.6.5      compiler_4.0.2    modelr_0.1.8      xfun_0.31         pkgconfig_2.0.3   pkgbuild_1.3.1    htmltools_0.5.2   tidyselect_1.1.2 
[33] fansi_0.4.1       crayon_1.5.1      tzdb_0.3.0        withr_2.5.0       later_1.3.0       grid_4.0.2        jsonlite_1.8.0    gtable_0.3.0     
[41] lifecycle_1.0.1   magrittr_2.0.3    scales_1.2.0      stringi_1.7.6     swagger_3.33.1    fs_1.5.2          promises_1.2.0.1  xml2_1.3.3       
[49] ellipsis_0.3.2    generics_0.1.2    vctrs_0.4.1       tools_4.0.2       bit64_4.0.5       glue_1.4.2        hms_1.1.1         processx_3.5.3   
[57] rsconnect_0.8.26  fastmap_1.1.0     colorspace_2.0-3  rvest_1.0.2       haven_2.5.0      

```

Is this a known issue?

**Comment by mgirlich** [comment]
Can you please make a reprex following the advice in https://dbplyr.tidyverse.org/articles/reprex.html?

**Comment by mgirlich** [comment]
The error message you see is not very helpful. A quick googling suggests you are using VSCode. In [this stackoverflow comment](https://stackoverflow.com/questions/71974812/query-works-in-sql-server-but-not-in-r/72002483#72002483) they suggested installing the cli package. Try that or use R via a different IDE (e.g. RStudio). Then you might get a more helpful error message.

I'm pretty sure there is nothing wrong with dbplyr. It might be the case that reinstalling dbplyr helps with your problems. Or you could try

```r
library(dplyr)
library(dbplyr)
mf <- memdb_frame(g = c(1, 1, 2, 2, 2), x = 1:5, y = 5:1)

mf %>%
  summarise(sum = sum(x, na.rm = TRUE))
```

to see whether the warning about missing values being removed in SQL  aggregation functions was turned into an error for you.

**Comment by Janlow** [comment]
Some updates regarding this. I am using RStudio and have the latest version of the cli package so that is not the issue. Summarizing worked when adding the na.rm = TRUE part, so that is great. I also roll backed to dbplyr version 2.1.0 and found that it worked without the na.rm = TRUE part, instead there was only a warning message:
```
Warning message:
Missing values are always removed in SQL.
Use `SUM(x, na.rm = TRUE)` to silence this warning
This warning is displayed only once per session. 
```
However, there seems to be some Oracle specific problems with dbplyr 2.2.0 that I can not recreate using memdb_frame. Using dbplyr 2.1.0 everything works as expected but I am having some errors with the exact same code using dbplyr 2.2.0. Is it possible to create an Oracle specific memdb_frame or something similar? In that case I could show you some examples.

**Comment by mgirlich** [comment]
Your messages confuse me... To clear this up:

1) Does your reprex from above (yes, with `memdb_frame()`)

```r
mf <- memdb_frame(g = c(1, 1, 2, 2, 2), x = 1:5, y = 5:1)

mf %>%
  summarize(sum = sum(x))
```

work with dbplyr 2.2.0 after a Restart? If not, what kind of error do you get?

2) Can you create a reprex for Oracle? If possible, use `lazy_frame(..., con = simulate_oracle())`. Otherwise, try to use `copy_to()` to create the table in the database. Please use the [reprex](https://reprex.tidyverse.org/) and post the results here.

**Comment by Janlow** [comment]
1. With dbplyr 2.1.0:
```
library(dbplyr)
library(dplyr)

mf <- memdb_frame(g = c(1, 1, 2, 2, 2), x = 1:5, y = 5:1)

mf %>%
  summarize(sum = sum(x))
```
Gives output:
```
# Source:   lazy query [?? x 1]
# Database: sqlite 3.38.5 [:memory:]
    sum
  <int>
1    15
Warning message:
Missing values are always removed in SQL.
Use `SUM(x, na.rm = TRUE)` to silence this warning
This warning is displayed only once per session. 
```
With dbplyr 2.2.0:
```
library(dbplyr)
library(dplyr)

mf <- memdb_frame(g = c(1, 1, 2, 2, 2), x = 1:5, y = 5:1)

mf %>%
  summarize(sum = sum(x))
```
Gives output:
```
Error in app$vspace(new_style$`margin-top` %||% 0) : 
  attempt to apply non-function
```
However, this works:
```
library(dbplyr)
library(dplyr)

mf <- memdb_frame(g = c(1, 1, 2, 2, 2), x = 1:5, y = 5:1)

mf %>%
  summarize(sum = sum(x, na.rm = TRUE))
```
Which gives:
```
# Source:   SQL [1 x 1]
# Database: sqlite 3.38.5 [:memory:]
    sum
  <int>
1    15
```

For the Oracle part I will try and make a reprex, I will get back to you.

**Comment by mgirlich** [comment]
The error message you see comes from the cli package and the code works for me. So, I guess the issue is either in cli or on your computer.

1) Please **reinstall** the cli package and check if the error still happens.
2) Does the following work for you?

```r
check_na_rm <- function(na.rm) {
  if (identical(na.rm, TRUE)) {
    return()
  }

  cli::cli_warn(
    c(
      "Missing values are always removed in SQL aggregation functions.",
      "Use {.code na.rm = TRUE} to silence this warning"
    ),
    .frequency = "regularly",
    .frequency_id = "dbplyr_check_na_rm"
  )
}
check_na_rm(FALSE)
```

3) If the error still occurs: Can you upgrade your R version to 4.2.0 and try again?

**Comment by Janlow** [comment]
I had the latest version of cli 3.3.0 already installed but I reinstalled and now it works with dbplyr 2.2.0 as well, thanks! A bit strange to me that failure of posting a warning message yields an error though... I will get back to you regarding the Oracle issues! :)

**Comment by Janlow** [comment]
Okay here is some of the troubles I am experiencing with dbplyr 2.2.0 and Oracle. Might be a long post since it is hard to recreate fully working with databases. The first part is dbplyr 2.2.0 and the second part is with functioning dbplyr 2.1.0 to mark the differences. 

dbplyr 2.2.0:

I have a very simple Oracle dataframe called df.

```
library(dplyr)
library(dbplyr)

df
# Source:   lazy query [?? x 2]
# Database: Oracle 
  <dbl> <chr>
1  1001 x    
2  1002 y    
3  1003 z    
4  1004 w    

df %>%
  summarize(sum = sum(ID))

```

**Comment by Janlow** [comment]
After some further investigating I conclude that it was the cli package causing this issue, dbplyr 2.2.0 seems fine with Oracle! However there could be a further discussion if the failure of sending a warning message should result in an error or not, but maybe that is R-related and not package specific. Thanks for your help!

**Comment by nFrechen** [comment]
For me installing glue 1.6.2 resolved the issue. It is used in cli 3.3.0 to output messages with inline markup. And I think that was the problem.
