### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by ehudtr7** [tidyverse/dbplyr#915]
We use dbplyr through sparklyr.
When we moved to dbplyr version 2.2.0 we got a failure during execution of a code which previously worked fine, while getting the following error message: 
"Error in dbi_ensure_no_backtick(x) : Can't escape back tick from string"
It happens when we sprarklyr::collect a spark data frame after some dplyr::anti_join operation.
We workaround it by applying sprarklyr::collect to each of the two data frames and then do the dplyr::anti_join on the resulted R data frames, instead of anti_join the original spark data frames.

**Comment by mgirlich** [comment]
@ehudtr7 I have added a PR that fixes the `semi_join()` and `anti_join()` issues with Spark. Until the CRAN release of dbplyr you can install it via

```r
remotes::install_github(
  "tidyverse/dbplyr",
  ref = "anti-join-sparklyr-issue"
)
```
