### ISSUE TITLE
MS SQL mutate(ifelse()) translation not working

### ISSUE THREAD

**Issue by bogdanrau** [tidyverse/dbplyr#93]
I'm running into an issue when using mutate and ifelse (or if) on a SQL Server backend. The following sample query:

```
df <- tbl(con, in_schema("schema", "table_name")) %>%
   mutate(field = ifelse(field %in% c('test1', 'test2', 'test3'), 'string1', 'string2') %>%
   collect()
```

... will give the following translation:
```
SELECT CASE WHEN (("field" IN ('test1', 'test2', 'test3')) = 'TRUE') THEN ('string1') 
            WHEN (("field" IN ('test1', 'test2', 'test3')) =  'FALSE') THEN ('string2') 
            END AS "field"
```

Which will return an error. The correct translation should be:
```
SELECT CASE WHEN ("field" IN ('test1', 'test2', 'test3')) THEN 'string1' 
            WHEN ("field" NOT IN ('test1', 'test2', 'test3')) THEN 'string2' 
            END AS "field"
```

Will correcting this in the mssql_if function create any issues in other queries, or is there a better way to do mutate(ifelse()) in mssql?

https://github.com/tidyverse/dbplyr/blob/477480e3c488fe6338ce5f142142d280dd61487b/R/db-odbc-mssql.R#L225

**Comment by bogdanrau** [comment]
Sorry guys. Just opened up a ticket in dplyr instead (as suggested in the readme). Closing this guy.

**Comment by hadley** [comment]
No you should file here; I need to update the readme.

**Comment by bogdanrau** [comment]
Thanks Hadley. @edgararuiz, any insight on what a fix might be?

**Comment by edgararuiz** [comment]
Ok, I think that the update may have to be done in the negating function here: 

https://github.com/tidyverse/dbplyr/blob/477480e3c488fe6338ce5f142142d280dd61487b/R/db-odbc-mssql.R#L183

I'll work on a PR for this

**Comment by edgararuiz** [comment]
Quick update, it looks like your suggestion fixes this issue, but it negatively impacts the custom MS SQL infix function we're using, so I have to work some more on this

https://github.com/tidyverse/dbplyr/blob/477480e3c488fe6338ce5f142142d280dd61487b/R/db-odbc-mssql.R#L194

**Comment by bogdanrau** [comment]
Thanks for your help on this @edgararuiz! We're transitioning from a MySQL db to MSSQL and it's been super smooth thus far minus this kink.

**Comment by edgararuiz** [comment]
@ablack3 - Yes, I have a PR that fixes it.  The PR is ready to be reviewed: https://github.com/tidyverse/dbplyr/pull/103
