### ISSUE TITLE
Warning to update PostgreSQL Connection Package

### ISSUE THREAD

**Issue by rohitg33** [tidyverse/dbplyr#932]
Hi, I'm trying to update to the latest version of dbplyr, and I use RPostgreSQL to connect to postgres. Both of the packages are fully updated, but I get this warning message whenever I restart the system and read a new table: 

"Warning message:
PostgreSQLConnection uses an old dbplyr interface
i Please install a newer version of the package or contact the maintainer"

**Comment by mgirlich** [comment]
We don't support the 2nd dbplyr edition for RPostgreSQL. You could use the RPostgres package instead which is fully supported by us.
