### ISSUE TITLE
Error with group_by and across in version 2.2.1

### ISSUE THREAD

**Issue by gbouzill** [tidyverse/dbplyr#937]
In version 2.2.1, using across after a group_by expression gives the following error : 

```r
library(dbplyr)
library(dplyr)

mf <- memdb_frame(ID = 1:5, b = 1:5, c = 10:6)

mf %>% 
  group_by(ID) %>% 
  summarise(across(-ID,  ~ min(.x, na.rm = TRUE)))
```
> Error in `chr_as_locations()`:
> ! Can't subset columns that don't exist.
> ✖ Column `ID` doesn't exist.
> Run `rlang::last_error()` to see where the error occurred.

I believe this is related to what is mentioned in the across help page : 
> Because across() is used within functions like summarise() and mutate(), you can't select or compute upon grouping variables.  

But the previous code worked in version 2.1.0.
I think the error message should be more expressive.

**Comment by mgirlich** [comment]
The behaviour and error is the same as for data frames. Please open an issue in the dplyr repository instead.
