### ISSUE TITLE
dbplyr SQL translation issues with Oracle

### ISSUE THREAD

**Issue by NZambranoc** [tidyverse/dbplyr#939]
This is still an issue with Oracle SQL since it doesn't allow bare asterisks when other columns are explicitly on the select clause.

Using ROracle to connect to the OCI.
dbplyr version: 2.20

_Originally posted by @NZambranoc in https://github.com/tidyverse/dbplyr/issues/319#issuecomment-1188243295_

**Comment by mgirlich** [comment]
Do you use the newest version of dbplyr (i.e. 2.2.1)? And how do connect to the database? Via odbc?

**Comment by NZambranoc** [comment]
@mgirlich  I connect using ROracle to connect to the OCI. The dbplyr version is  2.20

**Comment by mgirlich** [comment]
Closing this issue because this is already fixed in 2.2.1. In case you still have the same issue I'm happy to reopen this.

**Comment by NZambranoc** [comment]
@mgirlich updated my dbplyr version, the queries work fine now. 💓
