### ISSUE TITLE
2.2.0 SQL Generation incompatible with Teradata

### ISSUE THREAD

**Issue by But2ene** [tidyverse/dbplyr#966]
As described in #908 for Oracle, Teradata is not compatible with the new SQL generation for `*`.

```r
tbl(db, "my_table") %>%
  mutate(
    new_col = "any_value"
  ) %>% show_query()
```
which outputs a not-compatible Teradata query
```sql
<SQL>
SELECT
  *,
  'any_value' AS new_col
FROM "my_table"
```
when executed without `show_query`, the folowing error appears
```
Error in new_result(connection@ptr, statement, immediate) : 
  nanodbc/nanodbc.cpp:1594: 42000: [Teradata][ODBC Teradata Driver][Teradata Database](-3706)Syntax error: SELECT * must have a FROM clause.
```

Thank you for your hard work :) It really useful at my job.

**Comment by mgirlich** [comment]
@But2ene  I have added a PR that hopefully fixes the issues with Teradata. It would be great if you could install it via

```r
remotes::install_github(
  "tidyverse/dbplyr",
  ref = "teradata-cannot-select-star"
)
```

and give feedback whether this solves your dbplyr issues with Teradata.

**Comment by hadley** [comment]
(@mgirlich btw you can also do `remotes::install_github("tidyverse/dbplyr#968")`)

**Comment by But2ene** [comment]
The code below doesn't work in 2.2.1 and **it works** in the fix you have written

```r
db <- DBI::dbConnect(odbc::odbc(), dsn = "****", encoding = "latin1")

DBI::dbExecute(
  db, 
  "
  create multiset volatile table test, no log (
    my_variable INTEGER NOT NULL
  ) PRIMARY INDEX (my_variable)
  on commit preserve rows
  ")

library(dplyr)
tbl(db, "test") %>% 
  mutate(new_col = "any_value") %>%
  collect()
```
Sounds good to me :)
