### ISSUE TITLE
fill() not working with tbl_MoJAthenaConnection object

### ISSUE THREAD

**Issue by andreassoteriadesmoj** [tidyverse/dbplyr#967]
Hi,

I am having trouble running verb `tidyr::fill` with `dbplyr`. I am working with sensitive data, so apologies for lack of a reprex.

Consider that `df` is a `tbl_MoJAthenaConnection` object. Columns ID, B & C are, respectively, numeric, character and character.

```
df %>%
    dplyr::group_by(ID, B) %>%
    dplyr::arrange(C, .by_group = TRUE) %>%
    tidyr::fill(C, .direction = 'down') %>%
    dplyr::ungroup()

Error: InvalidRequestException (HTTP 400). line 82:34: mismatched input 'IGNORE'. Expecting: ',', <expression>
```

I looked for hints in the SQL code using `dbplyr::sql_render(df)` and found that this bit:

```
LAST_VALUE("C" IGNORE NULLS) OVER (PARTITION BY "ID", "B" ORDER BY "ID", "B", "C") AS "C"
```

may need to be rewritten as

```
LAST_VALUE("C") IGNORE NULLS OVER (PARTITION BY "ID", "B" ORDER BY "ID", "B", "C") AS "C"
```

(i.e. move `IGNORE NULLS` outside the parentheses). Could you check?

Thanks

**Comment by mgirlich** [comment]
We don't support MoJAthenaConnection. The package owner has to add a method for `last_value_sql()`. Something like

```r
#' @export
`last_value_sql.MoJAthenaConnection` <- function(con, x) {
  build_sql("LAST_VALUE(", ident(as.character(x)), ") IGNORE NULLS", con = con)
}
```
