### ISSUE TITLE
copy_inline() not working on oracle backends

### ISSUE THREAD

**Issue by bthe** [tidyverse/dbplyr#972]
This is basically a repeat of the issues listed in https://github.com/tidyverse/dbplyr/issues/950, but for Oracle backends.

```
copy_inline(con, tibble(a=c(1,1), b=c(2,3)))
```
> Error in .oci.SendQuery(conn, statement, data = data, prefetch = prefetch,  : 
>  ORA-00903: invalid table name

As for the Hana DB it seems the `values` command does not yield the desired result and you need use `union all ` in combination with selecting from `dual` in the query. So instead of the previous query this works:

```
SELECT CAST("a" AS NUMBER) AS "a", CAST("b" AS NUMBER) AS "b"
FROM (
  (
    SELECT NULL AS "a", NULL AS "b"
    FROM dual 
    WHERE (0 = 1)
  )
  UNION ALL
  (select 1.0, 2.0 from dual union all select 1.0, 3.0 from dual)
) "values_table"

```

**Comment by bthe** [comment]
It seems that the `FROM DUAL` is required, at least:
```
SELECT NULL AS "a", NULL AS "b"
    FROM () 
    WHERE (0 = 1)
```
fails whereas
```
SELECT NULL AS "a", NULL AS "b"
    FROM DUAL
    WHERE (0 = 1)
```
yields the expected results.

**Comment by mgirlich** [comment]
Thanks, indeed the `FROM DUAL` is necessary. I updated the PR and it should work now. Would be great if you could confirm 😄

**Comment by bthe** [comment]
Almost there, the generated query still has `()` in the definition clause (line 5 below):

```
SELECT CAST("a" AS NUMBER) AS "a", CAST("b" AS NUMBER) AS "b"
FROM (
  (
    SELECT NULL AS "a", NULL AS "b"
    FROM () 
    WHERE (0 = 1)
  )
  UNION ALL
  (
    SELECT 1.0, 2.0 FROM DUAL UNION ALL 
    SELECT 1.0, 3.0 FROM DUAL
  )
) "values_table"
```

**Comment by mgirlich** [comment]
Ah, thanks. This is now fixed as well.
