### ISSUE TITLE
feature request: Turn keyword highlighting off

### ISSUE THREAD

**Issue by eutwt** [tidyverse/dbplyr#974]
I'd like keyword highlighting, but the dark blue is hard to read with a dark grey background. Would be nice if the option allowed specifying a color, but failing that I'd like to be able to turn it off.

``` r
library(dplyr, w = F)
library(testthat, w = F)
#> Warning: package 'testthat' was built under R version 4.1.2
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
copy_to(con, mtcars)
mtcars2 <- tbl(con, "mtcars")

local_reproducible_output(crayon = TRUE)
options(dbplyr_use_colour = FALSE)

mtcars2 %>% 
  select(mpg) %>% 
  show_query()
#> <SQL>
#> [34mSELECT[39m `mpg`
#> [34mFROM[39m `mtcars`
```

<sup>Created on 2022-08-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

My workaround for now is below, but it would be nice if there was an option 

```{r}
style_kw <- function(x) {
  if (dbplyr:::dbplyr_use_colour()) {
    # use `br_blue` which is more legible for a dark theme
    cli::col_br_blue(x)
  } else {
    x
  }
}
 
assignInNamespace(
  "style_kw", 
  style_kw,
  asNamespace("dbplyr")
)
 ```

**Comment by eutwt** [comment]
After looking at the code, this problem is solved for me personally by manually changing `syle_kw()` as below, but leaving the issue up because I suspect an option to disable or modify the color is useful to others using a dark theme.
```{r}
assignInNamespace("style_kw", cli::col_br_cyan, asNamespace("dbplyr"))
```

**Comment by mgirlich** [comment]
Totally makes sense! 👍
