### ISSUE TITLE
`show_query()` could inform about option `dbplyr_highlight`

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/dbplyr#995]
We recently added the option `dbplyr_highlight` to control how keywords should be highlighted. We didn't find a good place to document this option so that users could find it. Then I wondered whether `show_query()` could inform about this option:

* every 8 hours
* if the option is not used (though this might not even be necessary b/c `show_query()` really only makes sense in interactive use and compared to an SQL query the info is quite minor)

**Comment by hadley** [comment]
I think messaging about it is probably a bit too aggressive, since the default will work for most people (especially as we make changes in RStudio to ensure that the ANSI colors have good contrast in more themes).
