### ISSUE TITLE
`indexes` parameter is not documented in `copy_to`

### ISSUE THREAD

**Issue by kongdd** [tidyverse/dbplyr#996]
In the vignettes, 
<https://cran.r-project.org/web/packages/dbplyr/vignettes/dbplyr.html>
```R
copy_to(con, nycflights13::flights, "flights",
  temporary = FALSE, 
  indexes = list(
    c("year", "month", "day"), 
    "carrier", 
    "tailnum",
    "dest"
  )
)
```
However, `indexes` parameter is not documented in the `copy_to` function.

**Comment by mgirlich** [comment]
It is not documented in the generic `dplyr::copy_to()` but in the method `dplyr::copy_to.src_sql()`. Unfortunately, this is harder to find but some arguments do not make sense in the generic.
