### ISSUE TITLE
names() method for tbl_* objects?

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/dbplyr#997]
Copying from the dbplyr vignette:

```r
library(dplyr)
con <- DBI::dbConnect(RSQLite::SQLite(), dbname = ":memory:")

copy_to(con, nycflights13::flights, "flights",
  temporary = FALSE, 
  indexes = list(
    c("year", "month", "day"), 
    "carrier", 
    "tailnum",
    "dest"
  )
)

flights_db <- tbl(con, "flights")
```

The `names()` here is not what I'd expect:

```r
class(flights_db)
# [1] "tbl_SQLiteConnection" "tbl_dbi"              "tbl_sql"              "tbl_lazy"             "tbl" 
names(flights_db)
# [1] "src"        "lazy_query"
```

I would have expected `names()` to give the column names (which `colnames()` does). Maybe I am not understanding the `tbl_*` class for remote connections, but `src/lazy_query` seem implementation detail-y to me.

Should we add a `names.tbl_lazy` (or other class) method to match my instinct here?

**Comment by mgirlich** [comment]
Probably makes sense as this mistake happened even a couple of times in dplyr code. Do you want to create a PR?

**Comment by MichaelChirico** [comment]
sure... I'll rely on your judgement for which class the method should be
for, exactly, WDYT?

**Comment by MichaelChirico** [comment]
Closing as superseded by #1010
