### ISSUE TITLE
Piped left joins get no results

### ISSUE THREAD

**Issue by XoliloX** [tidyverse/dbplyr#998]
Dear all,

I'm currently working on an Azure database. I wrote piped left joins in order to gather data from different tables and nothing ever comes back. In comparison to my code, a colleague wrote an SQL query with the same purpose and it did work. Nonetheless, I would like to keep on working with dbplyr's verbs (otherwise I feel I'd have to work only with SQL) which is why I need some support.

Here's my reprex:

```
s <- memdb_frame("col1" = 1:10,"col2" = 2:11,"col3" = 3:12,"col4" = 4:13,"col5" = 5:14,"col6" = 6:15,"col7" = 7:16,"col8" = 8:17,"col9" = 9:18)
t <- memdb_frame("col10" = 10:19,"col11" = 11:20)
c <- memdb_frame("col1" = 1:10,"col12" = 12:21,"col13" = 13:22)
a <- memdb_frame("col14" = 14:23,"col15" = 15:24,"col16" = 16:25,"col17" = 17:26,"col18" = 18:27,"col19" = 19:28,"col20" = 20:29,"col21" = 21:30,"col8" = 8:17,"col22" = 22:31)
p <- memdb_frame("col23" = 23:32,"col24" = 24:33,"col25" = 25:34,"col5" = 5:14,"col26" = 26:35,"col27" = 27:36,"col28" = 28:37,"col29" = 29:38)

 left_join(s,t, 
          by = c("col1" = "col10"), 
          suffix = c("s","t"),
          x_as = "s",
          y_as = "t") %>%
  left_join(c, by = c("col9" = "col1"),
            suffix = c("s","c"),
            x_as = "s",
            y_as = "c") %>% 
  left_join(a, by = c("col11" = "col14"),
            suffix = c("t","a"),
            x_as = "t",
            y_as = "a")%>%
  left_join(p, by = c("col15" = "col23"),
            suffix = c("a","p"),
            x_as = "a",
            y_as = "p") %>% 
show_query()
```

which returns:

```
<SQL>
SELECT
  `col1`, `col2`,  `col3`,  `col4`,
  `a`.`col5` AS `col5a`,
  `col6`,  `col7`,`col8t`,`col9`,  `col11`,  `col12`,  `col13`,  `col15`,  `col16`,  `col17`,  `col18`,  `col19`,  `col20`,  `col21`,  `col8a`,  `col22`,  `col24`,  `col25`,
  `p`.`col5` AS `col5p`,
  `col26`,  `col27`,  `col28`,  `col29`
FROM (
  SELECT
    `col1`,    `col2`,`col3`,`col4`,`col5`, `col6`,`col7`,
    `t`.`col8` AS `col8t`,
    `col9`,    `col11`,`col12`,`col13`,`col15`,`col16`,`col17`,`col18`,`col19`,`col20`,`col21`,
    `a`.`col8` AS `col8a`,    `col22`
  FROM (
    SELECT
      `s`.`col1` AS `col1`,     
 `col2`,`col3`,`col4`,`col5`,`col6`,`col7`,`col8`,`col9`,`col11`,`col12`,`col13`
    FROM (
      SELECT
        `col1`,`col2`,`col3`,`col4`,`col5`,`col6`,`col7`,`col8`,`col9`,`col11`
      FROM `dbplyr_016` AS `s`
      LEFT JOIN `dbplyr_017` AS `t`
        ON (`s`.`col1` = `t`.`col10`)
    ) AS `s`
    LEFT JOIN `dbplyr_018` AS `c`
      ON (`s`.`col9` = `c`.`col1`)
  ) AS `t`
  LEFT JOIN `dbplyr_019` AS `a`
    ON (`t`.`col11` = `a`.`col14`)
) AS `a`
LEFT JOIN `dbplyr_020` AS `p`
  ON (`a`.`col15` = `p`.`col23`)
```

In comparison, the SQL query I received is:

```
SELECT s.col1,s.col2,s.col3,s.col4,s.col5,s.col6,s.col7,s.col8,s.col9,
t.col10,t.col11,
c.col1,c.col12,c.col13,
a.col14,a.col15,a.col16,a.col17,a.col18,a.col19,a.col20,a.col21,a.col22,a.col8,
p.col23,p.col24,p.col25,p.col26,p.col27,p.col28,p.col29,p.col5
FROM s as s
left join t as t
on s.col1= t.col10
left join c as c
on s.col9 = c.col1
left join a as a
on t.11 = a.14
left join p as p
on a.col15 = p.col23
```

Would you be able to tell me what could I improve to have dbplyr's creating more or less the same SQL query?

In advance, thanks a lot for your support.

Best regards,
D.

**Comment by mgirlich** [comment]
> I wrote piped left joins in order to gather data from different tables and nothing ever comes back.

I don't understand what you mean by that. You have to use `collect()` to execute the query and get data in R. Do you do that? Do you get an error message? Or does the query take so long?

> Would you be able to tell me what could I improve to have dbplyr's creating more or less the same SQL query?

With the CRAN version you can't. You can try out the version from PR #984 via `install_github("tidyverse/dbplyr#984")`. This gives a much nicer query if you change your joins slightly:

```sql
SELECT
  `s`.`col1` AS `col1`,
  `col2`,
  `col3`,
  `col4`,
  `s`.`col5` AS `col5a`,
  `col6`,
  `col7`,
  `s`.`col8` AS `col8t`,
  `col9`,
  `col11`,
  `col12`,
  `col13`,
  `col15`,
  `col16`,
  `col17`,
  `col18`,
  `col19`,
  `col20`,
  `col21`,
  `a`.`col8` AS `col8a`,
  `col22`,
  `col24`,
  `col25`,
  `p`.`col5` AS `col5p`,
  `col26`,
  `col27`,
  `col28`,
  `col29`
FROM `dbplyr_001` AS `s`
LEFT JOIN `dbplyr_002` AS `t`
  ON (`s`.`col1` = `t`.`col10`)
LEFT JOIN `dbplyr_003` AS `c`
  ON (`s`.`col9` = `c`.`col1`)
LEFT JOIN `dbplyr_004` AS `a`
  ON (`s`.`col11` = `a`.`col14`)
LEFT JOIN `dbplyr_005` AS `p`
  ON (`s`.`col15` = `p`.`col23`)
```

**Comment by XoliloX** [comment]
Hi @mgirlich,

Thanks for your answer !

1. `collect()` doens't seem to work, nor throw an error. But I've tried it for 10 rows of observations and it does not help returning any results (it runs forever)

2. I've tried unsuccessfully to `install_github("tidyverse/dbplyr#984")` and have gone through different types of error messages. I've updated all packages, including tidyverse (I also tried when uninstalled). My latest error message is

```
Error in unloadNamespace("dbplyr") : 
  namespace ‘dbplyr’ is imported by ‘tidyverse’ so cannot be unloaded
Execution halted
ERROR: lazy loading failed for package ‘dbplyr’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/dbplyr’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/dbplyr’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/sc/46j_rwx94g36925rdqpnm42m0000gn/T//Rtmp0CqSNr/fileaa7a6506fa4b/dbplyr_2.2.1.9000.tar.gz’ had non-zero exit status
Error: VECTOR_ELT() can only be applied to a 'list', not a 'closure'
```
I've looked into #832 and related type of issues but it did not help me. Do you know what to do?

3. You mention I should change the joins slightly, what do you mean exactly?

In advance, thanks a lot for your answer!

Best,
D.

**Comment by mgirlich** [comment]
> 1. `collect()` doens't seem to work, nor throw an error. But I've tried it for 10 rows of observations and it does not help returning any results (it runs forever)

Does `collect()` work for very simple things, e.g. something like `db_tbl %>% head(10) %>% collect()`?

> 2. I've tried unsuccessfully to `install_github("tidyverse/dbplyr#984")` and have gone through different types of error messages. I've updated all packages, including tidyverse (I also tried when uninstalled). My latest error message is

Restart your R session and do not load any package. That should help with installing the dev version.

> 3. You mention I should change the joins slightly, what do you mean exactly?

Only relevant after you installed the dev version. In your reprex you used `x_as = "s"` and later `x_as = "t"`. This forces dbplyr to use a new query.

**Comment by XoliloX** [comment]
Hi @mgirlich !

Thanks again for your feedback !

1. `collect()` does work on samples
2. Starting with no packages at all allowed me to install the PR #984, thanks a lot !! And it does produce much shorter SQL queries, this is amazing, thank you so much ! And I'm able to query results now, thanks a thousand times !!!!
3. Thank you for your advise on the naming of the joins

Thanks for all your help and for the development !!!

Best,
D.
