### ISSUE TITLE
Support for drop_na

### ISSUE THREAD

**Issue by slhck** [tidyverse/dbplyr#999]
It would be nice to have support for `drop_na` from `dplyr`.

It can be implemented as a filter with `!is.na(column)`, but this would make code more reusable, and it would be easier to call for multiple columns.

I was wondering if this has already been considered? I see some solutions suggested here: https://stackoverflow.com/a/66812251/435093 — but `paste0("!is.na(",colnames,")")` and `filter(!!!parse_exprs(conditions))` look like something that `dbplyr` won't do …

**Comment by mgirlich** [comment]
`drop_na()` might be declared as superseeded (See https://github.com/tidyverse/tidyr/issues/939). You can easily replace it with the help of `across()`: `filter(across(vars, ~ !is.na(.x))`

**Comment by slhck** [comment]
Thanks for the pointer!
